
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 2051

#include "2051.h"

#ifdef ENABLE_FACE_2051

lv_obj_t *face_2051;
lv_obj_t *face_2051_0_184;
lv_obj_t *face_2051_1_69330;
lv_obj_t *face_2051_2_69330;
lv_obj_t *face_2051_3_71232;
lv_obj_t *face_2051_4_71232;
lv_obj_t *face_2051_5_71232;
lv_obj_t *face_2051_6_71232;
lv_obj_t *face_2051_8_102190;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif

const lv_img_dsc_t *face_2051_dial_img_1_69330_group[] = {
	&face_2051_dial_img_1_69330_0,
	&face_2051_dial_img_1_69330_1,
	&face_2051_dial_img_1_69330_2,
	&face_2051_dial_img_1_69330_3,
	&face_2051_dial_img_1_69330_4,
	&face_2051_dial_img_1_69330_5,
	&face_2051_dial_img_1_69330_6,
	&face_2051_dial_img_1_69330_7,
	&face_2051_dial_img_1_69330_8,
	&face_2051_dial_img_1_69330_9,
};
const lv_img_dsc_t *face_2051_dial_img_3_71232_group[] = {
	&face_2051_dial_img_3_71232_0,
	&face_2051_dial_img_3_71232_1,
	&face_2051_dial_img_3_71232_2,
	&face_2051_dial_img_3_71232_3,
	&face_2051_dial_img_3_71232_4,
	&face_2051_dial_img_3_71232_5,
	&face_2051_dial_img_3_71232_6,
	&face_2051_dial_img_3_71232_7,
	&face_2051_dial_img_3_71232_8,
	&face_2051_dial_img_3_71232_9,
};
const lv_img_dsc_t *face_2051_dial_img_7_96684_group[] = {
	&face_2051_dial_img_7_96684_0,
	&face_2051_dial_img_7_96684_1,
	&face_2051_dial_img_7_96684_2,
	&face_2051_dial_img_7_96684_3,
	&face_2051_dial_img_7_96684_4,
	&face_2051_dial_img_7_96684_5,
	&face_2051_dial_img_7_96684_6,
};
const lv_img_dsc_t *face_2051_dial_img_8_102190_group[] = {
	&face_2051_dial_img_8_102190_0,
	&face_2051_dial_img_8_102190_1,
	&face_2051_dial_img_8_102190_2,
	&face_2051_dial_img_8_102190_3,
	&face_2051_dial_img_8_102190_4,
	&face_2051_dial_img_8_102190_5,
	&face_2051_dial_img_8_102190_6,
};




#endif

void init_face_2051(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **)){
#ifdef ENABLE_FACE_2051
    face_2051 = lv_obj_create(NULL);
    lv_obj_clear_flag(face_2051, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_2051, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_2051, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_2051, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_2051, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_2051, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_2051, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_2051, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_2051, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_2051_0_184 = lv_img_create(face_2051);
    lv_img_set_src(face_2051_0_184, &face_2051_dial_img_0_184_0);
    lv_obj_set_width(face_2051_0_184, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2051_0_184, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2051_0_184, 0);
    lv_obj_set_y(face_2051_0_184, 0);
    lv_obj_add_flag(face_2051_0_184, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2051_0_184, LV_OBJ_FLAG_SCROLLABLE );

    face_2051_1_69330 = lv_img_create(face_2051);
    lv_img_set_src(face_2051_1_69330, &face_2051_dial_img_1_69330_0);
    lv_obj_set_width(face_2051_1_69330, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2051_1_69330, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2051_1_69330, 209);
    lv_obj_set_y(face_2051_1_69330, 179);
    lv_obj_add_flag(face_2051_1_69330, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2051_1_69330, LV_OBJ_FLAG_SCROLLABLE );

    face_2051_2_69330 = lv_img_create(face_2051);
    lv_img_set_src(face_2051_2_69330, &face_2051_dial_img_1_69330_0);
    lv_obj_set_width(face_2051_2_69330, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2051_2_69330, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2051_2_69330, 196);
    lv_obj_set_y(face_2051_2_69330, 179);
    lv_obj_add_flag(face_2051_2_69330, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2051_2_69330, LV_OBJ_FLAG_SCROLLABLE );

    face_2051_3_71232 = lv_img_create(face_2051);
    lv_img_set_src(face_2051_3_71232, &face_2051_dial_img_3_71232_0);
    lv_obj_set_width(face_2051_3_71232, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2051_3_71232, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2051_3_71232, 183);
    lv_obj_set_y(face_2051_3_71232, 34);
    lv_obj_add_flag(face_2051_3_71232, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2051_3_71232, LV_OBJ_FLAG_SCROLLABLE );

    face_2051_4_71232 = lv_img_create(face_2051);
    lv_img_set_src(face_2051_4_71232, &face_2051_dial_img_3_71232_0);
    lv_obj_set_width(face_2051_4_71232, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2051_4_71232, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2051_4_71232, 135);
    lv_obj_set_y(face_2051_4_71232, 34);
    lv_obj_add_flag(face_2051_4_71232, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2051_4_71232, LV_OBJ_FLAG_SCROLLABLE );

    face_2051_5_71232 = lv_img_create(face_2051);
    lv_img_set_src(face_2051_5_71232, &face_2051_dial_img_3_71232_0);
    lv_obj_set_width(face_2051_5_71232, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2051_5_71232, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2051_5_71232, 183);
    lv_obj_set_y(face_2051_5_71232, 111);
    lv_obj_add_flag(face_2051_5_71232, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2051_5_71232, LV_OBJ_FLAG_SCROLLABLE );

    face_2051_6_71232 = lv_img_create(face_2051);
    lv_img_set_src(face_2051_6_71232, &face_2051_dial_img_3_71232_0);
    lv_obj_set_width(face_2051_6_71232, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2051_6_71232, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2051_6_71232, 135);
    lv_obj_set_y(face_2051_6_71232, 111);
    lv_obj_add_flag(face_2051_6_71232, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2051_6_71232, LV_OBJ_FLAG_SCROLLABLE );

    face_2051_8_102190 = lv_img_create(face_2051);
    lv_img_set_src(face_2051_8_102190, &face_2051_dial_img_8_102190_0);
    lv_obj_set_width(face_2051_8_102190, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2051_8_102190, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2051_8_102190, 138);
    lv_obj_set_y(face_2051_8_102190, 179);
    lv_obj_add_flag(face_2051_8_102190, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2051_8_102190, LV_OBJ_FLAG_SCROLLABLE );


    callback("2051", &face_2051_dial_img_preview_0, &face_2051, NULL);

#endif
}

void update_time_2051(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_2051
    if (!face_2051)
    {
        return;
    }
	lv_img_set_src(face_2051_1_69330, face_2051_dial_img_1_69330_group[(day / 1) % 10]);
	lv_img_set_src(face_2051_2_69330, face_2051_dial_img_1_69330_group[(day / 10) % 10]);
	lv_img_set_src(face_2051_3_71232, face_2051_dial_img_3_71232_group[(hour / 1) % 10]);
	lv_img_set_src(face_2051_4_71232, face_2051_dial_img_3_71232_group[(hour / 10) % 10]);
	lv_img_set_src(face_2051_5_71232, face_2051_dial_img_3_71232_group[(minute / 1) % 10]);
	lv_img_set_src(face_2051_6_71232, face_2051_dial_img_3_71232_group[(minute / 10) % 10]);
	lv_img_set_src(face_2051_8_102190, face_2051_dial_img_8_102190_group[((weekday + 6) / 1) % 7]);

#endif
}

void update_weather_2051(int temp, int icon)
{
#ifdef ENABLE_FACE_2051
    if (!face_2051)
    {
        return;
    }

#endif
}

void update_status_2051(int battery, bool connection){
#ifdef ENABLE_FACE_2051
    if (!face_2051)
    {
        return;
    }

#endif
}

void update_activity_2051(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_2051
    if (!face_2051)
    {
        return;
    }

#endif
}

void update_health_2051(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_2051
    if (!face_2051)
    {
        return;
    }

#endif
}

void update_all_2051(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_2051
    update_time_2051(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_2051(temp, icon);
    update_status_2051(battery, connection);
    update_activity_2051(steps, distance, kcal);
    update_health_2051(bpm, oxygen);
#endif
}

void update_check_2051(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_2051
    if (root != face_2051)
    {
        return;
    }
    update_time_2051(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_2051(temp, icon);
    update_status_2051(battery, connection);
    update_activity_2051(steps, distance, kcal);
    update_health_2051(bpm, oxygen);
#endif
}


