
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 2051

#ifndef _FACE_2051_H
#define _FACE_2051_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"
#include "app_hal.h"

//#define ENABLE_FACE_2051 // (2051) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_2051
    extern lv_obj_t *face_2051;
	extern lv_obj_t *face_2051_0_184;
	extern lv_obj_t *face_2051_1_69330;
	extern lv_obj_t *face_2051_2_69330;
	extern lv_obj_t *face_2051_3_71232;
	extern lv_obj_t *face_2051_4_71232;
	extern lv_obj_t *face_2051_5_71232;
	extern lv_obj_t *face_2051_6_71232;
	extern lv_obj_t *face_2051_8_102190;


	LV_IMG_DECLARE(face_2051_dial_img_0_184_0);
	LV_IMG_DECLARE(face_2051_dial_img_1_69330_0);
	LV_IMG_DECLARE(face_2051_dial_img_1_69330_1);
	LV_IMG_DECLARE(face_2051_dial_img_1_69330_2);
	LV_IMG_DECLARE(face_2051_dial_img_1_69330_3);
	LV_IMG_DECLARE(face_2051_dial_img_1_69330_4);
	LV_IMG_DECLARE(face_2051_dial_img_1_69330_5);
	LV_IMG_DECLARE(face_2051_dial_img_1_69330_6);
	LV_IMG_DECLARE(face_2051_dial_img_1_69330_7);
	LV_IMG_DECLARE(face_2051_dial_img_1_69330_8);
	LV_IMG_DECLARE(face_2051_dial_img_1_69330_9);
	LV_IMG_DECLARE(face_2051_dial_img_3_71232_0);
	LV_IMG_DECLARE(face_2051_dial_img_3_71232_1);
	LV_IMG_DECLARE(face_2051_dial_img_3_71232_2);
	LV_IMG_DECLARE(face_2051_dial_img_3_71232_3);
	LV_IMG_DECLARE(face_2051_dial_img_3_71232_4);
	LV_IMG_DECLARE(face_2051_dial_img_3_71232_5);
	LV_IMG_DECLARE(face_2051_dial_img_3_71232_6);
	LV_IMG_DECLARE(face_2051_dial_img_3_71232_7);
	LV_IMG_DECLARE(face_2051_dial_img_3_71232_8);
	LV_IMG_DECLARE(face_2051_dial_img_3_71232_9);
	LV_IMG_DECLARE(face_2051_dial_img_7_96684_0);
	LV_IMG_DECLARE(face_2051_dial_img_7_96684_1);
	LV_IMG_DECLARE(face_2051_dial_img_7_96684_2);
	LV_IMG_DECLARE(face_2051_dial_img_7_96684_3);
	LV_IMG_DECLARE(face_2051_dial_img_7_96684_4);
	LV_IMG_DECLARE(face_2051_dial_img_7_96684_5);
	LV_IMG_DECLARE(face_2051_dial_img_7_96684_6);
	LV_IMG_DECLARE(face_2051_dial_img_8_102190_0);
	LV_IMG_DECLARE(face_2051_dial_img_8_102190_1);
	LV_IMG_DECLARE(face_2051_dial_img_8_102190_2);
	LV_IMG_DECLARE(face_2051_dial_img_8_102190_3);
	LV_IMG_DECLARE(face_2051_dial_img_8_102190_4);
	LV_IMG_DECLARE(face_2051_dial_img_8_102190_5);
	LV_IMG_DECLARE(face_2051_dial_img_8_102190_6);
	LV_IMG_DECLARE(face_2051_dial_img_preview_0);
	LV_IMG_DECLARE(face_2051_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_2051(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **));
    void update_time_2051(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_2051(int temp, int icon);
    void update_status_2051(int battery, bool connection);
    void update_activity_2051(int steps, int distance, int kcal);
    void update_health_2051(int bpm, int oxygen);
    void update_all_2051(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_2051(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
