
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 34_2

#include "../34_2.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif


// LVGL 9 format (RGB565) // LVGL_9 compatible 
const LV_ATTRIBUTE_MEM_ALIGN uint8_t face_34_2_dial_img_1_58396_data_0[] = {
	//RGB565 data 
	0xA2,0x10,0x45,0x29,0x45,0x29,0x45,0x29,0x04,0x21,0x65,0x29,0x2C,0x63,0x2C,0x63,0x2C,0x63,0xAA,0x52,0x61,0x08,0xC3,0x18,0xC3,0x18,0xC3,0x18,0xA2,0x10,

	// Alpha Channel 
	0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,
    };
        


const lv_img_dsc_t face_34_2_dial_img_1_58396_0 = {
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.w = 5,
    .header.h = 3,
    .data_size = sizeof(face_34_2_dial_img_1_58396_data_0),
    .header.cf = LV_COLOR_FORMAT_NATIVE_WITH_ALPHA,
    .data = face_34_2_dial_img_1_58396_data_0};

    