
/**
 * @file touch_test.c
 * @brief Touch_test app for C3 UI
 * Generated by app_create.py
 */

#include "touch_test.h"

#ifdef ENABLE_APP_TOUCH_TEST

/* Replace NULL with your app icon eg &touch_test_icon */
REGISTER_APP("Touch Test", &ui_img_sample_png, touch_test_screen_main, touch_test_screen_init);

lv_obj_t *label;
lv_obj_t *dot;
lv_obj_t *button;

void touch_test_screen_event_cb(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START)
    {
        /* Do something before the screen is loaded */
    }
    if (event_code == LV_EVENT_SCREEN_LOADED)
    {
        /* Do something after the screen is loaded */
        /* This is a good place to start animations or timers */
        onGameOpened();
    }
    if (event_code == LV_EVENT_SCREEN_UNLOAD_START)
    {
        /* Do something before the screen is unloaded */
        /* This is a good place to save data or stop timers */
    }
    if (event_code == LV_EVENT_SCREEN_UNLOADED)
    {
        /* Do something after the screen is unloaded */
        /* This is a good place to clean up resources */

        onGameClosed();

        /* Clean and delete screen if needed */
        lv_obj_delete(touch_test_screen_main);
        touch_test_screen_main = NULL;
    }

    if (event_code == LV_EVENT_PRESSING)
    {
        /* Do something when the screen is pressed */
        /* You can get the coordinates of the press with `lv_indev_get_point(lv_indev_active(), &point);` */
        lv_point_t point;
        lv_indev_get_point(lv_indev_active(), &point);
        lv_obj_set_pos(dot, point.x - 10, point.y - 10);
        lv_obj_set_flag(dot, LV_OBJ_FLAG_HIDDEN, false);
#ifdef ESP32_CYD
        lv_obj_set_flag(button, LV_OBJ_FLAG_HIDDEN, true);
#endif

        lv_label_set_text_fmt(label, "Touched at (%d, %d)", point.x, point.y);
    }
    if (event_code == LV_EVENT_RELEASED)
    {
        /* Do something when the screen is released */
        lv_obj_set_flag(dot, LV_OBJ_FLAG_HIDDEN, true);
#ifdef ESP32_CYD
        lv_obj_set_flag(button, LV_OBJ_FLAG_HIDDEN, false);
#endif

        lv_label_set_text(label, "Released");
    }

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT)
    {
        ui_app_exit(); /* exit to app list */
        /* Call this function to close the app, you can even use button instead of gesture */
    }
}

void button_event_cb(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        /* Do something when the button is clicked */
        /* This is a good place to start an action or open a new screen */
        lv_label_set_text(label, "Restarting");
        // Add your recalibration code here
        clear_touch_calibration();
    }
}

void touch_test_screen_init(void)
{
    /* create the screen */
    touch_test_screen_main = lv_obj_create(NULL);
    lv_obj_remove_flag(touch_test_screen_main, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(touch_test_screen_main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(touch_test_screen_main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    label = lv_label_create(touch_test_screen_main);
    lv_obj_set_align(label, LV_ALIGN_CENTER);
    lv_label_set_text(label, "Hello world!\nTouch Test App");

    dot = lv_obj_create(touch_test_screen_main);
    lv_obj_remove_style_all(dot);
    lv_obj_set_size(dot, 20, 20);
    lv_obj_set_style_bg_color(dot, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(dot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(dot, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_align(dot, LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(dot, LV_OBJ_FLAG_HIDDEN);
    lv_obj_remove_flag(dot, LV_OBJ_FLAG_CLICKABLE);

#ifdef ESP32_CYD
    button = lv_button_create(touch_test_screen_main);
    lv_obj_set_align(button, LV_ALIGN_CENTER);
    lv_obj_set_y(button, 100);
    lv_obj_set_size(button, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_t *btn_label = lv_label_create(button);
    lv_label_set_text(btn_label, "Recalibrate");
    lv_obj_center(btn_label);
    lv_obj_add_event_cb(button, button_event_cb, LV_EVENT_CLICKED, NULL);
#endif

    lv_obj_add_event_cb(touch_test_screen_main, touch_test_screen_event_cb, LV_EVENT_ALL, NULL);
}

void __attribute__((weak)) clear_touch_calibration(void)
{
    lv_label_set_text(label, "Function not implemented.");
}

#endif

