
/**
 * @file touch_test.h
 * @brief Touch_test app for C3 UI
 * Generated by app_create.py
 */

#ifndef _TOUCH_TEST_APP_H
#define _TOUCH_TEST_APP_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"
#include "app_hal.h"
#include "../../common/app_manager.h"

// #define ENABLE_APP_TOUCH_TEST // Uncomment or define this to enable the touch_test app

#ifdef ENABLE_APP_TOUCH_TEST

    LV_IMAGE_DECLARE(ui_img_sample_png);

    void touch_test_screen_init(void);

    void onGameOpened(void);
    void onGameClosed(void);

    void ui_app_load(lv_obj_t **screen, void (*screen_init)(void));
    void ui_app_exit(void);

    void clear_touch_calibration(void);

#endif

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif /*_TOUCH_TEST_APP_H*/
