
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 2151

#ifndef _FACE_2151_H
#define _FACE_2151_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"
#include "app_hal.h"

//#define ENABLE_FACE_2151 // (2151) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_2151
    extern lv_obj_t *face_2151;
	extern lv_obj_t *face_2151_0_1184;
	extern lv_obj_t *face_2151_2_71732;
	extern lv_obj_t *face_2151_4_81495;
	extern lv_obj_t *face_2151_5_65535;
	extern lv_obj_t *face_2151_6_65535;
	extern lv_obj_t *face_2151_7_99366;
	extern lv_obj_t *face_2151_8_99366;
	extern lv_obj_t *face_2151_9_99366;
	extern lv_obj_t *face_2151_10_94363;
	extern lv_obj_t *face_2151_11_96315;
	extern lv_obj_t *face_2151_12_65535;
	extern lv_obj_t *face_2151_13_76712;
	extern lv_obj_t *face_2151_14_76712;
	extern lv_obj_t *face_2151_15_76712;
	extern lv_obj_t *face_2151_16_76712;
	extern lv_obj_t *face_2151_18_81161;
	extern lv_obj_t *face_2151_20_81309;
	extern lv_obj_t *face_2151_22_81824;
	extern lv_obj_t *face_2151_23_77864;
	extern lv_obj_t *face_2151_24_77864;
	extern lv_obj_t *face_2151_25_77864;
	extern lv_obj_t *face_2151_26_77864;
	extern lv_obj_t *face_2151_27_80776;
	extern lv_obj_t *face_2151_28_76712;
	extern lv_obj_t *face_2151_29_76712;
	extern lv_obj_t *face_2151_30_76712;
	extern lv_obj_t *face_2151_31_76712;
	extern lv_obj_t *face_2151_32_76712;
	extern lv_obj_t *face_2151_33_76712;
	extern lv_obj_t *face_2151_34_76712;
	extern lv_obj_t *face_2151_35_76712;
	extern lv_obj_t *face_2151_36_76712;
	extern lv_obj_t *face_2151_37_76712;
	extern lv_obj_t *face_2151_38_76712;
	extern lv_obj_t *face_2151_39_86586;
	extern lv_obj_t *face_2151_40_76712;
	extern lv_obj_t *face_2151_41_76712;
	extern lv_obj_t *face_2151_42_76712;
	extern lv_obj_t *face_2151_43_86814;
	extern lv_obj_t *face_2151_44_86829;
	extern lv_obj_t *face_2151_45_86829;
	extern lv_obj_t *face_2151_46_86829;
	extern lv_obj_t *face_2151_47_86829;
	extern lv_obj_t *face_2151_48_76584;
	extern lv_obj_t *face_2151_50_95294;


	LV_IMG_DECLARE(face_2151_dial_img_0_1184_0);
	LV_IMG_DECLARE(face_2151_dial_img_1_70814_0);
	LV_IMG_DECLARE(face_2151_dial_img_1_70814_1);
	LV_IMG_DECLARE(face_2151_dial_img_2_71732_0);
	LV_IMG_DECLARE(face_2151_dial_img_2_71732_1);
	LV_IMG_DECLARE(face_2151_dial_img_3_80802_0);
	LV_IMG_DECLARE(face_2151_dial_img_3_80802_1);
	LV_IMG_DECLARE(face_2151_dial_img_4_81495_0);
	LV_IMG_DECLARE(face_2151_dial_img_4_81495_1);
	LV_IMG_DECLARE(face_2151_dial_img_5_65535_0);
	LV_IMG_DECLARE(face_2151_dial_img_7_99366_0);
	LV_IMG_DECLARE(face_2151_dial_img_7_99366_1);
	LV_IMG_DECLARE(face_2151_dial_img_7_99366_2);
	LV_IMG_DECLARE(face_2151_dial_img_7_99366_3);
	LV_IMG_DECLARE(face_2151_dial_img_7_99366_4);
	LV_IMG_DECLARE(face_2151_dial_img_7_99366_5);
	LV_IMG_DECLARE(face_2151_dial_img_7_99366_6);
	LV_IMG_DECLARE(face_2151_dial_img_7_99366_7);
	LV_IMG_DECLARE(face_2151_dial_img_7_99366_8);
	LV_IMG_DECLARE(face_2151_dial_img_7_99366_9);
	LV_IMG_DECLARE(face_2151_dial_img_10_94363_0);
	LV_IMG_DECLARE(face_2151_dial_img_11_96315_0);
	LV_IMG_DECLARE(face_2151_dial_img_13_76712_0);
	LV_IMG_DECLARE(face_2151_dial_img_13_76712_1);
	LV_IMG_DECLARE(face_2151_dial_img_13_76712_2);
	LV_IMG_DECLARE(face_2151_dial_img_13_76712_3);
	LV_IMG_DECLARE(face_2151_dial_img_13_76712_4);
	LV_IMG_DECLARE(face_2151_dial_img_13_76712_5);
	LV_IMG_DECLARE(face_2151_dial_img_13_76712_6);
	LV_IMG_DECLARE(face_2151_dial_img_13_76712_7);
	LV_IMG_DECLARE(face_2151_dial_img_13_76712_8);
	LV_IMG_DECLARE(face_2151_dial_img_13_76712_9);
	LV_IMG_DECLARE(face_2151_dial_img_17_71222_0);
	LV_IMG_DECLARE(face_2151_dial_img_18_81161_0);
	LV_IMG_DECLARE(face_2151_dial_img_19_71477_0);
	LV_IMG_DECLARE(face_2151_dial_img_20_81309_0);
	LV_IMG_DECLARE(face_2151_dial_img_21_72140_0);
	LV_IMG_DECLARE(face_2151_dial_img_21_72140_1);
	LV_IMG_DECLARE(face_2151_dial_img_21_72140_2);
	LV_IMG_DECLARE(face_2151_dial_img_21_72140_3);
	LV_IMG_DECLARE(face_2151_dial_img_21_72140_4);
	LV_IMG_DECLARE(face_2151_dial_img_21_72140_5);
	LV_IMG_DECLARE(face_2151_dial_img_21_72140_6);
	LV_IMG_DECLARE(face_2151_dial_img_22_81824_0);
	LV_IMG_DECLARE(face_2151_dial_img_22_81824_1);
	LV_IMG_DECLARE(face_2151_dial_img_22_81824_2);
	LV_IMG_DECLARE(face_2151_dial_img_22_81824_3);
	LV_IMG_DECLARE(face_2151_dial_img_22_81824_4);
	LV_IMG_DECLARE(face_2151_dial_img_22_81824_5);
	LV_IMG_DECLARE(face_2151_dial_img_22_81824_6);
	LV_IMG_DECLARE(face_2151_dial_img_23_77864_0);
	LV_IMG_DECLARE(face_2151_dial_img_23_77864_1);
	LV_IMG_DECLARE(face_2151_dial_img_23_77864_2);
	LV_IMG_DECLARE(face_2151_dial_img_23_77864_3);
	LV_IMG_DECLARE(face_2151_dial_img_23_77864_4);
	LV_IMG_DECLARE(face_2151_dial_img_23_77864_5);
	LV_IMG_DECLARE(face_2151_dial_img_23_77864_6);
	LV_IMG_DECLARE(face_2151_dial_img_23_77864_7);
	LV_IMG_DECLARE(face_2151_dial_img_23_77864_8);
	LV_IMG_DECLARE(face_2151_dial_img_23_77864_9);
	LV_IMG_DECLARE(face_2151_dial_img_27_80776_0);
	LV_IMG_DECLARE(face_2151_dial_img_39_86586_0);
	LV_IMG_DECLARE(face_2151_dial_img_43_86814_0);
	LV_IMG_DECLARE(face_2151_dial_img_44_86829_0);
	LV_IMG_DECLARE(face_2151_dial_img_44_86829_1);
	LV_IMG_DECLARE(face_2151_dial_img_44_86829_2);
	LV_IMG_DECLARE(face_2151_dial_img_44_86829_3);
	LV_IMG_DECLARE(face_2151_dial_img_44_86829_4);
	LV_IMG_DECLARE(face_2151_dial_img_44_86829_5);
	LV_IMG_DECLARE(face_2151_dial_img_44_86829_6);
	LV_IMG_DECLARE(face_2151_dial_img_44_86829_7);
	LV_IMG_DECLARE(face_2151_dial_img_44_86829_8);
	LV_IMG_DECLARE(face_2151_dial_img_44_86829_9);
	LV_IMG_DECLARE(face_2151_dial_img_48_76584_0);
	LV_IMG_DECLARE(face_2151_dial_img_50_95294_0);
	LV_IMG_DECLARE(face_2151_dial_img_51_105316_0);
	LV_IMG_DECLARE(face_2151_dial_img_52_104235_0);
	LV_IMG_DECLARE(face_2151_dial_img_53_102007_0);
	LV_IMG_DECLARE(face_2151_dial_img_54_100998_0);
	LV_IMG_DECLARE(face_2151_dial_img_55_103078_0);
	LV_IMG_DECLARE(face_2151_dial_img_56_106393_0);
	LV_IMG_DECLARE(face_2151_dial_img_57_97232_0);
	LV_IMG_DECLARE(face_2151_dial_img_58_98351_0);
	LV_IMG_DECLARE(face_2151_dial_img_preview_0);
	LV_IMG_DECLARE(face_2151_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_2151(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **));
    void update_time_2151(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_2151(int temp, int icon);
    void update_status_2151(int battery, bool connection);
    void update_activity_2151(int steps, int distance, int kcal);
    void update_health_2151(int bpm, int oxygen);
    void update_all_2151(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_2151(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
