
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: SMART_RESIZED_466

#ifndef _FACE_SMART_RESIZED_466_H
#define _FACE_SMART_RESIZED_466_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"
#include "app_hal.h"

//#define ENABLE_FACE_SMART_RESIZED_466 // (Pixel) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_SMART_RESIZED_466
    extern lv_obj_t *face_smart_resized_466;
	extern lv_obj_t *face_smart_resized_466_0_784;
	extern lv_obj_t *face_smart_resized_466_2_218450;
	extern lv_obj_t *face_smart_resized_466_11_226951;
	extern lv_obj_t *face_smart_resized_466_12_226951;
	extern lv_obj_t *face_smart_resized_466_13_226951;
	extern lv_obj_t *face_smart_resized_466_14_226951;
	extern lv_obj_t *face_smart_resized_466_15_230735;
	extern lv_obj_t *face_smart_resized_466_16_226951;
	extern lv_obj_t *face_smart_resized_466_17_226951;
	extern lv_obj_t *face_smart_resized_466_18_226951;
	extern lv_obj_t *face_smart_resized_466_19_231066;
	extern lv_obj_t *face_smart_resized_466_20_244858;
	extern lv_obj_t *face_smart_resized_466_21_245289;
	extern lv_obj_t *face_smart_resized_466_22_245289;
	extern lv_obj_t *face_smart_resized_466_23_245289;
	extern lv_obj_t *face_smart_resized_466_27_245289;
	extern lv_obj_t *face_smart_resized_466_28_245289;
	extern lv_obj_t *face_smart_resized_466_29_245289;
	extern lv_obj_t *face_smart_resized_466_30_245289;
	extern lv_obj_t *face_smart_resized_466_31_245289;
	extern lv_obj_t *face_smart_resized_466_32_248473;
	extern lv_obj_t *face_smart_resized_466_33_248473;
	extern lv_obj_t *face_smart_resized_466_34_248473;
	extern lv_obj_t *face_smart_resized_466_35_248473;
	extern lv_obj_t *face_smart_resized_466_38_339440;


	LV_IMG_DECLARE(face_smart_resized_466_dial_img_0_784_0);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_2_218450_0);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_3_219530_0);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_4_220429_0);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_5_221308_0);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_6_222523_0);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_7_223384_0);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_8_224217_0);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_9_225102_0);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_10_225999_0);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_11_226951_0);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_11_226951_1);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_11_226951_2);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_11_226951_3);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_11_226951_4);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_11_226951_5);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_11_226951_6);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_11_226951_7);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_11_226951_8);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_11_226951_9);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_15_230735_0);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_19_231066_0);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_19_231066_1);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_19_231066_2);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_19_231066_3);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_19_231066_4);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_19_231066_5);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_19_231066_6);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_19_231066_7);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_19_231066_8);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_19_231066_9);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_19_231066_10);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_20_244858_0);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_21_245289_0);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_21_245289_1);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_21_245289_2);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_21_245289_3);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_21_245289_4);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_21_245289_5);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_21_245289_6);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_21_245289_7);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_21_245289_8);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_21_245289_9);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_32_248473_0);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_32_248473_1);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_32_248473_2);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_32_248473_3);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_32_248473_4);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_32_248473_5);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_32_248473_6);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_32_248473_7);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_32_248473_8);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_32_248473_9);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_37_322207_0);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_37_322207_1);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_37_322207_2);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_37_322207_3);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_37_322207_4);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_37_322207_5);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_37_322207_6);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_38_339440_0);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_38_339440_1);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_38_339440_2);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_38_339440_3);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_38_339440_4);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_38_339440_5);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_38_339440_6);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_preview_0);
	LV_IMG_DECLARE(face_smart_resized_466_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_smart_resized_466(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **));
    void update_time_smart_resized_466(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_smart_resized_466(int temp, int icon);
    void update_status_smart_resized_466(int battery, bool connection);
    void update_activity_smart_resized_466(int steps, int distance, int kcal);
    void update_health_smart_resized_466(int bpm, int oxygen);
    void update_all_smart_resized_466(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_smart_resized_466(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
