
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: SMART_RESIZED_466

#include "smart_resized_466.h"

#ifdef ENABLE_FACE_SMART_RESIZED_466

lv_obj_t *face_smart_resized_466;
lv_obj_t *face_smart_resized_466_0_784;
lv_obj_t *face_smart_resized_466_2_218450;
lv_obj_t *face_smart_resized_466_11_226951;
lv_obj_t *face_smart_resized_466_12_226951;
lv_obj_t *face_smart_resized_466_13_226951;
lv_obj_t *face_smart_resized_466_14_226951;
lv_obj_t *face_smart_resized_466_15_230735;
lv_obj_t *face_smart_resized_466_16_226951;
lv_obj_t *face_smart_resized_466_17_226951;
lv_obj_t *face_smart_resized_466_18_226951;
lv_obj_t *face_smart_resized_466_19_231066;
lv_obj_t *face_smart_resized_466_20_244858;
lv_obj_t *face_smart_resized_466_21_245289;
lv_obj_t *face_smart_resized_466_22_245289;
lv_obj_t *face_smart_resized_466_23_245289;
lv_obj_t *face_smart_resized_466_27_245289;
lv_obj_t *face_smart_resized_466_28_245289;
lv_obj_t *face_smart_resized_466_29_245289;
lv_obj_t *face_smart_resized_466_30_245289;
lv_obj_t *face_smart_resized_466_31_245289;
lv_obj_t *face_smart_resized_466_32_248473;
lv_obj_t *face_smart_resized_466_33_248473;
lv_obj_t *face_smart_resized_466_34_248473;
lv_obj_t *face_smart_resized_466_35_248473;
lv_obj_t *face_smart_resized_466_38_339440;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif

const lv_img_dsc_t *face_smart_resized_466_dial_img_weather[] = {
	&face_smart_resized_466_dial_img_2_218450_0,
	&face_smart_resized_466_dial_img_3_219530_0,
	&face_smart_resized_466_dial_img_4_220429_0,
	&face_smart_resized_466_dial_img_5_221308_0,
	&face_smart_resized_466_dial_img_6_222523_0,
	&face_smart_resized_466_dial_img_7_223384_0,
	&face_smart_resized_466_dial_img_8_224217_0,
	&face_smart_resized_466_dial_img_9_225102_0,
	&face_smart_resized_466_dial_img_10_225999_0,
};
const lv_img_dsc_t *face_smart_resized_466_dial_img_11_226951_group[] = {
	&face_smart_resized_466_dial_img_11_226951_0,
	&face_smart_resized_466_dial_img_11_226951_1,
	&face_smart_resized_466_dial_img_11_226951_2,
	&face_smart_resized_466_dial_img_11_226951_3,
	&face_smart_resized_466_dial_img_11_226951_4,
	&face_smart_resized_466_dial_img_11_226951_5,
	&face_smart_resized_466_dial_img_11_226951_6,
	&face_smart_resized_466_dial_img_11_226951_7,
	&face_smart_resized_466_dial_img_11_226951_8,
	&face_smart_resized_466_dial_img_11_226951_9,
};
const lv_img_dsc_t *face_smart_resized_466_dial_img_19_231066_group[] = {
	&face_smart_resized_466_dial_img_19_231066_0,
	&face_smart_resized_466_dial_img_19_231066_1,
	&face_smart_resized_466_dial_img_19_231066_2,
	&face_smart_resized_466_dial_img_19_231066_3,
	&face_smart_resized_466_dial_img_19_231066_4,
	&face_smart_resized_466_dial_img_19_231066_5,
	&face_smart_resized_466_dial_img_19_231066_6,
	&face_smart_resized_466_dial_img_19_231066_7,
	&face_smart_resized_466_dial_img_19_231066_8,
	&face_smart_resized_466_dial_img_19_231066_9,
	&face_smart_resized_466_dial_img_19_231066_10,
};
const lv_img_dsc_t *face_smart_resized_466_dial_img_21_245289_group[] = {
	&face_smart_resized_466_dial_img_21_245289_0,
	&face_smart_resized_466_dial_img_21_245289_1,
	&face_smart_resized_466_dial_img_21_245289_2,
	&face_smart_resized_466_dial_img_21_245289_3,
	&face_smart_resized_466_dial_img_21_245289_4,
	&face_smart_resized_466_dial_img_21_245289_5,
	&face_smart_resized_466_dial_img_21_245289_6,
	&face_smart_resized_466_dial_img_21_245289_7,
	&face_smart_resized_466_dial_img_21_245289_8,
	&face_smart_resized_466_dial_img_21_245289_9,
};
const lv_img_dsc_t *face_smart_resized_466_dial_img_32_248473_group[] = {
	&face_smart_resized_466_dial_img_32_248473_0,
	&face_smart_resized_466_dial_img_32_248473_1,
	&face_smart_resized_466_dial_img_32_248473_2,
	&face_smart_resized_466_dial_img_32_248473_3,
	&face_smart_resized_466_dial_img_32_248473_4,
	&face_smart_resized_466_dial_img_32_248473_5,
	&face_smart_resized_466_dial_img_32_248473_6,
	&face_smart_resized_466_dial_img_32_248473_7,
	&face_smart_resized_466_dial_img_32_248473_8,
	&face_smart_resized_466_dial_img_32_248473_9,
};
const lv_img_dsc_t *face_smart_resized_466_dial_img_37_322207_group[] = {
	&face_smart_resized_466_dial_img_37_322207_0,
	&face_smart_resized_466_dial_img_37_322207_1,
	&face_smart_resized_466_dial_img_37_322207_2,
	&face_smart_resized_466_dial_img_37_322207_3,
	&face_smart_resized_466_dial_img_37_322207_4,
	&face_smart_resized_466_dial_img_37_322207_5,
	&face_smart_resized_466_dial_img_37_322207_6,
};
const lv_img_dsc_t *face_smart_resized_466_dial_img_38_339440_group[] = {
	&face_smart_resized_466_dial_img_38_339440_0,
	&face_smart_resized_466_dial_img_38_339440_1,
	&face_smart_resized_466_dial_img_38_339440_2,
	&face_smart_resized_466_dial_img_38_339440_3,
	&face_smart_resized_466_dial_img_38_339440_4,
	&face_smart_resized_466_dial_img_38_339440_5,
	&face_smart_resized_466_dial_img_38_339440_6,
};




#endif

void init_face_smart_resized_466(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **)){
#ifdef ENABLE_FACE_SMART_RESIZED_466
    face_smart_resized_466 = lv_obj_create(NULL);
    lv_obj_clear_flag(face_smart_resized_466, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_smart_resized_466, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_smart_resized_466, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_smart_resized_466, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_smart_resized_466, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_smart_resized_466, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_smart_resized_466, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_smart_resized_466, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_smart_resized_466, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_smart_resized_466_0_784 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_0_784, &face_smart_resized_466_dial_img_0_784_0);
    lv_obj_set_width(face_smart_resized_466_0_784, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_0_784, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_0_784, 0);
    lv_obj_set_y(face_smart_resized_466_0_784, 0);
    lv_obj_add_flag(face_smart_resized_466_0_784, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_0_784, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_2_218450 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_2_218450, &face_smart_resized_466_dial_img_2_218450_0);
    lv_obj_set_width(face_smart_resized_466_2_218450, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_2_218450, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_2_218450, 209);
    lv_obj_set_y(face_smart_resized_466_2_218450, 7);
    lv_obj_add_flag(face_smart_resized_466_2_218450, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_2_218450, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_11_226951 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_11_226951, &face_smart_resized_466_dial_img_11_226951_0);
    lv_obj_set_width(face_smart_resized_466_11_226951, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_11_226951, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_11_226951, 384);
    lv_obj_set_y(face_smart_resized_466_11_226951, 182);
    lv_obj_add_flag(face_smart_resized_466_11_226951, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_11_226951, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_12_226951 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_12_226951, &face_smart_resized_466_dial_img_11_226951_0);
    lv_obj_set_width(face_smart_resized_466_12_226951, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_12_226951, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_12_226951, 366);
    lv_obj_set_y(face_smart_resized_466_12_226951, 182);
    lv_obj_add_flag(face_smart_resized_466_12_226951, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_12_226951, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_13_226951 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_13_226951, &face_smart_resized_466_dial_img_11_226951_0);
    lv_obj_set_width(face_smart_resized_466_13_226951, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_13_226951, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_13_226951, 314);
    lv_obj_set_y(face_smart_resized_466_13_226951, 182);
    lv_obj_add_flag(face_smart_resized_466_13_226951, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_13_226951, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_14_226951 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_14_226951, &face_smart_resized_466_dial_img_11_226951_0);
    lv_obj_set_width(face_smart_resized_466_14_226951, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_14_226951, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_14_226951, 297);
    lv_obj_set_y(face_smart_resized_466_14_226951, 182);
    lv_obj_add_flag(face_smart_resized_466_14_226951, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_14_226951, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_15_230735 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_15_230735, &face_smart_resized_466_dial_img_15_230735_0);
    lv_obj_set_width(face_smart_resized_466_15_230735, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_15_230735, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_15_230735, 341);
    lv_obj_set_y(face_smart_resized_466_15_230735, 180);
    lv_obj_add_flag(face_smart_resized_466_15_230735, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_15_230735, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_16_226951 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_16_226951, &face_smart_resized_466_dial_img_11_226951_0);
    lv_obj_set_width(face_smart_resized_466_16_226951, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_16_226951, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_16_226951, 116);
    lv_obj_set_y(face_smart_resized_466_16_226951, 240);
    lv_obj_add_flag(face_smart_resized_466_16_226951, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_16_226951, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_17_226951 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_17_226951, &face_smart_resized_466_dial_img_11_226951_0);
    lv_obj_set_width(face_smart_resized_466_17_226951, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_17_226951, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_17_226951, 99);
    lv_obj_set_y(face_smart_resized_466_17_226951, 240);
    lv_obj_add_flag(face_smart_resized_466_17_226951, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_17_226951, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_18_226951 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_18_226951, &face_smart_resized_466_dial_img_11_226951_0);
    lv_obj_set_width(face_smart_resized_466_18_226951, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_18_226951, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_18_226951, 81);
    lv_obj_set_y(face_smart_resized_466_18_226951, 240);
    lv_obj_add_flag(face_smart_resized_466_18_226951, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_18_226951, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_19_231066 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_19_231066, &face_smart_resized_466_dial_img_19_231066_0);
    lv_obj_set_width(face_smart_resized_466_19_231066, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_19_231066, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_19_231066, 13);
    lv_obj_set_y(face_smart_resized_466_19_231066, 244);
    lv_obj_add_flag(face_smart_resized_466_19_231066, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_19_231066, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_20_244858 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_20_244858, &face_smart_resized_466_dial_img_20_244858_0);
    lv_obj_set_width(face_smart_resized_466_20_244858, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_20_244858, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_20_244858, 139);
    lv_obj_set_y(face_smart_resized_466_20_244858, 248);
    lv_obj_add_flag(face_smart_resized_466_20_244858, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_20_244858, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_21_245289 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_21_245289, &face_smart_resized_466_dial_img_21_245289_0);
    lv_obj_set_width(face_smart_resized_466_21_245289, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_21_245289, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_21_245289, 97);
    lv_obj_set_y(face_smart_resized_466_21_245289, 322);
    lv_obj_add_flag(face_smart_resized_466_21_245289, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_21_245289, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_22_245289 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_22_245289, &face_smart_resized_466_dial_img_21_245289_0);
    lv_obj_set_width(face_smart_resized_466_22_245289, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_22_245289, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_22_245289, 81);
    lv_obj_set_y(face_smart_resized_466_22_245289, 322);
    lv_obj_add_flag(face_smart_resized_466_22_245289, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_22_245289, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_23_245289 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_23_245289, &face_smart_resized_466_dial_img_21_245289_0);
    lv_obj_set_width(face_smart_resized_466_23_245289, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_23_245289, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_23_245289, 64);
    lv_obj_set_y(face_smart_resized_466_23_245289, 322);
    lv_obj_add_flag(face_smart_resized_466_23_245289, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_23_245289, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_27_245289 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_27_245289, &face_smart_resized_466_dial_img_21_245289_0);
    lv_obj_set_width(face_smart_resized_466_27_245289, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_27_245289, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_27_245289, 199);
    lv_obj_set_y(face_smart_resized_466_27_245289, 382);
    lv_obj_add_flag(face_smart_resized_466_27_245289, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_27_245289, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_28_245289 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_28_245289, &face_smart_resized_466_dial_img_21_245289_0);
    lv_obj_set_width(face_smart_resized_466_28_245289, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_28_245289, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_28_245289, 184);
    lv_obj_set_y(face_smart_resized_466_28_245289, 382);
    lv_obj_add_flag(face_smart_resized_466_28_245289, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_28_245289, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_29_245289 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_29_245289, &face_smart_resized_466_dial_img_21_245289_0);
    lv_obj_set_width(face_smart_resized_466_29_245289, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_29_245289, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_29_245289, 168);
    lv_obj_set_y(face_smart_resized_466_29_245289, 382);
    lv_obj_add_flag(face_smart_resized_466_29_245289, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_29_245289, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_30_245289 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_30_245289, &face_smart_resized_466_dial_img_21_245289_0);
    lv_obj_set_width(face_smart_resized_466_30_245289, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_30_245289, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_30_245289, 153);
    lv_obj_set_y(face_smart_resized_466_30_245289, 382);
    lv_obj_add_flag(face_smart_resized_466_30_245289, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_30_245289, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_31_245289 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_31_245289, &face_smart_resized_466_dial_img_21_245289_0);
    lv_obj_set_width(face_smart_resized_466_31_245289, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_31_245289, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_31_245289, 137);
    lv_obj_set_y(face_smart_resized_466_31_245289, 382);
    lv_obj_add_flag(face_smart_resized_466_31_245289, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_31_245289, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_32_248473 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_32_248473, &face_smart_resized_466_dial_img_32_248473_0);
    lv_obj_set_width(face_smart_resized_466_32_248473, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_32_248473, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_32_248473, 139);
    lv_obj_set_y(face_smart_resized_466_32_248473, 114);
    lv_obj_add_flag(face_smart_resized_466_32_248473, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_32_248473, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_33_248473 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_33_248473, &face_smart_resized_466_dial_img_32_248473_0);
    lv_obj_set_width(face_smart_resized_466_33_248473, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_33_248473, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_33_248473, 66);
    lv_obj_set_y(face_smart_resized_466_33_248473, 114);
    lv_obj_add_flag(face_smart_resized_466_33_248473, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_33_248473, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_34_248473 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_34_248473, &face_smart_resized_466_dial_img_32_248473_0);
    lv_obj_set_width(face_smart_resized_466_34_248473, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_34_248473, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_34_248473, 330);
    lv_obj_set_y(face_smart_resized_466_34_248473, 236);
    lv_obj_add_flag(face_smart_resized_466_34_248473, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_34_248473, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_35_248473 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_35_248473, &face_smart_resized_466_dial_img_32_248473_0);
    lv_obj_set_width(face_smart_resized_466_35_248473, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_35_248473, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_35_248473, 236);
    lv_obj_set_y(face_smart_resized_466_35_248473, 236);
    lv_obj_add_flag(face_smart_resized_466_35_248473, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_35_248473, LV_OBJ_FLAG_SCROLLABLE );

    face_smart_resized_466_38_339440 = lv_img_create(face_smart_resized_466);
    lv_img_set_src(face_smart_resized_466_38_339440, &face_smart_resized_466_dial_img_38_339440_0);
    lv_obj_set_width(face_smart_resized_466_38_339440, LV_SIZE_CONTENT);
    lv_obj_set_height(face_smart_resized_466_38_339440, LV_SIZE_CONTENT);
    lv_obj_set_x(face_smart_resized_466_38_339440, 312);
    lv_obj_set_y(face_smart_resized_466_38_339440, 66);
    lv_obj_add_flag(face_smart_resized_466_38_339440, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_smart_resized_466_38_339440, LV_OBJ_FLAG_SCROLLABLE );


    callback("Pixel", &face_smart_resized_466_dial_img_preview_0, &face_smart_resized_466, NULL);

#endif
}

void update_time_smart_resized_466(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_SMART_RESIZED_466
    if (!face_smart_resized_466)
    {
        return;
    }
	lv_img_set_src(face_smart_resized_466_11_226951, face_smart_resized_466_dial_img_11_226951_group[(month / 1) % 10]);
	lv_img_set_src(face_smart_resized_466_12_226951, face_smart_resized_466_dial_img_11_226951_group[(month / 10) % 10]);
	lv_img_set_src(face_smart_resized_466_13_226951, face_smart_resized_466_dial_img_11_226951_group[(day / 1) % 10]);
	lv_img_set_src(face_smart_resized_466_14_226951, face_smart_resized_466_dial_img_11_226951_group[(day / 10) % 10]);
	lv_img_set_src(face_smart_resized_466_32_248473, face_smart_resized_466_dial_img_32_248473_group[(hour / 1) % 10]);
	lv_img_set_src(face_smart_resized_466_33_248473, face_smart_resized_466_dial_img_32_248473_group[(hour / 10) % 10]);
	lv_img_set_src(face_smart_resized_466_34_248473, face_smart_resized_466_dial_img_32_248473_group[(minute / 1) % 10]);
	lv_img_set_src(face_smart_resized_466_35_248473, face_smart_resized_466_dial_img_32_248473_group[(minute / 10) % 10]);
	lv_img_set_src(face_smart_resized_466_38_339440, face_smart_resized_466_dial_img_38_339440_group[((weekday + 6) / 1) % 7]);

#endif
}

void update_weather_smart_resized_466(int temp, int icon)
{
#ifdef ENABLE_FACE_SMART_RESIZED_466
    if (!face_smart_resized_466)
    {
        return;
    }
	lv_img_set_src(face_smart_resized_466_2_218450, face_smart_resized_466_dial_img_weather[icon % 8]);

#endif
}

void update_status_smart_resized_466(int battery, bool connection){
#ifdef ENABLE_FACE_SMART_RESIZED_466
    if (!face_smart_resized_466)
    {
        return;
    }
	lv_img_set_src(face_smart_resized_466_16_226951, face_smart_resized_466_dial_img_11_226951_group[(battery / 1) % 10]);
	lv_img_set_src(face_smart_resized_466_17_226951, face_smart_resized_466_dial_img_11_226951_group[(battery / 10) % 10]);
	lv_img_set_src(face_smart_resized_466_18_226951, face_smart_resized_466_dial_img_11_226951_group[(battery / 100) % 10]);
	if (battery < 100)
	{
		lv_obj_add_flag(face_smart_resized_466_18_226951, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_smart_resized_466_18_226951, LV_OBJ_FLAG_HIDDEN);
	}
	lv_img_set_src(face_smart_resized_466_19_231066, face_smart_resized_466_dial_img_19_231066_group[(battery / (100 / 11)) % 11]);

#endif
}

void update_activity_smart_resized_466(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_SMART_RESIZED_466
    if (!face_smart_resized_466)
    {
        return;
    }
	lv_img_set_src(face_smart_resized_466_27_245289, face_smart_resized_466_dial_img_21_245289_group[(steps / 1) % 10]);
	lv_img_set_src(face_smart_resized_466_28_245289, face_smart_resized_466_dial_img_21_245289_group[(steps / 10) % 10]);
	lv_img_set_src(face_smart_resized_466_29_245289, face_smart_resized_466_dial_img_21_245289_group[(steps / 100) % 10]);
	lv_img_set_src(face_smart_resized_466_30_245289, face_smart_resized_466_dial_img_21_245289_group[(steps / 1000) % 10]);
	lv_img_set_src(face_smart_resized_466_31_245289, face_smart_resized_466_dial_img_21_245289_group[(steps / 10000) % 10]);

#endif
}

void update_health_smart_resized_466(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_SMART_RESIZED_466
    if (!face_smart_resized_466)
    {
        return;
    }
	lv_img_set_src(face_smart_resized_466_21_245289, face_smart_resized_466_dial_img_21_245289_group[(bpm / 1) % 10]);
	lv_img_set_src(face_smart_resized_466_22_245289, face_smart_resized_466_dial_img_21_245289_group[(bpm / 10) % 10]);
	lv_img_set_src(face_smart_resized_466_23_245289, face_smart_resized_466_dial_img_21_245289_group[(bpm / 100) % 10]);

#endif
}

void update_all_smart_resized_466(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_SMART_RESIZED_466
    update_time_smart_resized_466(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_smart_resized_466(temp, icon);
    update_status_smart_resized_466(battery, connection);
    update_activity_smart_resized_466(steps, distance, kcal);
    update_health_smart_resized_466(bpm, oxygen);
#endif
}

void update_check_smart_resized_466(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_SMART_RESIZED_466
    if (root != face_smart_resized_466)
    {
        return;
    }
    update_time_smart_resized_466(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_smart_resized_466(temp, icon);
    update_status_smart_resized_466(battery, connection);
    update_activity_smart_resized_466(steps, distance, kcal);
    update_health_smart_resized_466(bpm, oxygen);
#endif
}


