
/**
 * @file range.h
 * @brief Range app for C3 UI
 * Generated by app_create.py
 */

#ifndef _RANGE_APP_H
#define _RANGE_APP_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"
#include "app_hal.h"
#include "../../common/app_manager.h"
#include "../../common/input_bus/input_bus.h"

// #define ENABLE_APP_RANGE // Uncomment or define this to enable the range app

#ifdef ENABLE_APP_RANGE

    // LV_IMAGE_DECLARE(range_icon);

    void range_screen_init(void);

    void ui_app_load(lv_obj_t **screen, void (*screen_init)(void));
    void ui_app_exit(void);

    int32_t read_encoder_position();

    void onGameOpened(void);
    void onGameClosed(void);

#endif

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif /*_RANGE_APP_H*/
