import re, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from lvgl_img import decode_to_rgba, encode_from_rgba, format_c_array
from PIL import Image

# One-off (like the pivot-cap colour-sampling script from the 2026-07-22 session):
# composites face_citizen_410_dial_img onto face_citizen_410_body_bg at the exact
# offset citizen_410.c draws them at today (DIAL_SHIFT_X=-3, Y_OFFSET=42), producing
# a single opaque 410x494 RGB565 asset so the two draws collapse into one.

ASSET_DIR = "/home/greg/chronos-watch/src/faces/citizen_410/assets"
DIAL_SHIFT_X = -3
Y_OFFSET = 42  # (494 - 410) / 2, matches citizen_410.c's #define

def parse(fname):
    path = os.path.join(ASSET_DIR, fname)
    src = open(path).read()
    name = re.search(r'uint8_t (\w+)_data\[\]', src).group(1)
    w = int(re.search(r'\.header\.w\s*=\s*(\d+)', src).group(1))
    h = int(re.search(r'\.header\.h\s*=\s*(\d+)', src).group(1))
    has_alpha = 'NATIVE_WITH_ALPHA' in src
    m = re.search(rf'{name}_data\[\]\s*=\s*\{{(.*?)\}};', src, re.S)
    body = re.sub(r'//[^\n]*', '', m.group(1))
    vals = bytes(int(x.strip(), 16) for x in body.split(',') if x.strip())
    return name, w, h, vals, has_alpha

body_name, bw, bh, bvals, b_alpha = parse("face_citizen_410_body_bg.c")
dial_name, dw, dh, dvals, d_alpha = parse("face_citizen_410_dial_img.c")
assert not b_alpha and d_alpha, "unexpected format - body_bg should be opaque, dial_img should have alpha"

body_img = decode_to_rgba(bw, bh, bvals, b_alpha).convert("RGBA")
dial_img = decode_to_rgba(dw, dh, dvals, d_alpha)

merged = body_img.copy()
merged.alpha_composite(dial_img, (DIAL_SHIFT_X, Y_OFFSET))
merged = merged.convert("RGB").convert("RGBA")  # drop to opaque (alpha=255 everywhere)

data = encode_from_rgba(merged, has_alpha=False)

out_name = "face_citizen_410_face_bg"
out_path = os.path.join(ASSET_DIR, f"{out_name}.c")
c_src = f'''// Generated by tools/facegen/merge_citizen_410_bg.py: face_citizen_410_body_bg with
// face_citizen_410_dial_img composited on top at the exact offset citizen_410.c used to
// draw them separately (DIAL_SHIFT_X={DIAL_SHIFT_X}, Y_OFFSET={Y_OFFSET}), collapsing the
// two-image draw into one opaque {bw}x{bh} asset. Source assets' own history/derivation
// notes (pattern-matched crop, alpha falloff, etc.) still apply - see git log for
// face_citizen_410_body_bg.c / face_citizen_410_dial_img.c prior to this commit.

#include "../citizen_410.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

const LV_ATTRIBUTE_MEM_ALIGN uint8_t {out_name}_data[] = {{
\t//RGB565 data
{format_c_array(data)}
}};

const lv_img_dsc_t {out_name} = {{
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.w = {bw},
    .header.h = {bh},
    .data_size = sizeof({out_name}_data),
    .header.cf = LV_COLOR_FORMAT_RGB565,
    .data = {out_name}_data}};
'''
with open(out_path, "w") as f:
    f.write(c_src)

print(f"wrote {out_path} ({bw}x{bh}, opaque RGB565, {len(data)} bytes)")
