// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.3
// Project name: C3_Watch

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void onLoadHome(lv_event_t * e);
void onClickAlert(lv_event_t * e);
void onForecastOpen(lv_event_t * e);
void onWeatherLoad(lv_event_t * e);
void onNotificationsOpen(lv_event_t * e);
void onBrightnessChange(lv_event_t * e);
void onScrollMode(lv_event_t * e);
void onTimeoutChange(lv_event_t * e);
void onRotateChange(lv_event_t * e);
void onLanguageChange(lv_event_t * e);
void onBatteryChange(lv_event_t * e);
void onEndSearch(lv_event_t * e);
void onMusicPlay(lv_event_t * e);
void onMusicPrevious(lv_event_t * e);
void onMusicNext(lv_event_t * e);
void onStartSearch(lv_event_t * e);
void onEndSearch(lv_event_t * e);
void onVolumeUp(lv_event_t * e);
void onVolumeDown(lv_event_t * e);
void onAlertState(lv_event_t *e);
void onNavState(lv_event_t *e);
void onFaceSelected(lv_event_t *e);
void onCustomFaceSelected(int pathIndex);
void onMessageClick(lv_event_t *e);
void onCaptureClick(lv_event_t *e);

void onWatchfaceChange(lv_event_t * e);

void on_watchface_list_open();
void on_alert_state_change(int32_t states);
void set_alert_states(int32_t states);


void savePrefInt(const char* key, int value);
int getPrefInt(const char* key, int def_value);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
