
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: GREEN_FLAME_360

#ifndef _FACE_GREEN_FLAME_360_H
#define _FACE_GREEN_FLAME_360_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"
#include "app_hal.h"

//#define ENABLE_FACE_GREEN_FLAME_360 // (Green Flame) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_GREEN_FLAME_360
    extern lv_obj_t *face_green_flame_360;
	extern lv_obj_t *face_green_flame_360_0_484;
	extern lv_obj_t *face_green_flame_360_1_259684;
	extern lv_obj_t *face_green_flame_360_2_262684;
	extern lv_obj_t *face_green_flame_360_3_262684;
	extern lv_obj_t *face_green_flame_360_4_319314;
	extern lv_obj_t *face_green_flame_360_5_319314;
	extern lv_obj_t *face_green_flame_360_6_260010;
	extern lv_obj_t *face_green_flame_360_7_260010;
	extern lv_obj_t *face_green_flame_360_8_260010;
	extern lv_obj_t *face_green_flame_360_9_260010;
	extern lv_obj_t *face_green_flame_360_11_385756;
	extern lv_obj_t *face_green_flame_360_12_260010;
	extern lv_obj_t *face_green_flame_360_13_260010;
	extern lv_obj_t *face_green_flame_360_14_260010;
	extern lv_obj_t *face_green_flame_360_15_260010;
	extern lv_obj_t *face_green_flame_360_16_260010;
	extern lv_obj_t *face_green_flame_360_17_260010;
	extern lv_obj_t *face_green_flame_360_18_260010;
	extern lv_obj_t *face_green_flame_360_19_260010;
	extern lv_obj_t *face_green_flame_360_20_260010;
	extern lv_obj_t *face_green_flame_360_21_260010;
	extern lv_obj_t *face_green_flame_360_22_260010;
	extern lv_obj_t *face_green_flame_360_23_260010;


	LV_IMG_DECLARE(face_green_flame_360_dial_img_0_484_0);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_1_259684_0);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_2_262684_0);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_2_262684_1);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_2_262684_2);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_2_262684_3);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_2_262684_4);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_2_262684_5);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_2_262684_6);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_2_262684_7);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_2_262684_8);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_2_262684_9);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_4_319314_0);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_4_319314_1);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_4_319314_2);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_4_319314_3);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_4_319314_4);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_4_319314_5);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_4_319314_6);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_4_319314_7);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_4_319314_8);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_4_319314_9);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_6_260010_0);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_6_260010_1);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_6_260010_2);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_6_260010_3);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_6_260010_4);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_6_260010_5);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_6_260010_6);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_6_260010_7);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_6_260010_8);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_6_260010_9);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_10_376076_0);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_10_376076_1);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_10_376076_2);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_10_376076_3);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_10_376076_4);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_10_376076_5);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_10_376076_6);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_11_385756_0);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_11_385756_1);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_11_385756_2);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_11_385756_3);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_11_385756_4);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_11_385756_5);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_11_385756_6);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_preview_0);
	LV_IMG_DECLARE(face_green_flame_360_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_green_flame_360(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **));
    void update_time_green_flame_360(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_green_flame_360(int temp, int icon);
    void update_status_green_flame_360(int battery, bool connection);
    void update_activity_green_flame_360(int steps, int distance, int kcal);
    void update_health_green_flame_360(int bpm, int oxygen);
    void update_all_green_flame_360(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_green_flame_360(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
