
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 756_2

#ifndef _FACE_756_2_H
#define _FACE_756_2_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"
#include "app_hal.h"

//#define ENABLE_FACE_756_2 // (Red) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_756_2
    extern lv_obj_t *face_756_2;
	extern lv_obj_t *face_756_2_0_424;
	extern lv_obj_t *face_756_2_2_15014;
	extern lv_obj_t *face_756_2_3_18734;
	extern lv_obj_t *face_756_2_5_22382;
	extern lv_obj_t *face_756_2_6_25488;
	extern lv_obj_t *face_756_2_7_25488;
	extern lv_obj_t *face_756_2_8_81874;
	extern lv_obj_t *face_756_2_9_81874;
	extern lv_obj_t *face_756_2_10_22752;
	extern lv_obj_t *face_756_2_11_22752;
	extern lv_obj_t *face_756_2_12_22752;
	extern lv_obj_t *face_756_2_13_22752;
	extern lv_obj_t *face_756_2_14_22752;
	extern lv_obj_t *face_756_2_15_22752;
	extern lv_obj_t *face_756_2_16_22752;
	extern lv_obj_t *face_756_2_17_17160;
	extern lv_obj_t *face_756_2_18_17160;
	extern lv_obj_t *face_756_2_20_105728;


	LV_IMG_DECLARE(face_756_2_dial_img_0_424_0);
	LV_IMG_DECLARE(face_756_2_dial_img_1_13004_0);
	LV_IMG_DECLARE(face_756_2_dial_img_1_13004_1);
	LV_IMG_DECLARE(face_756_2_dial_img_2_15014_0);
	LV_IMG_DECLARE(face_756_2_dial_img_2_15014_1);
	LV_IMG_DECLARE(face_756_2_dial_img_3_18734_0);
	LV_IMG_DECLARE(face_756_2_dial_img_3_18734_1);
	LV_IMG_DECLARE(face_756_2_dial_img_3_18734_2);
	LV_IMG_DECLARE(face_756_2_dial_img_3_18734_3);
	LV_IMG_DECLARE(face_756_2_dial_img_3_18734_4);
	LV_IMG_DECLARE(face_756_2_dial_img_3_18734_5);
	LV_IMG_DECLARE(face_756_2_dial_img_4_22016_0);
	LV_IMG_DECLARE(face_756_2_dial_img_5_22382_0);
	LV_IMG_DECLARE(face_756_2_dial_img_6_25488_0);
	LV_IMG_DECLARE(face_756_2_dial_img_6_25488_1);
	LV_IMG_DECLARE(face_756_2_dial_img_6_25488_2);
	LV_IMG_DECLARE(face_756_2_dial_img_6_25488_3);
	LV_IMG_DECLARE(face_756_2_dial_img_6_25488_4);
	LV_IMG_DECLARE(face_756_2_dial_img_6_25488_5);
	LV_IMG_DECLARE(face_756_2_dial_img_6_25488_6);
	LV_IMG_DECLARE(face_756_2_dial_img_6_25488_7);
	LV_IMG_DECLARE(face_756_2_dial_img_6_25488_8);
	LV_IMG_DECLARE(face_756_2_dial_img_6_25488_9);
	LV_IMG_DECLARE(face_756_2_dial_img_8_81874_0);
	LV_IMG_DECLARE(face_756_2_dial_img_8_81874_1);
	LV_IMG_DECLARE(face_756_2_dial_img_8_81874_2);
	LV_IMG_DECLARE(face_756_2_dial_img_8_81874_3);
	LV_IMG_DECLARE(face_756_2_dial_img_8_81874_4);
	LV_IMG_DECLARE(face_756_2_dial_img_8_81874_5);
	LV_IMG_DECLARE(face_756_2_dial_img_8_81874_6);
	LV_IMG_DECLARE(face_756_2_dial_img_8_81874_7);
	LV_IMG_DECLARE(face_756_2_dial_img_8_81874_8);
	LV_IMG_DECLARE(face_756_2_dial_img_8_81874_9);
	LV_IMG_DECLARE(face_756_2_dial_img_10_22752_0);
	LV_IMG_DECLARE(face_756_2_dial_img_10_22752_1);
	LV_IMG_DECLARE(face_756_2_dial_img_10_22752_2);
	LV_IMG_DECLARE(face_756_2_dial_img_10_22752_3);
	LV_IMG_DECLARE(face_756_2_dial_img_10_22752_4);
	LV_IMG_DECLARE(face_756_2_dial_img_10_22752_5);
	LV_IMG_DECLARE(face_756_2_dial_img_10_22752_6);
	LV_IMG_DECLARE(face_756_2_dial_img_10_22752_7);
	LV_IMG_DECLARE(face_756_2_dial_img_10_22752_8);
	LV_IMG_DECLARE(face_756_2_dial_img_10_22752_9);
	LV_IMG_DECLARE(face_756_2_dial_img_17_17160_0);
	LV_IMG_DECLARE(face_756_2_dial_img_17_17160_1);
	LV_IMG_DECLARE(face_756_2_dial_img_17_17160_2);
	LV_IMG_DECLARE(face_756_2_dial_img_17_17160_3);
	LV_IMG_DECLARE(face_756_2_dial_img_17_17160_4);
	LV_IMG_DECLARE(face_756_2_dial_img_17_17160_5);
	LV_IMG_DECLARE(face_756_2_dial_img_17_17160_6);
	LV_IMG_DECLARE(face_756_2_dial_img_17_17160_7);
	LV_IMG_DECLARE(face_756_2_dial_img_17_17160_8);
	LV_IMG_DECLARE(face_756_2_dial_img_17_17160_9);
	LV_IMG_DECLARE(face_756_2_dial_img_19_101998_0);
	LV_IMG_DECLARE(face_756_2_dial_img_19_101998_1);
	LV_IMG_DECLARE(face_756_2_dial_img_19_101998_2);
	LV_IMG_DECLARE(face_756_2_dial_img_19_101998_3);
	LV_IMG_DECLARE(face_756_2_dial_img_19_101998_4);
	LV_IMG_DECLARE(face_756_2_dial_img_19_101998_5);
	LV_IMG_DECLARE(face_756_2_dial_img_19_101998_6);
	LV_IMG_DECLARE(face_756_2_dial_img_20_105728_0);
	LV_IMG_DECLARE(face_756_2_dial_img_20_105728_1);
	LV_IMG_DECLARE(face_756_2_dial_img_20_105728_2);
	LV_IMG_DECLARE(face_756_2_dial_img_20_105728_3);
	LV_IMG_DECLARE(face_756_2_dial_img_20_105728_4);
	LV_IMG_DECLARE(face_756_2_dial_img_20_105728_5);
	LV_IMG_DECLARE(face_756_2_dial_img_20_105728_6);
	LV_IMG_DECLARE(face_756_2_dial_img_preview_0);
	LV_IMG_DECLARE(face_756_2_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_756_2(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **));
    void update_time_756_2(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_756_2(int temp, int icon);
    void update_status_756_2(int battery, bool connection);
    void update_activity_756_2(int steps, int distance, int kcal);
    void update_health_756_2(int bpm, int oxygen);
    void update_all_756_2(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_756_2(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
