
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 79_2_466

#include "79_2_466.h"

#ifdef ENABLE_FACE_79_2_466

lv_obj_t *face_79_2_466;
lv_obj_t *face_79_2_466_0_404;
lv_obj_t *face_79_2_466_1_218068;
lv_obj_t *face_79_2_466_2_218068;
lv_obj_t *face_79_2_466_3_456176;
lv_obj_t *face_79_2_466_4_456176;
lv_obj_t *face_79_2_466_5_512782;
lv_obj_t *face_79_2_466_6_512782;
lv_obj_t *face_79_2_466_7_512782;
lv_obj_t *face_79_2_466_8_512782;
lv_obj_t *face_79_2_466_9_516066;
lv_obj_t *face_79_2_466_10_512782;
lv_obj_t *face_79_2_466_11_512782;
lv_obj_t *face_79_2_466_12_512782;
lv_obj_t *face_79_2_466_13_512782;
lv_obj_t *face_79_2_466_14_512782;
lv_obj_t *face_79_2_466_15_512782;
lv_obj_t *face_79_2_466_16_512782;
lv_obj_t *face_79_2_466_17_512782;
lv_obj_t *face_79_2_466_19_536660;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif

const lv_img_dsc_t *face_79_2_466_dial_img_1_218068_group[] = {
	&face_79_2_466_dial_img_1_218068_0,
	&face_79_2_466_dial_img_1_218068_1,
	&face_79_2_466_dial_img_1_218068_2,
	&face_79_2_466_dial_img_1_218068_3,
	&face_79_2_466_dial_img_1_218068_4,
	&face_79_2_466_dial_img_1_218068_5,
	&face_79_2_466_dial_img_1_218068_6,
	&face_79_2_466_dial_img_1_218068_7,
	&face_79_2_466_dial_img_1_218068_8,
	&face_79_2_466_dial_img_1_218068_9,
};
const lv_img_dsc_t *face_79_2_466_dial_img_3_456176_group[] = {
	&face_79_2_466_dial_img_3_456176_0,
	&face_79_2_466_dial_img_3_456176_1,
	&face_79_2_466_dial_img_3_456176_2,
	&face_79_2_466_dial_img_3_456176_3,
	&face_79_2_466_dial_img_3_456176_4,
	&face_79_2_466_dial_img_3_456176_5,
	&face_79_2_466_dial_img_3_456176_6,
	&face_79_2_466_dial_img_3_456176_7,
	&face_79_2_466_dial_img_3_456176_8,
	&face_79_2_466_dial_img_3_456176_9,
};
const lv_img_dsc_t *face_79_2_466_dial_img_5_512782_group[] = {
	&face_79_2_466_dial_img_5_512782_0,
	&face_79_2_466_dial_img_5_512782_1,
	&face_79_2_466_dial_img_5_512782_2,
	&face_79_2_466_dial_img_5_512782_3,
	&face_79_2_466_dial_img_5_512782_4,
	&face_79_2_466_dial_img_5_512782_5,
	&face_79_2_466_dial_img_5_512782_6,
	&face_79_2_466_dial_img_5_512782_7,
	&face_79_2_466_dial_img_5_512782_8,
	&face_79_2_466_dial_img_5_512782_9,
};
const lv_img_dsc_t *face_79_2_466_dial_img_18_516445_group[] = {
	&face_79_2_466_dial_img_18_516445_0,
	&face_79_2_466_dial_img_18_516445_1,
	&face_79_2_466_dial_img_18_516445_2,
	&face_79_2_466_dial_img_18_516445_3,
	&face_79_2_466_dial_img_18_516445_4,
	&face_79_2_466_dial_img_18_516445_5,
	&face_79_2_466_dial_img_18_516445_6,
};
const lv_img_dsc_t *face_79_2_466_dial_img_19_536660_group[] = {
	&face_79_2_466_dial_img_19_536660_0,
	&face_79_2_466_dial_img_19_536660_1,
	&face_79_2_466_dial_img_19_536660_2,
	&face_79_2_466_dial_img_19_536660_3,
	&face_79_2_466_dial_img_19_536660_4,
	&face_79_2_466_dial_img_19_536660_5,
	&face_79_2_466_dial_img_19_536660_6,
};




#endif

void init_face_79_2_466(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **)){
#ifdef ENABLE_FACE_79_2_466
    face_79_2_466 = lv_obj_create(NULL);
    lv_obj_clear_flag(face_79_2_466, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_79_2_466, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_79_2_466, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_79_2_466, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_79_2_466, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_79_2_466, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_79_2_466, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_79_2_466, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_79_2_466, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_79_2_466_0_404 = lv_img_create(face_79_2_466);
    lv_img_set_src(face_79_2_466_0_404, &face_79_2_466_dial_img_0_404_0);
    lv_obj_set_width(face_79_2_466_0_404, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_466_0_404, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_466_0_404, 0);
    lv_obj_set_y(face_79_2_466_0_404, 0);
    lv_obj_add_flag(face_79_2_466_0_404, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_466_0_404, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_466_1_218068 = lv_img_create(face_79_2_466);
    lv_img_set_src(face_79_2_466_1_218068, &face_79_2_466_dial_img_1_218068_0);
    lv_obj_set_width(face_79_2_466_1_218068, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_466_1_218068, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_466_1_218068, 159);
    lv_obj_set_y(face_79_2_466_1_218068, 133);
    lv_obj_add_flag(face_79_2_466_1_218068, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_466_1_218068, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_466_2_218068 = lv_img_create(face_79_2_466);
    lv_img_set_src(face_79_2_466_2_218068, &face_79_2_466_dial_img_1_218068_0);
    lv_obj_set_width(face_79_2_466_2_218068, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_466_2_218068, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_466_2_218068, 27);
    lv_obj_set_y(face_79_2_466_2_218068, 133);
    lv_obj_add_flag(face_79_2_466_2_218068, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_466_2_218068, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_466_3_456176 = lv_img_create(face_79_2_466);
    lv_img_set_src(face_79_2_466_3_456176, &face_79_2_466_dial_img_3_456176_0);
    lv_obj_set_width(face_79_2_466_3_456176, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_466_3_456176, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_466_3_456176, 365);
    lv_obj_set_y(face_79_2_466_3_456176, 180);
    lv_obj_add_flag(face_79_2_466_3_456176, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_466_3_456176, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_466_4_456176 = lv_img_create(face_79_2_466);
    lv_img_set_src(face_79_2_466_4_456176, &face_79_2_466_dial_img_3_456176_0);
    lv_obj_set_width(face_79_2_466_4_456176, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_466_4_456176, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_466_4_456176, 299);
    lv_obj_set_y(face_79_2_466_4_456176, 180);
    lv_obj_add_flag(face_79_2_466_4_456176, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_466_4_456176, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_466_5_512782 = lv_img_create(face_79_2_466);
    lv_img_set_src(face_79_2_466_5_512782, &face_79_2_466_dial_img_5_512782_0);
    lv_obj_set_width(face_79_2_466_5_512782, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_466_5_512782, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_466_5_512782, 209);
    lv_obj_set_y(face_79_2_466_5_512782, 409);
    lv_obj_add_flag(face_79_2_466_5_512782, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_466_5_512782, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_466_6_512782 = lv_img_create(face_79_2_466);
    lv_img_set_src(face_79_2_466_6_512782, &face_79_2_466_dial_img_5_512782_0);
    lv_obj_set_width(face_79_2_466_6_512782, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_466_6_512782, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_466_6_512782, 192);
    lv_obj_set_y(face_79_2_466_6_512782, 409);
    lv_obj_add_flag(face_79_2_466_6_512782, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_466_6_512782, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_466_7_512782 = lv_img_create(face_79_2_466);
    lv_img_set_src(face_79_2_466_7_512782, &face_79_2_466_dial_img_5_512782_0);
    lv_obj_set_width(face_79_2_466_7_512782, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_466_7_512782, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_466_7_512782, 258);
    lv_obj_set_y(face_79_2_466_7_512782, 409);
    lv_obj_add_flag(face_79_2_466_7_512782, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_466_7_512782, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_466_8_512782 = lv_img_create(face_79_2_466);
    lv_img_set_src(face_79_2_466_8_512782, &face_79_2_466_dial_img_5_512782_0);
    lv_obj_set_width(face_79_2_466_8_512782, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_466_8_512782, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_466_8_512782, 240);
    lv_obj_set_y(face_79_2_466_8_512782, 409);
    lv_obj_add_flag(face_79_2_466_8_512782, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_466_8_512782, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_466_9_516066 = lv_img_create(face_79_2_466);
    lv_img_set_src(face_79_2_466_9_516066, &face_79_2_466_dial_img_9_516066_0);
    lv_obj_set_width(face_79_2_466_9_516066, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_466_9_516066, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_466_9_516066, 225);
    lv_obj_set_y(face_79_2_466_9_516066, 411);
    lv_obj_add_flag(face_79_2_466_9_516066, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_466_9_516066, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_466_10_512782 = lv_img_create(face_79_2_466);
    lv_img_set_src(face_79_2_466_10_512782, &face_79_2_466_dial_img_5_512782_0);
    lv_obj_set_width(face_79_2_466_10_512782, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_466_10_512782, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_466_10_512782, 130);
    lv_obj_set_y(face_79_2_466_10_512782, 366);
    lv_obj_add_flag(face_79_2_466_10_512782, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_466_10_512782, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_466_11_512782 = lv_img_create(face_79_2_466);
    lv_img_set_src(face_79_2_466_11_512782, &face_79_2_466_dial_img_5_512782_0);
    lv_obj_set_width(face_79_2_466_11_512782, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_466_11_512782, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_466_11_512782, 112);
    lv_obj_set_y(face_79_2_466_11_512782, 366);
    lv_obj_add_flag(face_79_2_466_11_512782, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_466_11_512782, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_466_12_512782 = lv_img_create(face_79_2_466);
    lv_img_set_src(face_79_2_466_12_512782, &face_79_2_466_dial_img_5_512782_0);
    lv_obj_set_width(face_79_2_466_12_512782, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_466_12_512782, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_466_12_512782, 95);
    lv_obj_set_y(face_79_2_466_12_512782, 366);
    lv_obj_add_flag(face_79_2_466_12_512782, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_466_12_512782, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_466_13_512782 = lv_img_create(face_79_2_466);
    lv_img_set_src(face_79_2_466_13_512782, &face_79_2_466_dial_img_5_512782_0);
    lv_obj_set_width(face_79_2_466_13_512782, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_466_13_512782, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_466_13_512782, 378);
    lv_obj_set_y(face_79_2_466_13_512782, 366);
    lv_obj_add_flag(face_79_2_466_13_512782, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_466_13_512782, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_466_14_512782 = lv_img_create(face_79_2_466);
    lv_img_set_src(face_79_2_466_14_512782, &face_79_2_466_dial_img_5_512782_0);
    lv_obj_set_width(face_79_2_466_14_512782, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_466_14_512782, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_466_14_512782, 361);
    lv_obj_set_y(face_79_2_466_14_512782, 366);
    lv_obj_add_flag(face_79_2_466_14_512782, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_466_14_512782, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_466_15_512782 = lv_img_create(face_79_2_466);
    lv_img_set_src(face_79_2_466_15_512782, &face_79_2_466_dial_img_5_512782_0);
    lv_obj_set_width(face_79_2_466_15_512782, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_466_15_512782, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_466_15_512782, 343);
    lv_obj_set_y(face_79_2_466_15_512782, 366);
    lv_obj_add_flag(face_79_2_466_15_512782, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_466_15_512782, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_466_16_512782 = lv_img_create(face_79_2_466);
    lv_img_set_src(face_79_2_466_16_512782, &face_79_2_466_dial_img_5_512782_0);
    lv_obj_set_width(face_79_2_466_16_512782, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_466_16_512782, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_466_16_512782, 326);
    lv_obj_set_y(face_79_2_466_16_512782, 366);
    lv_obj_add_flag(face_79_2_466_16_512782, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_466_16_512782, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_466_17_512782 = lv_img_create(face_79_2_466);
    lv_img_set_src(face_79_2_466_17_512782, &face_79_2_466_dial_img_5_512782_0);
    lv_obj_set_width(face_79_2_466_17_512782, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_466_17_512782, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_466_17_512782, 308);
    lv_obj_set_y(face_79_2_466_17_512782, 366);
    lv_obj_add_flag(face_79_2_466_17_512782, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_466_17_512782, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_466_19_536660 = lv_img_create(face_79_2_466);
    lv_img_set_src(face_79_2_466_19_536660, &face_79_2_466_dial_img_19_536660_0);
    lv_obj_set_width(face_79_2_466_19_536660, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_466_19_536660, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_466_19_536660, 143);
    lv_obj_set_y(face_79_2_466_19_536660, 44);
    lv_obj_add_flag(face_79_2_466_19_536660, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_466_19_536660, LV_OBJ_FLAG_SCROLLABLE );


    callback("Blue", &face_79_2_466_dial_img_preview_0, &face_79_2_466, NULL);

#endif
}

void update_time_79_2_466(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_79_2_466
    if (!face_79_2_466)
    {
        return;
    }
	lv_img_set_src(face_79_2_466_1_218068, face_79_2_466_dial_img_1_218068_group[(hour / 1) % 10]);
	lv_img_set_src(face_79_2_466_2_218068, face_79_2_466_dial_img_1_218068_group[(hour / 10) % 10]);
	lv_img_set_src(face_79_2_466_3_456176, face_79_2_466_dial_img_3_456176_group[(minute / 1) % 10]);
	lv_img_set_src(face_79_2_466_4_456176, face_79_2_466_dial_img_3_456176_group[(minute / 10) % 10]);
	lv_img_set_src(face_79_2_466_5_512782, face_79_2_466_dial_img_5_512782_group[(month / 1) % 10]);
	lv_img_set_src(face_79_2_466_6_512782, face_79_2_466_dial_img_5_512782_group[(month / 10) % 10]);
	lv_img_set_src(face_79_2_466_7_512782, face_79_2_466_dial_img_5_512782_group[(day / 1) % 10]);
	lv_img_set_src(face_79_2_466_8_512782, face_79_2_466_dial_img_5_512782_group[(day / 10) % 10]);
	lv_img_set_src(face_79_2_466_19_536660, face_79_2_466_dial_img_19_536660_group[((weekday + 6) / 1) % 7]);

#endif
}

void update_weather_79_2_466(int temp, int icon)
{
#ifdef ENABLE_FACE_79_2_466
    if (!face_79_2_466)
    {
        return;
    }

#endif
}

void update_status_79_2_466(int battery, bool connection){
#ifdef ENABLE_FACE_79_2_466
    if (!face_79_2_466)
    {
        return;
    }
	lv_img_set_src(face_79_2_466_10_512782, face_79_2_466_dial_img_5_512782_group[(battery / 1) % 10]);
	lv_img_set_src(face_79_2_466_11_512782, face_79_2_466_dial_img_5_512782_group[(battery / 10) % 10]);
	lv_img_set_src(face_79_2_466_12_512782, face_79_2_466_dial_img_5_512782_group[(battery / 100) % 10]);
	if (battery < 100)
	{
		lv_obj_add_flag(face_79_2_466_12_512782, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_79_2_466_12_512782, LV_OBJ_FLAG_HIDDEN);
	}

#endif
}

void update_activity_79_2_466(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_79_2_466
    if (!face_79_2_466)
    {
        return;
    }
	lv_img_set_src(face_79_2_466_13_512782, face_79_2_466_dial_img_5_512782_group[(steps / 1) % 10]);
	lv_img_set_src(face_79_2_466_14_512782, face_79_2_466_dial_img_5_512782_group[(steps / 10) % 10]);
	lv_img_set_src(face_79_2_466_15_512782, face_79_2_466_dial_img_5_512782_group[(steps / 100) % 10]);
	lv_img_set_src(face_79_2_466_16_512782, face_79_2_466_dial_img_5_512782_group[(steps / 1000) % 10]);
	lv_img_set_src(face_79_2_466_17_512782, face_79_2_466_dial_img_5_512782_group[(steps / 10000) % 10]);

#endif
}

void update_health_79_2_466(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_79_2_466
    if (!face_79_2_466)
    {
        return;
    }

#endif
}

void update_all_79_2_466(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_79_2_466
    update_time_79_2_466(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_79_2_466(temp, icon);
    update_status_79_2_466(battery, connection);
    update_activity_79_2_466(steps, distance, kcal);
    update_health_79_2_466(bpm, oxygen);
#endif
}

void update_check_79_2_466(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_79_2_466
    if (root != face_79_2_466)
    {
        return;
    }
    update_time_79_2_466(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_79_2_466(temp, icon);
    update_status_79_2_466(battery, connection);
    update_activity_79_2_466(steps, distance, kcal);
    update_health_79_2_466(bpm, oxygen);
#endif
}


