
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: PIXEL_RESIZED

#ifndef _FACE_PIXEL_RESIZED_H
#define _FACE_PIXEL_RESIZED_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"
#include "app_hal.h"

//#define ENABLE_FACE_PIXEL_RESIZED // (Pixel) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_PIXEL_RESIZED
    extern lv_obj_t *face_pixel_resized;
	extern lv_obj_t *face_pixel_resized_0_1004;
	extern lv_obj_t *face_pixel_resized_1_59114;
	extern lv_obj_t *face_pixel_resized_2_59114;
	extern lv_obj_t *face_pixel_resized_3_59114;
	extern lv_obj_t *face_pixel_resized_4_59114;
	extern lv_obj_t *face_pixel_resized_5_59114;
	extern lv_obj_t *face_pixel_resized_6_59114;
	extern lv_obj_t *face_pixel_resized_7_59114;
	extern lv_obj_t *face_pixel_resized_8_59114;
	extern lv_obj_t *face_pixel_resized_9_59114;
	extern lv_obj_t *face_pixel_resized_12_60913;
	extern lv_obj_t *face_pixel_resized_13_59114;
	extern lv_obj_t *face_pixel_resized_14_59114;
	extern lv_obj_t *face_pixel_resized_15_59114;
	extern lv_obj_t *face_pixel_resized_16_59114;
	extern lv_obj_t *face_pixel_resized_17_59114;
	extern lv_obj_t *face_pixel_resized_18_59114;
	extern lv_obj_t *face_pixel_resized_19_61460;
	extern lv_obj_t *face_pixel_resized_20_61728;
	extern lv_obj_t *face_pixel_resized_22_72744;
	extern lv_obj_t *face_pixel_resized_23_59114;
	extern lv_obj_t *face_pixel_resized_24_59114;
	extern lv_obj_t *face_pixel_resized_27_87610;
	extern lv_obj_t *face_pixel_resized_28_97966;
	extern lv_obj_t *face_pixel_resized_29_97966;
	extern lv_obj_t *face_pixel_resized_30_97966;
	extern lv_obj_t *face_pixel_resized_31_97966;
	extern lv_obj_t *face_pixel_resized_34_59114;
	extern lv_obj_t *face_pixel_resized_35_59114;
	extern lv_obj_t *face_pixel_resized_36_130812;
	extern lv_obj_t *face_pixel_resized_37_65535;
	extern lv_obj_t *face_pixel_resized_41_130994;


	LV_IMG_DECLARE(face_pixel_resized_dial_img_0_1004_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_1_59114_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_1_59114_1);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_1_59114_2);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_1_59114_3);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_1_59114_4);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_1_59114_5);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_1_59114_6);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_1_59114_7);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_1_59114_8);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_1_59114_9);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_11_60084_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_12_60913_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_19_61460_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_20_61728_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_20_61728_1);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_20_61728_2);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_20_61728_3);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_20_61728_4);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_20_61728_5);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_20_61728_6);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_21_65400_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_21_65400_1);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_21_65400_2);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_21_65400_3);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_21_65400_4);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_21_65400_5);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_21_65400_6);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_22_72744_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_22_72744_1);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_22_72744_2);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_22_72744_3);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_22_72744_4);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_22_72744_5);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_22_72744_6);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_26_78812_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_26_78812_1);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_26_78812_2);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_26_78812_3);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_26_78812_4);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_26_78812_5);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_26_78812_6);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_26_78812_7);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_26_78812_8);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_26_78812_9);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_26_78812_10);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_26_78812_11);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_27_87610_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_27_87610_1);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_27_87610_2);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_27_87610_3);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_27_87610_4);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_27_87610_5);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_27_87610_6);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_27_87610_7);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_27_87610_8);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_27_87610_9);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_27_87610_10);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_27_87610_11);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_28_97966_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_28_97966_1);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_28_97966_2);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_28_97966_3);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_28_97966_4);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_28_97966_5);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_28_97966_6);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_28_97966_7);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_28_97966_8);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_28_97966_9);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_32_65535_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_36_130812_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_41_130994_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_42_131564_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_43_132416_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_44_133314_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_45_134124_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_46_134880_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_47_135702_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_48_136588_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_49_137284_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_preview_0);
	LV_IMG_DECLARE(face_pixel_resized_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_pixel_resized(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **));
    void update_time_pixel_resized(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_pixel_resized(int temp, int icon);
    void update_status_pixel_resized(int battery, bool connection);
    void update_activity_pixel_resized(int steps, int distance, int kcal);
    void update_health_pixel_resized(int bpm, int oxygen);
    void update_all_pixel_resized(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_pixel_resized(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
