
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: SMART_RESIZED

#ifndef _FACE_SMART_RESIZED_H
#define _FACE_SMART_RESIZED_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"
#include "app_hal.h"

//#define ENABLE_FACE_SMART_RESIZED // (Smart) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_SMART_RESIZED
    extern lv_obj_t *face_smart_resized;
	extern lv_obj_t *face_smart_resized_0_784;
	extern lv_obj_t *face_smart_resized_2_58894;
	extern lv_obj_t *face_smart_resized_11_62309;
	extern lv_obj_t *face_smart_resized_12_62309;
	extern lv_obj_t *face_smart_resized_13_62309;
	extern lv_obj_t *face_smart_resized_14_62309;
	extern lv_obj_t *face_smart_resized_15_63383;
	extern lv_obj_t *face_smart_resized_16_62309;
	extern lv_obj_t *face_smart_resized_17_62309;
	extern lv_obj_t *face_smart_resized_18_62309;
	extern lv_obj_t *face_smart_resized_19_63501;
	extern lv_obj_t *face_smart_resized_20_67327;
	extern lv_obj_t *face_smart_resized_21_67469;
	extern lv_obj_t *face_smart_resized_22_67469;
	extern lv_obj_t *face_smart_resized_23_67469;
	extern lv_obj_t *face_smart_resized_27_67469;
	extern lv_obj_t *face_smart_resized_28_67469;
	extern lv_obj_t *face_smart_resized_29_67469;
	extern lv_obj_t *face_smart_resized_30_67469;
	extern lv_obj_t *face_smart_resized_31_67469;
	extern lv_obj_t *face_smart_resized_32_68383;
	extern lv_obj_t *face_smart_resized_33_68383;
	extern lv_obj_t *face_smart_resized_34_68383;
	extern lv_obj_t *face_smart_resized_35_68383;
	extern lv_obj_t *face_smart_resized_38_93007;


	LV_IMG_DECLARE(face_smart_resized_dial_img_0_784_0);
	LV_IMG_DECLARE(face_smart_resized_dial_img_2_58894_0);
	LV_IMG_DECLARE(face_smart_resized_dial_img_3_59321_0);
	LV_IMG_DECLARE(face_smart_resized_dial_img_4_59687_0);
	LV_IMG_DECLARE(face_smart_resized_dial_img_5_60033_0);
	LV_IMG_DECLARE(face_smart_resized_dial_img_6_60497_0);
	LV_IMG_DECLARE(face_smart_resized_dial_img_7_60803_0);
	LV_IMG_DECLARE(face_smart_resized_dial_img_8_61183_0);
	LV_IMG_DECLARE(face_smart_resized_dial_img_9_61547_0);
	LV_IMG_DECLARE(face_smart_resized_dial_img_10_61923_0);
	LV_IMG_DECLARE(face_smart_resized_dial_img_11_62309_0);
	LV_IMG_DECLARE(face_smart_resized_dial_img_11_62309_1);
	LV_IMG_DECLARE(face_smart_resized_dial_img_11_62309_2);
	LV_IMG_DECLARE(face_smart_resized_dial_img_11_62309_3);
	LV_IMG_DECLARE(face_smart_resized_dial_img_11_62309_4);
	LV_IMG_DECLARE(face_smart_resized_dial_img_11_62309_5);
	LV_IMG_DECLARE(face_smart_resized_dial_img_11_62309_6);
	LV_IMG_DECLARE(face_smart_resized_dial_img_11_62309_7);
	LV_IMG_DECLARE(face_smart_resized_dial_img_11_62309_8);
	LV_IMG_DECLARE(face_smart_resized_dial_img_11_62309_9);
	LV_IMG_DECLARE(face_smart_resized_dial_img_15_63383_0);
	LV_IMG_DECLARE(face_smart_resized_dial_img_19_63501_0);
	LV_IMG_DECLARE(face_smart_resized_dial_img_19_63501_1);
	LV_IMG_DECLARE(face_smart_resized_dial_img_19_63501_2);
	LV_IMG_DECLARE(face_smart_resized_dial_img_19_63501_3);
	LV_IMG_DECLARE(face_smart_resized_dial_img_19_63501_4);
	LV_IMG_DECLARE(face_smart_resized_dial_img_19_63501_5);
	LV_IMG_DECLARE(face_smart_resized_dial_img_19_63501_6);
	LV_IMG_DECLARE(face_smart_resized_dial_img_19_63501_7);
	LV_IMG_DECLARE(face_smart_resized_dial_img_19_63501_8);
	LV_IMG_DECLARE(face_smart_resized_dial_img_19_63501_9);
	LV_IMG_DECLARE(face_smart_resized_dial_img_19_63501_10);
	LV_IMG_DECLARE(face_smart_resized_dial_img_20_67327_0);
	LV_IMG_DECLARE(face_smart_resized_dial_img_21_67469_0);
	LV_IMG_DECLARE(face_smart_resized_dial_img_21_67469_1);
	LV_IMG_DECLARE(face_smart_resized_dial_img_21_67469_2);
	LV_IMG_DECLARE(face_smart_resized_dial_img_21_67469_3);
	LV_IMG_DECLARE(face_smart_resized_dial_img_21_67469_4);
	LV_IMG_DECLARE(face_smart_resized_dial_img_21_67469_5);
	LV_IMG_DECLARE(face_smart_resized_dial_img_21_67469_6);
	LV_IMG_DECLARE(face_smart_resized_dial_img_21_67469_7);
	LV_IMG_DECLARE(face_smart_resized_dial_img_21_67469_8);
	LV_IMG_DECLARE(face_smart_resized_dial_img_21_67469_9);
	LV_IMG_DECLARE(face_smart_resized_dial_img_32_68383_0);
	LV_IMG_DECLARE(face_smart_resized_dial_img_32_68383_1);
	LV_IMG_DECLARE(face_smart_resized_dial_img_32_68383_2);
	LV_IMG_DECLARE(face_smart_resized_dial_img_32_68383_3);
	LV_IMG_DECLARE(face_smart_resized_dial_img_32_68383_4);
	LV_IMG_DECLARE(face_smart_resized_dial_img_32_68383_5);
	LV_IMG_DECLARE(face_smart_resized_dial_img_32_68383_6);
	LV_IMG_DECLARE(face_smart_resized_dial_img_32_68383_7);
	LV_IMG_DECLARE(face_smart_resized_dial_img_32_68383_8);
	LV_IMG_DECLARE(face_smart_resized_dial_img_32_68383_9);
	LV_IMG_DECLARE(face_smart_resized_dial_img_37_88367_0);
	LV_IMG_DECLARE(face_smart_resized_dial_img_37_88367_1);
	LV_IMG_DECLARE(face_smart_resized_dial_img_37_88367_2);
	LV_IMG_DECLARE(face_smart_resized_dial_img_37_88367_3);
	LV_IMG_DECLARE(face_smart_resized_dial_img_37_88367_4);
	LV_IMG_DECLARE(face_smart_resized_dial_img_37_88367_5);
	LV_IMG_DECLARE(face_smart_resized_dial_img_37_88367_6);
	LV_IMG_DECLARE(face_smart_resized_dial_img_38_93007_0);
	LV_IMG_DECLARE(face_smart_resized_dial_img_38_93007_1);
	LV_IMG_DECLARE(face_smart_resized_dial_img_38_93007_2);
	LV_IMG_DECLARE(face_smart_resized_dial_img_38_93007_3);
	LV_IMG_DECLARE(face_smart_resized_dial_img_38_93007_4);
	LV_IMG_DECLARE(face_smart_resized_dial_img_38_93007_5);
	LV_IMG_DECLARE(face_smart_resized_dial_img_38_93007_6);
	LV_IMG_DECLARE(face_smart_resized_dial_img_preview_0);
	LV_IMG_DECLARE(face_smart_resized_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_smart_resized(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **));
    void update_time_smart_resized(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_smart_resized(int temp, int icon);
    void update_status_smart_resized(int battery, bool connection);
    void update_activity_smart_resized(int steps, int distance, int kcal);
    void update_health_smart_resized(int bpm, int oxygen);
    void update_all_smart_resized(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_smart_resized(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
