
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: NIGHT_360

#include "night_360.h"

#ifdef ENABLE_FACE_NIGHT_360

lv_obj_t *face_night_360;
lv_obj_t *face_night_360_0_634;
lv_obj_t *face_night_360_2_130744;
lv_obj_t *face_night_360_3_130744;
lv_obj_t *face_night_360_4_130744;
lv_obj_t *face_night_360_5_130744;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif

const lv_img_dsc_t *face_night_360_dial_img_2_130744_group[] = {
	&face_night_360_dial_img_2_130744_0,
	&face_night_360_dial_img_2_130744_1,
	&face_night_360_dial_img_2_130744_2,
	&face_night_360_dial_img_2_130744_3,
	&face_night_360_dial_img_2_130744_4,
	&face_night_360_dial_img_2_130744_5,
	&face_night_360_dial_img_2_130744_6,
	&face_night_360_dial_img_2_130744_7,
	&face_night_360_dial_img_2_130744_8,
	&face_night_360_dial_img_2_130744_9,
};




#endif

void init_face_night_360(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **)){
#ifdef ENABLE_FACE_NIGHT_360
    face_night_360 = lv_obj_create(NULL);
    lv_obj_clear_flag(face_night_360, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_night_360, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_night_360, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_night_360, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_night_360, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_night_360, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_night_360, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_night_360, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_night_360, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_night_360_0_634 = lv_img_create(face_night_360);
    lv_img_set_src(face_night_360_0_634, &face_night_360_dial_img_0_634_0);
    lv_obj_set_width(face_night_360_0_634, LV_SIZE_CONTENT);
    lv_obj_set_height(face_night_360_0_634, LV_SIZE_CONTENT);
    lv_obj_set_x(face_night_360_0_634, 0);
    lv_obj_set_y(face_night_360_0_634, 0);
    lv_obj_add_flag(face_night_360_0_634, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_night_360_0_634, LV_OBJ_FLAG_SCROLLABLE );

    face_night_360_2_130744 = lv_img_create(face_night_360);
    lv_img_set_src(face_night_360_2_130744, &face_night_360_dial_img_2_130744_0);
    lv_obj_set_width(face_night_360_2_130744, LV_SIZE_CONTENT);
    lv_obj_set_height(face_night_360_2_130744, LV_SIZE_CONTENT);
    lv_obj_set_x(face_night_360_2_130744, 150);
    lv_obj_set_y(face_night_360_2_130744, 20);
    lv_obj_add_flag(face_night_360_2_130744, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_night_360_2_130744, LV_OBJ_FLAG_SCROLLABLE );

    face_night_360_3_130744 = lv_img_create(face_night_360);
    lv_img_set_src(face_night_360_3_130744, &face_night_360_dial_img_2_130744_0);
    lv_obj_set_width(face_night_360_3_130744, LV_SIZE_CONTENT);
    lv_obj_set_height(face_night_360_3_130744, LV_SIZE_CONTENT);
    lv_obj_set_x(face_night_360_3_130744, 70);
    lv_obj_set_y(face_night_360_3_130744, 20);
    lv_obj_add_flag(face_night_360_3_130744, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_night_360_3_130744, LV_OBJ_FLAG_SCROLLABLE );

    face_night_360_4_130744 = lv_img_create(face_night_360);
    lv_img_set_src(face_night_360_4_130744, &face_night_360_dial_img_2_130744_0);
    lv_obj_set_width(face_night_360_4_130744, LV_SIZE_CONTENT);
    lv_obj_set_height(face_night_360_4_130744, LV_SIZE_CONTENT);
    lv_obj_set_x(face_night_360_4_130744, 150);
    lv_obj_set_y(face_night_360_4_130744, 145);
    lv_obj_add_flag(face_night_360_4_130744, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_night_360_4_130744, LV_OBJ_FLAG_SCROLLABLE );

    face_night_360_5_130744 = lv_img_create(face_night_360);
    lv_img_set_src(face_night_360_5_130744, &face_night_360_dial_img_2_130744_0);
    lv_obj_set_width(face_night_360_5_130744, LV_SIZE_CONTENT);
    lv_obj_set_height(face_night_360_5_130744, LV_SIZE_CONTENT);
    lv_obj_set_x(face_night_360_5_130744, 70);
    lv_obj_set_y(face_night_360_5_130744, 145);
    lv_obj_add_flag(face_night_360_5_130744, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_night_360_5_130744, LV_OBJ_FLAG_SCROLLABLE );


    callback("Night", &face_night_360_dial_img_preview_0, &face_night_360, NULL);

#endif
}

void update_time_night_360(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_NIGHT_360
    if (!face_night_360)
    {
        return;
    }
	lv_img_set_src(face_night_360_2_130744, face_night_360_dial_img_2_130744_group[(hour / 1) % 10]);
	lv_img_set_src(face_night_360_3_130744, face_night_360_dial_img_2_130744_group[(hour / 10) % 10]);
	lv_img_set_src(face_night_360_4_130744, face_night_360_dial_img_2_130744_group[(minute / 1) % 10]);
	lv_img_set_src(face_night_360_5_130744, face_night_360_dial_img_2_130744_group[(minute / 10) % 10]);

#endif
}

void update_weather_night_360(int temp, int icon)
{
#ifdef ENABLE_FACE_NIGHT_360
    if (!face_night_360)
    {
        return;
    }

#endif
}

void update_status_night_360(int battery, bool connection){
#ifdef ENABLE_FACE_NIGHT_360
    if (!face_night_360)
    {
        return;
    }

#endif
}

void update_activity_night_360(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_NIGHT_360
    if (!face_night_360)
    {
        return;
    }

#endif
}

void update_health_night_360(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_NIGHT_360
    if (!face_night_360)
    {
        return;
    }

#endif
}

void update_all_night_360(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_NIGHT_360
    update_time_night_360(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_night_360(temp, icon);
    update_status_night_360(battery, connection);
    update_activity_night_360(steps, distance, kcal);
    update_health_night_360(bpm, oxygen);
#endif
}

void update_check_night_360(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_NIGHT_360
    if (root != face_night_360)
    {
        return;
    }
    update_time_night_360(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_night_360(temp, icon);
    update_status_night_360(battery, connection);
    update_activity_night_360(steps, distance, kcal);
    update_health_night_360(bpm, oxygen);
#endif
}


