
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: ARCTIC_360

#include "arctic_360.h"

#ifdef ENABLE_FACE_ARCTIC_360

lv_obj_t *face_arctic_360;
lv_obj_t *face_arctic_360_0_724;
lv_obj_t *face_arctic_360_1_130834;
lv_obj_t *face_arctic_360_2_130834;
lv_obj_t *face_arctic_360_3_210070;
lv_obj_t *face_arctic_360_4_210070;
lv_obj_t *face_arctic_360_5_255122;
lv_obj_t *face_arctic_360_6_255122;
lv_obj_t *face_arctic_360_8_263030;
lv_obj_t *face_arctic_360_9_259332;
lv_obj_t *face_arctic_360_10_259332;
lv_obj_t *face_arctic_360_11_259332;
lv_obj_t *face_arctic_360_12_259332;
lv_obj_t *face_arctic_360_13_259332;
lv_obj_t *face_arctic_360_14_259332;
lv_obj_t *face_arctic_360_15_259332;
lv_obj_t *face_arctic_360_16_259332;
lv_obj_t *face_arctic_360_17_259332;
lv_obj_t *face_arctic_360_19_293418;
lv_obj_t *face_arctic_360_30_259332;
lv_obj_t *face_arctic_360_31_259332;
lv_obj_t *face_arctic_360_32_259332;
lv_obj_t *face_arctic_360_34_284972;
lv_obj_t *face_arctic_360_35_65535;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif

const lv_img_dsc_t *face_arctic_360_dial_img_1_130834_group[] = {
	&face_arctic_360_dial_img_1_130834_0,
	&face_arctic_360_dial_img_1_130834_1,
	&face_arctic_360_dial_img_1_130834_2,
	&face_arctic_360_dial_img_1_130834_3,
	&face_arctic_360_dial_img_1_130834_4,
	&face_arctic_360_dial_img_1_130834_5,
	&face_arctic_360_dial_img_1_130834_6,
	&face_arctic_360_dial_img_1_130834_7,
	&face_arctic_360_dial_img_1_130834_8,
	&face_arctic_360_dial_img_1_130834_9,
};
const lv_img_dsc_t *face_arctic_360_dial_img_3_210070_group[] = {
	&face_arctic_360_dial_img_3_210070_0,
	&face_arctic_360_dial_img_3_210070_1,
	&face_arctic_360_dial_img_3_210070_2,
	&face_arctic_360_dial_img_3_210070_3,
	&face_arctic_360_dial_img_3_210070_4,
	&face_arctic_360_dial_img_3_210070_5,
	&face_arctic_360_dial_img_3_210070_6,
	&face_arctic_360_dial_img_3_210070_7,
	&face_arctic_360_dial_img_3_210070_8,
	&face_arctic_360_dial_img_3_210070_9,
};
const lv_img_dsc_t *face_arctic_360_dial_img_5_255122_group[] = {
	&face_arctic_360_dial_img_5_255122_0,
	&face_arctic_360_dial_img_5_255122_1,
	&face_arctic_360_dial_img_5_255122_2,
	&face_arctic_360_dial_img_5_255122_3,
	&face_arctic_360_dial_img_5_255122_4,
	&face_arctic_360_dial_img_5_255122_5,
	&face_arctic_360_dial_img_5_255122_6,
	&face_arctic_360_dial_img_5_255122_7,
	&face_arctic_360_dial_img_5_255122_8,
	&face_arctic_360_dial_img_5_255122_9,
};
const lv_img_dsc_t *face_arctic_360_dial_img_7_274000_group[] = {
	&face_arctic_360_dial_img_7_274000_0,
	&face_arctic_360_dial_img_7_274000_1,
	&face_arctic_360_dial_img_7_274000_2,
	&face_arctic_360_dial_img_7_274000_3,
	&face_arctic_360_dial_img_7_274000_4,
	&face_arctic_360_dial_img_7_274000_5,
	&face_arctic_360_dial_img_7_274000_6,
};
const lv_img_dsc_t *face_arctic_360_dial_img_8_263030_group[] = {
	&face_arctic_360_dial_img_8_263030_0,
	&face_arctic_360_dial_img_8_263030_1,
	&face_arctic_360_dial_img_8_263030_2,
	&face_arctic_360_dial_img_8_263030_3,
	&face_arctic_360_dial_img_8_263030_4,
	&face_arctic_360_dial_img_8_263030_5,
	&face_arctic_360_dial_img_8_263030_6,
};
const lv_img_dsc_t *face_arctic_360_dial_img_9_259332_group[] = {
	&face_arctic_360_dial_img_9_259332_0,
	&face_arctic_360_dial_img_9_259332_1,
	&face_arctic_360_dial_img_9_259332_2,
	&face_arctic_360_dial_img_9_259332_3,
	&face_arctic_360_dial_img_9_259332_4,
	&face_arctic_360_dial_img_9_259332_5,
	&face_arctic_360_dial_img_9_259332_6,
	&face_arctic_360_dial_img_9_259332_7,
	&face_arctic_360_dial_img_9_259332_8,
	&face_arctic_360_dial_img_9_259332_9,
};
const lv_img_dsc_t *face_arctic_360_dial_img_weather[] = {
	&face_arctic_360_dial_img_19_293418_0,
};
const lv_img_dsc_t *face_arctic_360_dial_img_34_284972_group[] = {
	&face_arctic_360_dial_img_34_284972_0,
	&face_arctic_360_dial_img_34_284972_1,
	&face_arctic_360_dial_img_34_284972_2,
	&face_arctic_360_dial_img_34_284972_3,
	&face_arctic_360_dial_img_34_284972_4,
	&face_arctic_360_dial_img_34_284972_5,
	&face_arctic_360_dial_img_34_284972_6,
};




#endif

void init_face_arctic_360(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **)){
#ifdef ENABLE_FACE_ARCTIC_360
    face_arctic_360 = lv_obj_create(NULL);
    lv_obj_clear_flag(face_arctic_360, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_arctic_360, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_arctic_360, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_arctic_360, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_arctic_360, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_arctic_360, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_arctic_360, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_arctic_360, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_arctic_360, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_arctic_360_0_724 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_0_724, &face_arctic_360_dial_img_0_724_0);
    lv_obj_set_width(face_arctic_360_0_724, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_0_724, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_0_724, 0);
    lv_obj_set_y(face_arctic_360_0_724, 0);
    lv_obj_add_flag(face_arctic_360_0_724, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_0_724, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_1_130834 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_1_130834, &face_arctic_360_dial_img_1_130834_0);
    lv_obj_set_width(face_arctic_360_1_130834, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_1_130834, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_1_130834, 128);
    lv_obj_set_y(face_arctic_360_1_130834, 126);
    lv_obj_add_flag(face_arctic_360_1_130834, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_1_130834, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_2_130834 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_2_130834, &face_arctic_360_dial_img_1_130834_0);
    lv_obj_set_width(face_arctic_360_2_130834, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_2_130834, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_2_130834, 62);
    lv_obj_set_y(face_arctic_360_2_130834, 126);
    lv_obj_add_flag(face_arctic_360_2_130834, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_2_130834, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_3_210070 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_3_210070, &face_arctic_360_dial_img_3_210070_0);
    lv_obj_set_width(face_arctic_360_3_210070, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_3_210070, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_3_210070, 253);
    lv_obj_set_y(face_arctic_360_3_210070, 121);
    lv_obj_add_flag(face_arctic_360_3_210070, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_3_210070, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_4_210070 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_4_210070, &face_arctic_360_dial_img_3_210070_0);
    lv_obj_set_width(face_arctic_360_4_210070, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_4_210070, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_4_210070, 203);
    lv_obj_set_y(face_arctic_360_4_210070, 121);
    lv_obj_add_flag(face_arctic_360_4_210070, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_4_210070, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_5_255122 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_5_255122, &face_arctic_360_dial_img_5_255122_0);
    lv_obj_set_width(face_arctic_360_5_255122, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_5_255122, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_5_255122, 279);
    lv_obj_set_y(face_arctic_360_5_255122, 221);
    lv_obj_add_flag(face_arctic_360_5_255122, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_5_255122, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_6_255122 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_6_255122, &face_arctic_360_dial_img_5_255122_0);
    lv_obj_set_width(face_arctic_360_6_255122, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_6_255122, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_6_255122, 265);
    lv_obj_set_y(face_arctic_360_6_255122, 221);
    lv_obj_add_flag(face_arctic_360_6_255122, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_6_255122, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_8_263030 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_8_263030, &face_arctic_360_dial_img_8_263030_0);
    lv_obj_set_width(face_arctic_360_8_263030, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_8_263030, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_8_263030, 199);
    lv_obj_set_y(face_arctic_360_8_263030, 221);
    lv_obj_add_flag(face_arctic_360_8_263030, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_8_263030, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_9_259332 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_9_259332, &face_arctic_360_dial_img_9_259332_0);
    lv_obj_set_width(face_arctic_360_9_259332, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_9_259332, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_9_259332, 259);
    lv_obj_set_y(face_arctic_360_9_259332, 265);
    lv_obj_add_flag(face_arctic_360_9_259332, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_9_259332, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_10_259332 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_10_259332, &face_arctic_360_dial_img_9_259332_0);
    lv_obj_set_width(face_arctic_360_10_259332, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_10_259332, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_10_259332, 249);
    lv_obj_set_y(face_arctic_360_10_259332, 265);
    lv_obj_add_flag(face_arctic_360_10_259332, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_10_259332, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_11_259332 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_11_259332, &face_arctic_360_dial_img_9_259332_0);
    lv_obj_set_width(face_arctic_360_11_259332, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_11_259332, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_11_259332, 239);
    lv_obj_set_y(face_arctic_360_11_259332, 265);
    lv_obj_add_flag(face_arctic_360_11_259332, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_11_259332, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_12_259332 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_12_259332, &face_arctic_360_dial_img_9_259332_0);
    lv_obj_set_width(face_arctic_360_12_259332, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_12_259332, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_12_259332, 230);
    lv_obj_set_y(face_arctic_360_12_259332, 265);
    lv_obj_add_flag(face_arctic_360_12_259332, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_12_259332, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_13_259332 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_13_259332, &face_arctic_360_dial_img_9_259332_0);
    lv_obj_set_width(face_arctic_360_13_259332, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_13_259332, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_13_259332, 219);
    lv_obj_set_y(face_arctic_360_13_259332, 265);
    lv_obj_add_flag(face_arctic_360_13_259332, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_13_259332, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_14_259332 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_14_259332, &face_arctic_360_dial_img_9_259332_0);
    lv_obj_set_width(face_arctic_360_14_259332, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_14_259332, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_14_259332, 149);
    lv_obj_set_y(face_arctic_360_14_259332, 265);
    lv_obj_add_flag(face_arctic_360_14_259332, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_14_259332, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_15_259332 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_15_259332, &face_arctic_360_dial_img_9_259332_0);
    lv_obj_set_width(face_arctic_360_15_259332, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_15_259332, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_15_259332, 139);
    lv_obj_set_y(face_arctic_360_15_259332, 265);
    lv_obj_add_flag(face_arctic_360_15_259332, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_15_259332, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_16_259332 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_16_259332, &face_arctic_360_dial_img_9_259332_0);
    lv_obj_set_width(face_arctic_360_16_259332, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_16_259332, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_16_259332, 132);
    lv_obj_set_y(face_arctic_360_16_259332, 265);
    lv_obj_add_flag(face_arctic_360_16_259332, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_16_259332, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_17_259332 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_17_259332, &face_arctic_360_dial_img_9_259332_0);
    lv_obj_set_width(face_arctic_360_17_259332, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_17_259332, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_17_259332, 161);
    lv_obj_set_y(face_arctic_360_17_259332, 265);
    lv_obj_add_flag(face_arctic_360_17_259332, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_17_259332, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_19_293418 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_19_293418, &face_arctic_360_dial_img_19_293418_0);
    lv_obj_set_width(face_arctic_360_19_293418, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_19_293418, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_19_293418, 76);
    lv_obj_set_y(face_arctic_360_19_293418, 81);
    lv_obj_add_flag(face_arctic_360_19_293418, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_19_293418, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_30_259332 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_30_259332, &face_arctic_360_dial_img_9_259332_0);
    lv_obj_set_width(face_arctic_360_30_259332, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_30_259332, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_30_259332, 125);
    lv_obj_set_y(face_arctic_360_30_259332, 86);
    lv_obj_add_flag(face_arctic_360_30_259332, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_30_259332, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_31_259332 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_31_259332, &face_arctic_360_dial_img_9_259332_0);
    lv_obj_set_width(face_arctic_360_31_259332, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_31_259332, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_31_259332, 112);
    lv_obj_set_y(face_arctic_360_31_259332, 86);
    lv_obj_add_flag(face_arctic_360_31_259332, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_31_259332, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_32_259332 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_32_259332, &face_arctic_360_dial_img_9_259332_0);
    lv_obj_set_width(face_arctic_360_32_259332, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_32_259332, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_32_259332, 138);
    lv_obj_set_y(face_arctic_360_32_259332, 86);
    lv_obj_add_flag(face_arctic_360_32_259332, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_32_259332, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_34_284972 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_34_284972, &face_arctic_360_dial_img_34_284972_0);
    lv_obj_set_width(face_arctic_360_34_284972, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_34_284972, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_34_284972, 96);
    lv_obj_set_y(face_arctic_360_34_284972, 260);
    lv_obj_add_flag(face_arctic_360_34_284972, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_34_284972, LV_OBJ_FLAG_SCROLLABLE );

    face_arctic_360_35_65535 = lv_img_create(face_arctic_360);
    lv_img_set_src(face_arctic_360_35_65535, &face_arctic_360_dial_img_28_65535_0);
    lv_obj_set_width(face_arctic_360_35_65535, LV_SIZE_CONTENT);
    lv_obj_set_height(face_arctic_360_35_65535, LV_SIZE_CONTENT);
    lv_obj_set_x(face_arctic_360_35_65535, 182);
    lv_obj_set_y(face_arctic_360_35_65535, 86);
    lv_obj_add_flag(face_arctic_360_35_65535, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_arctic_360_35_65535, LV_OBJ_FLAG_SCROLLABLE );


    callback("Arctic", &face_arctic_360_dial_img_preview_0, &face_arctic_360, NULL);

#endif
}

void update_time_arctic_360(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_ARCTIC_360
    if (!face_arctic_360)
    {
        return;
    }
	lv_img_set_src(face_arctic_360_1_130834, face_arctic_360_dial_img_1_130834_group[(hour / 1) % 10]);
	lv_img_set_src(face_arctic_360_2_130834, face_arctic_360_dial_img_1_130834_group[(hour / 10) % 10]);
	lv_img_set_src(face_arctic_360_3_210070, face_arctic_360_dial_img_3_210070_group[(minute / 1) % 10]);
	lv_img_set_src(face_arctic_360_4_210070, face_arctic_360_dial_img_3_210070_group[(minute / 10) % 10]);
	lv_img_set_src(face_arctic_360_5_255122, face_arctic_360_dial_img_5_255122_group[(day / 1) % 10]);
	lv_img_set_src(face_arctic_360_6_255122, face_arctic_360_dial_img_5_255122_group[(day / 10) % 10]);
	lv_img_set_src(face_arctic_360_8_263030, face_arctic_360_dial_img_8_263030_group[((weekday + 6) / 1) % 7]);

#endif
}

void update_weather_arctic_360(int temp, int icon)
{
#ifdef ENABLE_FACE_ARCTIC_360
    if (!face_arctic_360)
    {
        return;
    }
	lv_img_set_src(face_arctic_360_19_293418, face_arctic_360_dial_img_weather[icon % 8]);
	lv_img_set_src(face_arctic_360_30_259332, face_arctic_360_dial_img_9_259332_group[(temp / 1) % 10]);
	lv_img_set_src(face_arctic_360_31_259332, face_arctic_360_dial_img_9_259332_group[(temp / 10) % 10]);

#endif
}

void update_status_arctic_360(int battery, bool connection){
#ifdef ENABLE_FACE_ARCTIC_360
    if (!face_arctic_360)
    {
        return;
    }
	lv_img_set_src(face_arctic_360_14_259332, face_arctic_360_dial_img_9_259332_group[(battery / 1) % 10]);
	lv_img_set_src(face_arctic_360_15_259332, face_arctic_360_dial_img_9_259332_group[(battery / 10) % 10]);
	lv_img_set_src(face_arctic_360_16_259332, face_arctic_360_dial_img_9_259332_group[(battery / 100) % 10]);
	if (battery < 100)
	{
		lv_obj_add_flag(face_arctic_360_16_259332, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_arctic_360_16_259332, LV_OBJ_FLAG_HIDDEN);
	}
	lv_img_set_src(face_arctic_360_34_284972, face_arctic_360_dial_img_34_284972_group[(battery / (100 / 7)) % 7]);

#endif
}

void update_activity_arctic_360(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_ARCTIC_360
    if (!face_arctic_360)
    {
        return;
    }
	lv_img_set_src(face_arctic_360_9_259332, face_arctic_360_dial_img_9_259332_group[(steps / 1) % 10]);
	lv_img_set_src(face_arctic_360_10_259332, face_arctic_360_dial_img_9_259332_group[(steps / 10) % 10]);
	lv_img_set_src(face_arctic_360_11_259332, face_arctic_360_dial_img_9_259332_group[(steps / 100) % 10]);
	lv_img_set_src(face_arctic_360_12_259332, face_arctic_360_dial_img_9_259332_group[(steps / 1000) % 10]);
	lv_img_set_src(face_arctic_360_13_259332, face_arctic_360_dial_img_9_259332_group[(steps / 10000) % 10]);

#endif
}

void update_health_arctic_360(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_ARCTIC_360
    if (!face_arctic_360)
    {
        return;
    }

#endif
}

void update_all_arctic_360(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_ARCTIC_360
    update_time_arctic_360(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_arctic_360(temp, icon);
    update_status_arctic_360(battery, connection);
    update_activity_arctic_360(steps, distance, kcal);
    update_health_arctic_360(bpm, oxygen);
#endif
}

void update_check_arctic_360(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_ARCTIC_360
    if (root != face_arctic_360)
    {
        return;
    }
    update_time_arctic_360(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_arctic_360(temp, icon);
    update_status_arctic_360(battery, connection);
    update_activity_arctic_360(steps, distance, kcal);
    update_health_arctic_360(bpm, oxygen);
#endif
}


