
/**
 * @file calendar.h
 * @brief Calendar app for C3 UI
 * Generated by app_create.py
 */

#ifndef _CALENDAR_APP_H
#define _CALENDAR_APP_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"
#include "app_hal.h"
#include "../../common/app_manager.h"

#ifdef ENABLE_APP_CALENDAR

    LV_IMAGE_DECLARE(ui_img_calendar_png);

    void calendar_screen_init(void);

    void ui_app_load(lv_obj_t **screen, void (*screen_init)(void));
    void ui_app_exit(void);


#endif

void calendar_app_launched(void);
void calendar_set_today(int year, int month, int day);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif /*_CALENDAR_APP_H*/
