
/**
 * @file calendar.c
 * @brief Calendar app for C3 UI
 * Generated by app_create.py
 */

#include "calendar.h"

#ifdef ENABLE_APP_CALENDAR

REGISTER_APP("Calendar", &ui_img_calendar_png, calendar_screen_main, calendar_screen_init);

static lv_obj_t *cal_obj;

void calendar_screen_event_cb(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START)
    {
        /* Do something before the screen is loaded */
    }
    if (event_code == LV_EVENT_SCREEN_LOADED)
    {
        /* Do something after the screen is loaded */
        /* This is a good place to start animations or timers */

        calendar_app_launched();
    }
    if (event_code == LV_EVENT_SCREEN_UNLOAD_START)
    {
        /* Do something before the screen is unloaded */
        /* This is a good place to save data or stop timers */
    }
    if (event_code == LV_EVENT_SCREEN_UNLOADED)
    {
        /* Do something after the screen is unloaded */
        /* This is a good place to clean up resources */

        /* Clean and delete screen if needed */
        lv_obj_delete(calendar_screen_main);
        calendar_screen_main = NULL;
    }

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT)
    {
        ui_app_exit(); /* exit to app list */
        /* Call this function to close the app, you can even use button instead of gesture */
    }
}

void calendar_screen_init(void)
{
    /* create the screen */
    calendar_screen_main = lv_obj_create(NULL);
    lv_obj_remove_flag(calendar_screen_main, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(calendar_screen_main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(calendar_screen_main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    cal_obj = lv_calendar_create(calendar_screen_main);
    lv_obj_t *cal_obj_header = lv_calendar_header_arrow_create(cal_obj);
    lv_obj_set_width(cal_obj, 200);
    lv_obj_set_height(cal_obj, 200);
    lv_obj_set_align(cal_obj, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(cal_obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cal_obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cal_obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(calendar_screen_main, calendar_screen_event_cb, LV_EVENT_ALL, NULL);
}

#endif

void calendar_set_today(int year, int month, int day)
{
#ifdef ENABLE_APP_CALENDAR
    if (calendar_screen_main == NULL)
    {
        return;
    }
    lv_calendar_set_today_date(cal_obj, year, month, day);
    lv_calendar_set_showed_date(cal_obj, year, month);
#endif
}
