
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 174_410

#ifndef _FACE_174_410_H
#define _FACE_174_410_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"
#include "app_hal.h"

//#define ENABLE_FACE_174_410 // (174) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_174_410
    extern lv_obj_t *face_174_410;
	extern lv_obj_t *face_174_410_0_744;
	extern lv_obj_t *face_174_410_1_8347;
	extern lv_obj_t *face_174_410_2_15980;
	extern lv_obj_t *face_174_410_3_42048;
	extern lv_obj_t *face_174_410_5_52144;
	extern lv_obj_t *face_174_410_7_56358;
	extern lv_obj_t *face_174_410_9_59272;
	extern lv_obj_t *face_174_410_11_61178;
	extern lv_obj_t *face_174_410_13_63313;
	extern lv_obj_t *face_174_410_14_64537;
	extern lv_obj_t *face_174_410_15_64537;
	extern lv_obj_t *face_174_410_16_64537;
	extern lv_obj_t *face_174_410_17_64537;
	extern lv_obj_t *face_174_410_18_64537;
	extern lv_obj_t *face_174_410_19_64537;
	extern lv_obj_t *face_174_410_20_64537;
	extern lv_obj_t *face_174_410_21_64537;
	extern lv_obj_t *face_174_410_22_64537;
	extern lv_obj_t *face_174_410_23_64537;
	extern lv_obj_t *face_174_410_24_64537;
	extern lv_obj_t *face_174_410_25_64537;
	extern lv_obj_t *face_174_410_26_67871;
	extern lv_obj_t *face_174_410_27_67871;
	extern lv_obj_t *face_174_410_28_73905;
	extern lv_obj_t *face_174_410_29_67871;
	extern lv_obj_t *face_174_410_30_67871;
	extern lv_obj_t *face_174_410_31_74532;
	extern lv_obj_t *face_174_410_32_74532;
	extern lv_obj_t *face_174_410_33_188086;
	extern lv_obj_t *face_174_410_34_188086;
	extern lv_obj_t *face_174_410_36_352525;


	LV_IMG_DECLARE(face_174_410_dial_img_0_744_0);
	LV_IMG_DECLARE(face_174_410_dial_img_1_8347_0);
	LV_IMG_DECLARE(face_174_410_dial_img_2_15980_0);
	LV_IMG_DECLARE(face_174_410_dial_img_3_42048_0);
	LV_IMG_DECLARE(face_174_410_dial_img_4_49557_0);
	LV_IMG_DECLARE(face_174_410_dial_img_4_49557_1);
	LV_IMG_DECLARE(face_174_410_dial_img_5_52144_0);
	LV_IMG_DECLARE(face_174_410_dial_img_5_52144_1);
	LV_IMG_DECLARE(face_174_410_dial_img_6_54731_0);
	LV_IMG_DECLARE(face_174_410_dial_img_6_54731_1);
	LV_IMG_DECLARE(face_174_410_dial_img_7_56358_0);
	LV_IMG_DECLARE(face_174_410_dial_img_7_56358_1);
	LV_IMG_DECLARE(face_174_410_dial_img_8_57904_0);
	LV_IMG_DECLARE(face_174_410_dial_img_9_59272_0);
	LV_IMG_DECLARE(face_174_410_dial_img_10_60088_0);
	LV_IMG_DECLARE(face_174_410_dial_img_11_61178_0);
	LV_IMG_DECLARE(face_174_410_dial_img_12_62198_0);
	LV_IMG_DECLARE(face_174_410_dial_img_13_63313_0);
	LV_IMG_DECLARE(face_174_410_dial_img_14_64537_0);
	LV_IMG_DECLARE(face_174_410_dial_img_14_64537_1);
	LV_IMG_DECLARE(face_174_410_dial_img_14_64537_2);
	LV_IMG_DECLARE(face_174_410_dial_img_14_64537_3);
	LV_IMG_DECLARE(face_174_410_dial_img_14_64537_4);
	LV_IMG_DECLARE(face_174_410_dial_img_14_64537_5);
	LV_IMG_DECLARE(face_174_410_dial_img_14_64537_6);
	LV_IMG_DECLARE(face_174_410_dial_img_14_64537_7);
	LV_IMG_DECLARE(face_174_410_dial_img_14_64537_8);
	LV_IMG_DECLARE(face_174_410_dial_img_14_64537_9);
	LV_IMG_DECLARE(face_174_410_dial_img_26_67871_0);
	LV_IMG_DECLARE(face_174_410_dial_img_26_67871_1);
	LV_IMG_DECLARE(face_174_410_dial_img_26_67871_2);
	LV_IMG_DECLARE(face_174_410_dial_img_26_67871_3);
	LV_IMG_DECLARE(face_174_410_dial_img_26_67871_4);
	LV_IMG_DECLARE(face_174_410_dial_img_26_67871_5);
	LV_IMG_DECLARE(face_174_410_dial_img_26_67871_6);
	LV_IMG_DECLARE(face_174_410_dial_img_26_67871_7);
	LV_IMG_DECLARE(face_174_410_dial_img_26_67871_8);
	LV_IMG_DECLARE(face_174_410_dial_img_26_67871_9);
	LV_IMG_DECLARE(face_174_410_dial_img_28_73905_0);
	LV_IMG_DECLARE(face_174_410_dial_img_31_74532_0);
	LV_IMG_DECLARE(face_174_410_dial_img_31_74532_1);
	LV_IMG_DECLARE(face_174_410_dial_img_31_74532_2);
	LV_IMG_DECLARE(face_174_410_dial_img_31_74532_3);
	LV_IMG_DECLARE(face_174_410_dial_img_31_74532_4);
	LV_IMG_DECLARE(face_174_410_dial_img_31_74532_5);
	LV_IMG_DECLARE(face_174_410_dial_img_31_74532_6);
	LV_IMG_DECLARE(face_174_410_dial_img_31_74532_7);
	LV_IMG_DECLARE(face_174_410_dial_img_31_74532_8);
	LV_IMG_DECLARE(face_174_410_dial_img_31_74532_9);
	LV_IMG_DECLARE(face_174_410_dial_img_33_188086_0);
	LV_IMG_DECLARE(face_174_410_dial_img_33_188086_1);
	LV_IMG_DECLARE(face_174_410_dial_img_33_188086_2);
	LV_IMG_DECLARE(face_174_410_dial_img_33_188086_3);
	LV_IMG_DECLARE(face_174_410_dial_img_33_188086_4);
	LV_IMG_DECLARE(face_174_410_dial_img_33_188086_5);
	LV_IMG_DECLARE(face_174_410_dial_img_33_188086_6);
	LV_IMG_DECLARE(face_174_410_dial_img_33_188086_7);
	LV_IMG_DECLARE(face_174_410_dial_img_33_188086_8);
	LV_IMG_DECLARE(face_174_410_dial_img_33_188086_9);
	LV_IMG_DECLARE(face_174_410_dial_img_35_334116_0);
	LV_IMG_DECLARE(face_174_410_dial_img_35_334116_1);
	LV_IMG_DECLARE(face_174_410_dial_img_35_334116_2);
	LV_IMG_DECLARE(face_174_410_dial_img_35_334116_3);
	LV_IMG_DECLARE(face_174_410_dial_img_35_334116_4);
	LV_IMG_DECLARE(face_174_410_dial_img_35_334116_5);
	LV_IMG_DECLARE(face_174_410_dial_img_35_334116_6);
	LV_IMG_DECLARE(face_174_410_dial_img_36_352525_0);
	LV_IMG_DECLARE(face_174_410_dial_img_36_352525_1);
	LV_IMG_DECLARE(face_174_410_dial_img_36_352525_2);
	LV_IMG_DECLARE(face_174_410_dial_img_36_352525_3);
	LV_IMG_DECLARE(face_174_410_dial_img_36_352525_4);
	LV_IMG_DECLARE(face_174_410_dial_img_36_352525_5);
	LV_IMG_DECLARE(face_174_410_dial_img_36_352525_6);
	LV_IMG_DECLARE(face_174_410_dial_img_preview_0);
	LV_IMG_DECLARE(face_174_410_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_174_410(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **));
    void update_time_174_410(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_174_410(int temp, int icon);
    void update_status_174_410(int battery, bool connection);
    void update_activity_174_410(int steps, int distance, int kcal);
    void update_health_174_410(int bpm, int oxygen);
    void update_all_174_410(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_174_410(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
