
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 174_410

#include "174_410.h"

#ifdef ENABLE_FACE_174_410

lv_obj_t *face_174_410;
lv_obj_t *face_174_410_0_744;
lv_obj_t *face_174_410_1_8347;
lv_obj_t *face_174_410_2_15980;
lv_obj_t *face_174_410_3_42048;
lv_obj_t *face_174_410_5_52144;
lv_obj_t *face_174_410_7_56358;
lv_obj_t *face_174_410_9_59272;
lv_obj_t *face_174_410_11_61178;
lv_obj_t *face_174_410_13_63313;
lv_obj_t *face_174_410_14_64537;
lv_obj_t *face_174_410_15_64537;
lv_obj_t *face_174_410_16_64537;
lv_obj_t *face_174_410_17_64537;
lv_obj_t *face_174_410_18_64537;
lv_obj_t *face_174_410_19_64537;
lv_obj_t *face_174_410_20_64537;
lv_obj_t *face_174_410_21_64537;
lv_obj_t *face_174_410_22_64537;
lv_obj_t *face_174_410_23_64537;
lv_obj_t *face_174_410_24_64537;
lv_obj_t *face_174_410_25_64537;
lv_obj_t *face_174_410_26_67871;
lv_obj_t *face_174_410_27_67871;
lv_obj_t *face_174_410_28_73905;
lv_obj_t *face_174_410_29_67871;
lv_obj_t *face_174_410_30_67871;
lv_obj_t *face_174_410_31_74532;
lv_obj_t *face_174_410_32_74532;
lv_obj_t *face_174_410_33_188086;
lv_obj_t *face_174_410_34_188086;
lv_obj_t *face_174_410_36_352525;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif

const lv_img_dsc_t *face_174_410_dial_img_4_49557_group[] = {
	&face_174_410_dial_img_4_49557_0,
	&face_174_410_dial_img_4_49557_1,
};
const lv_img_dsc_t *face_174_410_dial_img_5_52144_group[] = {
	&face_174_410_dial_img_5_52144_0,
	&face_174_410_dial_img_5_52144_1,
};
const lv_img_dsc_t *face_174_410_dial_img_6_54731_group[] = {
	&face_174_410_dial_img_6_54731_0,
	&face_174_410_dial_img_6_54731_1,
};
const lv_img_dsc_t *face_174_410_dial_img_7_56358_group[] = {
	&face_174_410_dial_img_7_56358_0,
	&face_174_410_dial_img_7_56358_1,
};
const lv_img_dsc_t *face_174_410_dial_img_14_64537_group[] = {
	&face_174_410_dial_img_14_64537_0,
	&face_174_410_dial_img_14_64537_1,
	&face_174_410_dial_img_14_64537_2,
	&face_174_410_dial_img_14_64537_3,
	&face_174_410_dial_img_14_64537_4,
	&face_174_410_dial_img_14_64537_5,
	&face_174_410_dial_img_14_64537_6,
	&face_174_410_dial_img_14_64537_7,
	&face_174_410_dial_img_14_64537_8,
	&face_174_410_dial_img_14_64537_9,
};
const lv_img_dsc_t *face_174_410_dial_img_26_67871_group[] = {
	&face_174_410_dial_img_26_67871_0,
	&face_174_410_dial_img_26_67871_1,
	&face_174_410_dial_img_26_67871_2,
	&face_174_410_dial_img_26_67871_3,
	&face_174_410_dial_img_26_67871_4,
	&face_174_410_dial_img_26_67871_5,
	&face_174_410_dial_img_26_67871_6,
	&face_174_410_dial_img_26_67871_7,
	&face_174_410_dial_img_26_67871_8,
	&face_174_410_dial_img_26_67871_9,
};
const lv_img_dsc_t *face_174_410_dial_img_31_74532_group[] = {
	&face_174_410_dial_img_31_74532_0,
	&face_174_410_dial_img_31_74532_1,
	&face_174_410_dial_img_31_74532_2,
	&face_174_410_dial_img_31_74532_3,
	&face_174_410_dial_img_31_74532_4,
	&face_174_410_dial_img_31_74532_5,
	&face_174_410_dial_img_31_74532_6,
	&face_174_410_dial_img_31_74532_7,
	&face_174_410_dial_img_31_74532_8,
	&face_174_410_dial_img_31_74532_9,
};
const lv_img_dsc_t *face_174_410_dial_img_33_188086_group[] = {
	&face_174_410_dial_img_33_188086_0,
	&face_174_410_dial_img_33_188086_1,
	&face_174_410_dial_img_33_188086_2,
	&face_174_410_dial_img_33_188086_3,
	&face_174_410_dial_img_33_188086_4,
	&face_174_410_dial_img_33_188086_5,
	&face_174_410_dial_img_33_188086_6,
	&face_174_410_dial_img_33_188086_7,
	&face_174_410_dial_img_33_188086_8,
	&face_174_410_dial_img_33_188086_9,
};
const lv_img_dsc_t *face_174_410_dial_img_35_334116_group[] = {
	&face_174_410_dial_img_35_334116_0,
	&face_174_410_dial_img_35_334116_1,
	&face_174_410_dial_img_35_334116_2,
	&face_174_410_dial_img_35_334116_3,
	&face_174_410_dial_img_35_334116_4,
	&face_174_410_dial_img_35_334116_5,
	&face_174_410_dial_img_35_334116_6,
};
const lv_img_dsc_t *face_174_410_dial_img_36_352525_group[] = {
	&face_174_410_dial_img_36_352525_0,
	&face_174_410_dial_img_36_352525_1,
	&face_174_410_dial_img_36_352525_2,
	&face_174_410_dial_img_36_352525_3,
	&face_174_410_dial_img_36_352525_4,
	&face_174_410_dial_img_36_352525_5,
	&face_174_410_dial_img_36_352525_6,
};




#endif

void init_face_174_410(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **)){
#ifdef ENABLE_FACE_174_410
    face_174_410 = lv_obj_create(NULL);
    lv_obj_clear_flag(face_174_410, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_174_410, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_174_410, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_174_410, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_174_410, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_174_410, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_174_410, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_174_410, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_174_410, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_174_410_0_744 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_0_744, &face_174_410_dial_img_0_744_0);
    lv_obj_set_width(face_174_410_0_744, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_0_744, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_0_744, 18);
    lv_obj_set_y(face_174_410_0_744, 160);
    lv_obj_add_flag(face_174_410_0_744, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_0_744, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_1_8347 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_1_8347, &face_174_410_dial_img_1_8347_0);
    lv_obj_set_width(face_174_410_1_8347, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_1_8347, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_1_8347, 18);
    lv_obj_set_y(face_174_410_1_8347, 280);
    lv_obj_add_flag(face_174_410_1_8347, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_1_8347, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_2_15980 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_2_15980, &face_174_410_dial_img_2_15980_0);
    lv_obj_set_width(face_174_410_2_15980, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_2_15980, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_2_15980, 18);
    lv_obj_set_y(face_174_410_2_15980, 394);
    lv_obj_add_flag(face_174_410_2_15980, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_2_15980, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_3_42048 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_3_42048, &face_174_410_dial_img_3_42048_0);
    lv_obj_set_width(face_174_410_3_42048, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_3_42048, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_3_42048, 18);
    lv_obj_set_y(face_174_410_3_42048, 42);
    lv_obj_add_flag(face_174_410_3_42048, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_3_42048, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_5_52144 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_5_52144, &face_174_410_dial_img_5_52144_0);
    lv_obj_set_width(face_174_410_5_52144, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_5_52144, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_5_52144, 160);
    lv_obj_set_y(face_174_410_5_52144, 411);
    lv_obj_add_flag(face_174_410_5_52144, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_5_52144, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_7_56358 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_7_56358, &face_174_410_dial_img_7_56358_0);
    lv_obj_set_width(face_174_410_7_56358, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_7_56358, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_7_56358, 160);
    lv_obj_set_y(face_174_410_7_56358, 420);
    lv_obj_add_flag(face_174_410_7_56358, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_7_56358, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_9_59272 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_9_59272, &face_174_410_dial_img_9_59272_0);
    lv_obj_set_width(face_174_410_9_59272, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_9_59272, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_9_59272, 134);
    lv_obj_set_y(face_174_410_9_59272, 61);
    lv_obj_add_flag(face_174_410_9_59272, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_9_59272, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_11_61178 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_11_61178, &face_174_410_dial_img_11_61178_0);
    lv_obj_set_width(face_174_410_11_61178, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_11_61178, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_11_61178, 128);
    lv_obj_set_y(face_174_410_11_61178, 292);
    lv_obj_add_flag(face_174_410_11_61178, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_11_61178, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_13_63313 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_13_63313, &face_174_410_dial_img_13_63313_0);
    lv_obj_set_width(face_174_410_13_63313, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_13_63313, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_13_63313, 123);
    lv_obj_set_y(face_174_410_13_63313, 186);
    lv_obj_add_flag(face_174_410_13_63313, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_13_63313, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_14_64537 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_14_64537, &face_174_410_dial_img_14_64537_0);
    lv_obj_set_width(face_174_410_14_64537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_14_64537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_14_64537, 165);
    lv_obj_set_y(face_174_410_14_64537, 95);
    lv_obj_add_flag(face_174_410_14_64537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_14_64537, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_15_64537 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_15_64537, &face_174_410_dial_img_14_64537_0);
    lv_obj_set_width(face_174_410_15_64537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_15_64537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_15_64537, 150);
    lv_obj_set_y(face_174_410_15_64537, 95);
    lv_obj_add_flag(face_174_410_15_64537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_15_64537, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_16_64537 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_16_64537, &face_174_410_dial_img_14_64537_0);
    lv_obj_set_width(face_174_410_16_64537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_16_64537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_16_64537, 134);
    lv_obj_set_y(face_174_410_16_64537, 95);
    lv_obj_add_flag(face_174_410_16_64537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_16_64537, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_17_64537 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_17_64537, &face_174_410_dial_img_14_64537_0);
    lv_obj_set_width(face_174_410_17_64537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_17_64537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_17_64537, 172);
    lv_obj_set_y(face_174_410_17_64537, 326);
    lv_obj_add_flag(face_174_410_17_64537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_17_64537, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_18_64537 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_18_64537, &face_174_410_dial_img_14_64537_0);
    lv_obj_set_width(face_174_410_18_64537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_18_64537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_18_64537, 157);
    lv_obj_set_y(face_174_410_18_64537, 326);
    lv_obj_add_flag(face_174_410_18_64537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_18_64537, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_19_64537 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_19_64537, &face_174_410_dial_img_14_64537_0);
    lv_obj_set_width(face_174_410_19_64537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_19_64537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_19_64537, 141);
    lv_obj_set_y(face_174_410_19_64537, 326);
    lv_obj_add_flag(face_174_410_19_64537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_19_64537, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_20_64537 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_20_64537, &face_174_410_dial_img_14_64537_0);
    lv_obj_set_width(face_174_410_20_64537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_20_64537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_20_64537, 126);
    lv_obj_set_y(face_174_410_20_64537, 326);
    lv_obj_add_flag(face_174_410_20_64537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_20_64537, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_21_64537 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_21_64537, &face_174_410_dial_img_14_64537_0);
    lv_obj_set_width(face_174_410_21_64537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_21_64537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_21_64537, 181);
    lv_obj_set_y(face_174_410_21_64537, 218);
    lv_obj_add_flag(face_174_410_21_64537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_21_64537, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_22_64537 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_22_64537, &face_174_410_dial_img_14_64537_0);
    lv_obj_set_width(face_174_410_22_64537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_22_64537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_22_64537, 165);
    lv_obj_set_y(face_174_410_22_64537, 218);
    lv_obj_add_flag(face_174_410_22_64537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_22_64537, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_23_64537 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_23_64537, &face_174_410_dial_img_14_64537_0);
    lv_obj_set_width(face_174_410_23_64537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_23_64537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_23_64537, 150);
    lv_obj_set_y(face_174_410_23_64537, 218);
    lv_obj_add_flag(face_174_410_23_64537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_23_64537, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_24_64537 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_24_64537, &face_174_410_dial_img_14_64537_0);
    lv_obj_set_width(face_174_410_24_64537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_24_64537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_24_64537, 134);
    lv_obj_set_y(face_174_410_24_64537, 218);
    lv_obj_add_flag(face_174_410_24_64537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_24_64537, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_25_64537 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_25_64537, &face_174_410_dial_img_14_64537_0);
    lv_obj_set_width(face_174_410_25_64537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_25_64537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_25_64537, 119);
    lv_obj_set_y(face_174_410_25_64537, 218);
    lv_obj_add_flag(face_174_410_25_64537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_25_64537, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_26_67871 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_26_67871, &face_174_410_dial_img_26_67871_0);
    lv_obj_set_width(face_174_410_26_67871, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_26_67871, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_26_67871, 269);
    lv_obj_set_y(face_174_410_26_67871, 416);
    lv_obj_add_flag(face_174_410_26_67871, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_26_67871, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_27_67871 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_27_67871, &face_174_410_dial_img_26_67871_0);
    lv_obj_set_width(face_174_410_27_67871, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_27_67871, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_27_67871, 249);
    lv_obj_set_y(face_174_410_27_67871, 416);
    lv_obj_add_flag(face_174_410_27_67871, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_27_67871, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_28_73905 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_28_73905, &face_174_410_dial_img_28_73905_0);
    lv_obj_set_width(face_174_410_28_73905, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_28_73905, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_28_73905, 290);
    lv_obj_set_y(face_174_410_28_73905, 415);
    lv_obj_add_flag(face_174_410_28_73905, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_28_73905, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_29_67871 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_29_67871, &face_174_410_dial_img_26_67871_0);
    lv_obj_set_width(face_174_410_29_67871, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_29_67871, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_29_67871, 328);
    lv_obj_set_y(face_174_410_29_67871, 416);
    lv_obj_add_flag(face_174_410_29_67871, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_29_67871, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_30_67871 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_30_67871, &face_174_410_dial_img_26_67871_0);
    lv_obj_set_width(face_174_410_30_67871, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_30_67871, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_30_67871, 307);
    lv_obj_set_y(face_174_410_30_67871, 416);
    lv_obj_add_flag(face_174_410_30_67871, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_30_67871, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_31_74532 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_31_74532, &face_174_410_dial_img_31_74532_0);
    lv_obj_set_width(face_174_410_31_74532, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_31_74532, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_31_74532, 304);
    lv_obj_set_y(face_174_410_31_74532, 46);
    lv_obj_add_flag(face_174_410_31_74532, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_31_74532, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_32_74532 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_32_74532, &face_174_410_dial_img_31_74532_0);
    lv_obj_set_width(face_174_410_32_74532, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_32_74532, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_32_74532, 215);
    lv_obj_set_y(face_174_410_32_74532, 46);
    lv_obj_add_flag(face_174_410_32_74532, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_32_74532, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_33_188086 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_33_188086, &face_174_410_dial_img_33_188086_0);
    lv_obj_set_width(face_174_410_33_188086, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_33_188086, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_33_188086, 300);
    lv_obj_set_y(face_174_410_33_188086, 222);
    lv_obj_add_flag(face_174_410_33_188086, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_33_188086, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_34_188086 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_34_188086, &face_174_410_dial_img_33_188086_0);
    lv_obj_set_width(face_174_410_34_188086, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_34_188086, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_34_188086, 198);
    lv_obj_set_y(face_174_410_34_188086, 222);
    lv_obj_add_flag(face_174_410_34_188086, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_34_188086, LV_OBJ_FLAG_SCROLLABLE );

    face_174_410_36_352525 = lv_img_create(face_174_410);
    lv_img_set_src(face_174_410_36_352525, &face_174_410_dial_img_36_352525_0);
    lv_obj_set_width(face_174_410_36_352525, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_410_36_352525, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_410_36_352525, 52);
    lv_obj_set_y(face_174_410_36_352525, 418);
    lv_obj_add_flag(face_174_410_36_352525, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_174_410_36_352525, LV_OBJ_FLAG_SCROLLABLE );


    callback("174", &face_174_410_dial_img_preview_0, &face_174_410, NULL);

#endif
}

void update_time_174_410(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_174_410
    if (!face_174_410)
    {
        return;
    }
	if (mode)
	{
		lv_obj_add_flag(face_174_410_5_52144, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_174_410_5_52144, LV_OBJ_FLAG_HIDDEN);
	}
	lv_img_set_src(face_174_410_5_52144, face_174_410_dial_img_5_52144_group[(am ? 0 : 1) % 2]);
	if (mode)
	{
		lv_obj_add_flag(face_174_410_7_56358, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_174_410_7_56358, LV_OBJ_FLAG_HIDDEN);
	}
	lv_img_set_src(face_174_410_7_56358, face_174_410_dial_img_7_56358_group[(am ? 0 : 1) % 2]);
	lv_img_set_src(face_174_410_26_67871, face_174_410_dial_img_26_67871_group[(month / 1) % 10]);
	lv_img_set_src(face_174_410_27_67871, face_174_410_dial_img_26_67871_group[(month / 10) % 10]);
	lv_img_set_src(face_174_410_29_67871, face_174_410_dial_img_26_67871_group[(day / 1) % 10]);
	lv_img_set_src(face_174_410_30_67871, face_174_410_dial_img_26_67871_group[(day / 10) % 10]);
	lv_img_set_src(face_174_410_31_74532, face_174_410_dial_img_31_74532_group[(hour / 1) % 10]);
	lv_img_set_src(face_174_410_32_74532, face_174_410_dial_img_31_74532_group[(hour / 10) % 10]);
	lv_img_set_src(face_174_410_33_188086, face_174_410_dial_img_33_188086_group[(minute / 1) % 10]);
	lv_img_set_src(face_174_410_34_188086, face_174_410_dial_img_33_188086_group[(minute / 10) % 10]);
	lv_img_set_src(face_174_410_36_352525, face_174_410_dial_img_36_352525_group[((weekday + 6) / 1) % 7]);

#endif
}

void update_weather_174_410(int temp, int icon)
{
#ifdef ENABLE_FACE_174_410
    if (!face_174_410)
    {
        return;
    }

#endif
}

void update_status_174_410(int battery, bool connection){
#ifdef ENABLE_FACE_174_410
    if (!face_174_410)
    {
        return;
    }

#endif
}

void update_activity_174_410(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_174_410
    if (!face_174_410)
    {
        return;
    }
	lv_img_set_src(face_174_410_17_64537, face_174_410_dial_img_14_64537_group[(kcal / 1) % 10]);
	lv_img_set_src(face_174_410_18_64537, face_174_410_dial_img_14_64537_group[(kcal / 10) % 10]);
	lv_img_set_src(face_174_410_19_64537, face_174_410_dial_img_14_64537_group[(kcal / 100) % 10]);
	lv_img_set_src(face_174_410_20_64537, face_174_410_dial_img_14_64537_group[(kcal / 1000) % 10]);
	lv_img_set_src(face_174_410_21_64537, face_174_410_dial_img_14_64537_group[(steps / 1) % 10]);
	lv_img_set_src(face_174_410_22_64537, face_174_410_dial_img_14_64537_group[(steps / 10) % 10]);
	lv_img_set_src(face_174_410_23_64537, face_174_410_dial_img_14_64537_group[(steps / 100) % 10]);
	lv_img_set_src(face_174_410_24_64537, face_174_410_dial_img_14_64537_group[(steps / 1000) % 10]);
	lv_img_set_src(face_174_410_25_64537, face_174_410_dial_img_14_64537_group[(steps / 10000) % 10]);

#endif
}

void update_health_174_410(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_174_410
    if (!face_174_410)
    {
        return;
    }
	lv_img_set_src(face_174_410_14_64537, face_174_410_dial_img_14_64537_group[(bpm / 1) % 10]);
	lv_img_set_src(face_174_410_15_64537, face_174_410_dial_img_14_64537_group[(bpm / 10) % 10]);
	lv_img_set_src(face_174_410_16_64537, face_174_410_dial_img_14_64537_group[(bpm / 100) % 10]);

#endif
}

void update_all_174_410(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_174_410
    update_time_174_410(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_174_410(temp, icon);
    update_status_174_410(battery, connection);
    update_activity_174_410(steps, distance, kcal);
    update_health_174_410(bpm, oxygen);
#endif
}

void update_check_174_410(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_174_410
    if (root != face_174_410)
    {
        return;
    }
    update_time_174_410(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_174_410(temp, icon);
    update_status_174_410(battery, connection);
    update_activity_174_410(steps, distance, kcal);
    update_health_174_410(bpm, oxygen);
#endif
}


