
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: TIX_RESIZED

#ifndef _FACE_TIX_RESIZED_H
#define _FACE_TIX_RESIZED_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"
#include "app_hal.h"

//#define ENABLE_FACE_TIX_RESIZED // (Tix) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_TIX_RESIZED
    extern lv_obj_t *face_tix_resized;
	extern lv_obj_t *face_tix_resized_0_124;
	extern lv_obj_t *face_tix_resized_1_46402;
	extern lv_obj_t *face_tix_resized_2_50918;
	extern lv_obj_t *face_tix_resized_3_97204;
	extern lv_obj_t *face_tix_resized_4_127846;
	extern lv_obj_t *face_tix_resized_5_152184;


	LV_IMG_DECLARE(face_tix_resized_dial_img_0_124_0);
	LV_IMG_DECLARE(face_tix_resized_dial_img_0_124_1);
	LV_IMG_DECLARE(face_tix_resized_dial_img_0_124_2);
	LV_IMG_DECLARE(face_tix_resized_dial_img_0_124_3);
	LV_IMG_DECLARE(face_tix_resized_dial_img_0_124_4);
	LV_IMG_DECLARE(face_tix_resized_dial_img_0_124_5);
	LV_IMG_DECLARE(face_tix_resized_dial_img_0_124_6);
	LV_IMG_DECLARE(face_tix_resized_dial_img_0_124_7);
	LV_IMG_DECLARE(face_tix_resized_dial_img_0_124_8);
	LV_IMG_DECLARE(face_tix_resized_dial_img_0_124_9);
	LV_IMG_DECLARE(face_tix_resized_dial_img_1_46402_0);
	LV_IMG_DECLARE(face_tix_resized_dial_img_1_46402_1);
	LV_IMG_DECLARE(face_tix_resized_dial_img_1_46402_2);
	LV_IMG_DECLARE(face_tix_resized_dial_img_2_50918_0);
	LV_IMG_DECLARE(face_tix_resized_dial_img_2_50918_1);
	LV_IMG_DECLARE(face_tix_resized_dial_img_2_50918_2);
	LV_IMG_DECLARE(face_tix_resized_dial_img_2_50918_3);
	LV_IMG_DECLARE(face_tix_resized_dial_img_2_50918_4);
	LV_IMG_DECLARE(face_tix_resized_dial_img_2_50918_5);
	LV_IMG_DECLARE(face_tix_resized_dial_img_2_50918_6);
	LV_IMG_DECLARE(face_tix_resized_dial_img_2_50918_7);
	LV_IMG_DECLARE(face_tix_resized_dial_img_2_50918_8);
	LV_IMG_DECLARE(face_tix_resized_dial_img_2_50918_9);
	LV_IMG_DECLARE(face_tix_resized_dial_img_3_97204_0);
	LV_IMG_DECLARE(face_tix_resized_dial_img_3_97204_1);
	LV_IMG_DECLARE(face_tix_resized_dial_img_3_97204_2);
	LV_IMG_DECLARE(face_tix_resized_dial_img_3_97204_3);
	LV_IMG_DECLARE(face_tix_resized_dial_img_3_97204_4);
	LV_IMG_DECLARE(face_tix_resized_dial_img_3_97204_5);
	LV_IMG_DECLARE(face_tix_resized_dial_img_3_97204_6);
	LV_IMG_DECLARE(face_tix_resized_dial_img_3_97204_7);
	LV_IMG_DECLARE(face_tix_resized_dial_img_3_97204_8);
	LV_IMG_DECLARE(face_tix_resized_dial_img_3_97204_9);
	LV_IMG_DECLARE(face_tix_resized_dial_img_4_127846_0);
	LV_IMG_DECLARE(face_tix_resized_dial_img_4_127846_1);
	LV_IMG_DECLARE(face_tix_resized_dial_img_4_127846_2);
	LV_IMG_DECLARE(face_tix_resized_dial_img_4_127846_3);
	LV_IMG_DECLARE(face_tix_resized_dial_img_4_127846_4);
	LV_IMG_DECLARE(face_tix_resized_dial_img_4_127846_5);
	LV_IMG_DECLARE(face_tix_resized_dial_img_4_127846_6);
	LV_IMG_DECLARE(face_tix_resized_dial_img_5_152184_0);
	LV_IMG_DECLARE(face_tix_resized_dial_img_5_152184_1);
	LV_IMG_DECLARE(face_tix_resized_dial_img_5_152184_2);
	LV_IMG_DECLARE(face_tix_resized_dial_img_5_152184_3);
	LV_IMG_DECLARE(face_tix_resized_dial_img_5_152184_4);
	LV_IMG_DECLARE(face_tix_resized_dial_img_5_152184_5);
	LV_IMG_DECLARE(face_tix_resized_dial_img_5_152184_6);
	LV_IMG_DECLARE(face_tix_resized_dial_img_preview_0);
	LV_IMG_DECLARE(face_tix_resized_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_tix_resized(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **));
    void update_time_tix_resized(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_tix_resized(int temp, int icon);
    void update_status_tix_resized(int battery, bool connection);
    void update_activity_tix_resized(int steps, int distance, int kcal);
    void update_health_tix_resized(int bpm, int oxygen);
    void update_all_tix_resized(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_tix_resized(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
