
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 2051_410

#include "2051_410.h"

#ifdef ENABLE_FACE_2051_410

lv_obj_t *face_2051_410;
lv_obj_t *face_2051_410_0_184;
lv_obj_t *face_2051_410_1_200770;
lv_obj_t *face_2051_410_2_200770;
lv_obj_t *face_2051_410_3_206022;
lv_obj_t *face_2051_410_4_206022;
lv_obj_t *face_2051_410_5_206022;
lv_obj_t *face_2051_410_6_206022;
lv_obj_t *face_2051_410_8_295420;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif

const lv_img_dsc_t *face_2051_410_dial_img_1_200770_group[] = {
	&face_2051_410_dial_img_1_200770_0,
	&face_2051_410_dial_img_1_200770_1,
	&face_2051_410_dial_img_1_200770_2,
	&face_2051_410_dial_img_1_200770_3,
	&face_2051_410_dial_img_1_200770_4,
	&face_2051_410_dial_img_1_200770_5,
	&face_2051_410_dial_img_1_200770_6,
	&face_2051_410_dial_img_1_200770_7,
	&face_2051_410_dial_img_1_200770_8,
	&face_2051_410_dial_img_1_200770_9,
};
const lv_img_dsc_t *face_2051_410_dial_img_3_206022_group[] = {
	&face_2051_410_dial_img_3_206022_0,
	&face_2051_410_dial_img_3_206022_1,
	&face_2051_410_dial_img_3_206022_2,
	&face_2051_410_dial_img_3_206022_3,
	&face_2051_410_dial_img_3_206022_4,
	&face_2051_410_dial_img_3_206022_5,
	&face_2051_410_dial_img_3_206022_6,
	&face_2051_410_dial_img_3_206022_7,
	&face_2051_410_dial_img_3_206022_8,
	&face_2051_410_dial_img_3_206022_9,
};
const lv_img_dsc_t *face_2051_410_dial_img_7_279554_group[] = {
	&face_2051_410_dial_img_7_279554_0,
	&face_2051_410_dial_img_7_279554_1,
	&face_2051_410_dial_img_7_279554_2,
	&face_2051_410_dial_img_7_279554_3,
	&face_2051_410_dial_img_7_279554_4,
	&face_2051_410_dial_img_7_279554_5,
	&face_2051_410_dial_img_7_279554_6,
};
const lv_img_dsc_t *face_2051_410_dial_img_8_295420_group[] = {
	&face_2051_410_dial_img_8_295420_0,
	&face_2051_410_dial_img_8_295420_1,
	&face_2051_410_dial_img_8_295420_2,
	&face_2051_410_dial_img_8_295420_3,
	&face_2051_410_dial_img_8_295420_4,
	&face_2051_410_dial_img_8_295420_5,
	&face_2051_410_dial_img_8_295420_6,
};




#endif

void init_face_2051_410(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **)){
#ifdef ENABLE_FACE_2051_410
    face_2051_410 = lv_obj_create(NULL);
    lv_obj_clear_flag(face_2051_410, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_2051_410, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_2051_410, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_2051_410, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_2051_410, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_2051_410, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_2051_410, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_2051_410, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_2051_410, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_2051_410_0_184 = lv_img_create(face_2051_410);
    lv_img_set_src(face_2051_410_0_184, &face_2051_410_dial_img_0_184_0);
    lv_obj_set_width(face_2051_410_0_184, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2051_410_0_184, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2051_410_0_184, 0);
    lv_obj_set_y(face_2051_410_0_184, 0);
    lv_obj_add_flag(face_2051_410_0_184, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2051_410_0_184, LV_OBJ_FLAG_SCROLLABLE );

    face_2051_410_1_200770 = lv_img_create(face_2051_410);
    lv_img_set_src(face_2051_410_1_200770, &face_2051_410_dial_img_1_200770_0);
    lv_obj_set_width(face_2051_410_1_200770, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2051_410_1_200770, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2051_410_1_200770, 357);
    lv_obj_set_y(face_2051_410_1_200770, 305);
    lv_obj_add_flag(face_2051_410_1_200770, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2051_410_1_200770, LV_OBJ_FLAG_SCROLLABLE );

    face_2051_410_2_200770 = lv_img_create(face_2051_410);
    lv_img_set_src(face_2051_410_2_200770, &face_2051_410_dial_img_1_200770_0);
    lv_obj_set_width(face_2051_410_2_200770, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2051_410_2_200770, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2051_410_2_200770, 334);
    lv_obj_set_y(face_2051_410_2_200770, 305);
    lv_obj_add_flag(face_2051_410_2_200770, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2051_410_2_200770, LV_OBJ_FLAG_SCROLLABLE );

    face_2051_410_3_206022 = lv_img_create(face_2051_410);
    lv_img_set_src(face_2051_410_3_206022, &face_2051_410_dial_img_3_206022_0);
    lv_obj_set_width(face_2051_410_3_206022, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2051_410_3_206022, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2051_410_3_206022, 312);
    lv_obj_set_y(face_2051_410_3_206022, 58);
    lv_obj_add_flag(face_2051_410_3_206022, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2051_410_3_206022, LV_OBJ_FLAG_SCROLLABLE );

    face_2051_410_4_206022 = lv_img_create(face_2051_410);
    lv_img_set_src(face_2051_410_4_206022, &face_2051_410_dial_img_3_206022_0);
    lv_obj_set_width(face_2051_410_4_206022, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2051_410_4_206022, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2051_410_4_206022, 230);
    lv_obj_set_y(face_2051_410_4_206022, 58);
    lv_obj_add_flag(face_2051_410_4_206022, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2051_410_4_206022, LV_OBJ_FLAG_SCROLLABLE );

    face_2051_410_5_206022 = lv_img_create(face_2051_410);
    lv_img_set_src(face_2051_410_5_206022, &face_2051_410_dial_img_3_206022_0);
    lv_obj_set_width(face_2051_410_5_206022, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2051_410_5_206022, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2051_410_5_206022, 312);
    lv_obj_set_y(face_2051_410_5_206022, 189);
    lv_obj_add_flag(face_2051_410_5_206022, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2051_410_5_206022, LV_OBJ_FLAG_SCROLLABLE );

    face_2051_410_6_206022 = lv_img_create(face_2051_410);
    lv_img_set_src(face_2051_410_6_206022, &face_2051_410_dial_img_3_206022_0);
    lv_obj_set_width(face_2051_410_6_206022, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2051_410_6_206022, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2051_410_6_206022, 230);
    lv_obj_set_y(face_2051_410_6_206022, 189);
    lv_obj_add_flag(face_2051_410_6_206022, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2051_410_6_206022, LV_OBJ_FLAG_SCROLLABLE );

    face_2051_410_8_295420 = lv_img_create(face_2051_410);
    lv_img_set_src(face_2051_410_8_295420, &face_2051_410_dial_img_8_295420_0);
    lv_obj_set_width(face_2051_410_8_295420, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2051_410_8_295420, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2051_410_8_295420, 235);
    lv_obj_set_y(face_2051_410_8_295420, 305);
    lv_obj_add_flag(face_2051_410_8_295420, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2051_410_8_295420, LV_OBJ_FLAG_SCROLLABLE );


    callback("2051", &face_2051_410_dial_img_preview_0, &face_2051_410, NULL);

#endif
}

void update_time_2051_410(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_2051_410
    if (!face_2051_410)
    {
        return;
    }
	lv_img_set_src(face_2051_410_1_200770, face_2051_410_dial_img_1_200770_group[(day / 1) % 10]);
	lv_img_set_src(face_2051_410_2_200770, face_2051_410_dial_img_1_200770_group[(day / 10) % 10]);
	lv_img_set_src(face_2051_410_3_206022, face_2051_410_dial_img_3_206022_group[(hour / 1) % 10]);
	lv_img_set_src(face_2051_410_4_206022, face_2051_410_dial_img_3_206022_group[(hour / 10) % 10]);
	lv_img_set_src(face_2051_410_5_206022, face_2051_410_dial_img_3_206022_group[(minute / 1) % 10]);
	lv_img_set_src(face_2051_410_6_206022, face_2051_410_dial_img_3_206022_group[(minute / 10) % 10]);
	lv_img_set_src(face_2051_410_8_295420, face_2051_410_dial_img_8_295420_group[((weekday + 6) / 1) % 7]);

#endif
}

void update_weather_2051_410(int temp, int icon)
{
#ifdef ENABLE_FACE_2051_410
    if (!face_2051_410)
    {
        return;
    }

#endif
}

void update_status_2051_410(int battery, bool connection){
#ifdef ENABLE_FACE_2051_410
    if (!face_2051_410)
    {
        return;
    }

#endif
}

void update_activity_2051_410(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_2051_410
    if (!face_2051_410)
    {
        return;
    }

#endif
}

void update_health_2051_410(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_2051_410
    if (!face_2051_410)
    {
        return;
    }

#endif
}

void update_all_2051_410(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_2051_410
    update_time_2051_410(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_2051_410(temp, icon);
    update_status_2051_410(battery, connection);
    update_activity_2051_410(steps, distance, kcal);
    update_health_2051_410(bpm, oxygen);
#endif
}

void update_check_2051_410(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_2051_410
    if (root != face_2051_410)
    {
        return;
    }
    update_time_2051_410(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_2051_410(temp, icon);
    update_status_2051_410(battery, connection);
    update_activity_2051_410(steps, distance, kcal);
    update_health_2051_410(bpm, oxygen);
#endif
}


