
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: SIMPLE_360

#ifndef _FACE_SIMPLE_360_H
#define _FACE_SIMPLE_360_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"
#include "app_hal.h"

//#define ENABLE_FACE_SIMPLE_360 // (Simple) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_SIMPLE_360
    extern lv_obj_t *face_simple_360;
	extern lv_obj_t *face_simple_360_0_1276;
	extern lv_obj_t *face_simple_360_2_140074;
	extern lv_obj_t *face_simple_360_11_65535;
	extern lv_obj_t *face_simple_360_12_65535;
	extern lv_obj_t *face_simple_360_13_191064;
	extern lv_obj_t *face_simple_360_14_191064;
	extern lv_obj_t *face_simple_360_15_191064;
	extern lv_obj_t *face_simple_360_16_151204;
	extern lv_obj_t *face_simple_360_17_145716;
	extern lv_obj_t *face_simple_360_18_65535;
	extern lv_obj_t *face_simple_360_19_135620;
	extern lv_obj_t *face_simple_360_20_134154;
	extern lv_obj_t *face_simple_360_21_132698;
	extern lv_obj_t *face_simple_360_22_131342;
	extern lv_obj_t *face_simple_360_23_147294;
	extern lv_obj_t *face_simple_360_24_147294;
	extern lv_obj_t *face_simple_360_25_147294;
	extern lv_obj_t *face_simple_360_26_984;
	extern lv_obj_t *face_simple_360_28_141970;
	extern lv_obj_t *face_simple_360_29_151518;
	extern lv_obj_t *face_simple_360_30_151518;
	extern lv_obj_t *face_simple_360_31_151518;
	extern lv_obj_t *face_simple_360_32_151518;
	extern lv_obj_t *face_simple_360_33_140742;
	extern lv_obj_t *face_simple_360_34_140742;
	extern lv_obj_t *face_simple_360_35_140742;
	extern lv_obj_t *face_simple_360_36_140742;
	extern lv_obj_t *face_simple_360_37_147294;
	extern lv_obj_t *face_simple_360_38_147294;
	extern lv_obj_t *face_simple_360_39_147294;
	extern lv_obj_t *face_simple_360_40_141938;
	extern lv_obj_t *face_simple_360_41_191064;
	extern lv_obj_t *face_simple_360_42_191064;
	extern lv_obj_t *face_simple_360_43_191064;
	extern lv_obj_t *face_simple_360_44_147294;
	extern lv_obj_t *face_simple_360_45_147294;
	extern lv_obj_t *face_simple_360_46_147294;
	extern lv_obj_t *face_simple_360_47_147294;
	extern lv_obj_t *face_simple_360_48_147294;


	LV_IMG_DECLARE(face_simple_360_dial_img_0_1276_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_2_140074_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_3_150530_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_4_149856_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_5_148496_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_6_146652_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_7_149166_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_8_192574_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_9_145048_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_10_146002_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_11_65535_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_13_191064_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_13_191064_1);
	LV_IMG_DECLARE(face_simple_360_dial_img_13_191064_2);
	LV_IMG_DECLARE(face_simple_360_dial_img_13_191064_3);
	LV_IMG_DECLARE(face_simple_360_dial_img_13_191064_4);
	LV_IMG_DECLARE(face_simple_360_dial_img_13_191064_5);
	LV_IMG_DECLARE(face_simple_360_dial_img_13_191064_6);
	LV_IMG_DECLARE(face_simple_360_dial_img_13_191064_7);
	LV_IMG_DECLARE(face_simple_360_dial_img_13_191064_8);
	LV_IMG_DECLARE(face_simple_360_dial_img_13_191064_9);
	LV_IMG_DECLARE(face_simple_360_dial_img_16_151204_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_17_145716_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_19_135620_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_19_135620_1);
	LV_IMG_DECLARE(face_simple_360_dial_img_19_135620_2);
	LV_IMG_DECLARE(face_simple_360_dial_img_19_135620_3);
	LV_IMG_DECLARE(face_simple_360_dial_img_19_135620_4);
	LV_IMG_DECLARE(face_simple_360_dial_img_19_135620_5);
	LV_IMG_DECLARE(face_simple_360_dial_img_19_135620_6);
	LV_IMG_DECLARE(face_simple_360_dial_img_19_135620_7);
	LV_IMG_DECLARE(face_simple_360_dial_img_19_135620_8);
	LV_IMG_DECLARE(face_simple_360_dial_img_19_135620_9);
	LV_IMG_DECLARE(face_simple_360_dial_img_20_134154_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_20_134154_1);
	LV_IMG_DECLARE(face_simple_360_dial_img_20_134154_2);
	LV_IMG_DECLARE(face_simple_360_dial_img_20_134154_3);
	LV_IMG_DECLARE(face_simple_360_dial_img_20_134154_4);
	LV_IMG_DECLARE(face_simple_360_dial_img_20_134154_5);
	LV_IMG_DECLARE(face_simple_360_dial_img_20_134154_6);
	LV_IMG_DECLARE(face_simple_360_dial_img_20_134154_7);
	LV_IMG_DECLARE(face_simple_360_dial_img_20_134154_8);
	LV_IMG_DECLARE(face_simple_360_dial_img_20_134154_9);
	LV_IMG_DECLARE(face_simple_360_dial_img_21_132698_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_21_132698_1);
	LV_IMG_DECLARE(face_simple_360_dial_img_21_132698_2);
	LV_IMG_DECLARE(face_simple_360_dial_img_21_132698_3);
	LV_IMG_DECLARE(face_simple_360_dial_img_21_132698_4);
	LV_IMG_DECLARE(face_simple_360_dial_img_21_132698_5);
	LV_IMG_DECLARE(face_simple_360_dial_img_21_132698_6);
	LV_IMG_DECLARE(face_simple_360_dial_img_21_132698_7);
	LV_IMG_DECLARE(face_simple_360_dial_img_21_132698_8);
	LV_IMG_DECLARE(face_simple_360_dial_img_21_132698_9);
	LV_IMG_DECLARE(face_simple_360_dial_img_22_131342_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_22_131342_1);
	LV_IMG_DECLARE(face_simple_360_dial_img_22_131342_2);
	LV_IMG_DECLARE(face_simple_360_dial_img_22_131342_3);
	LV_IMG_DECLARE(face_simple_360_dial_img_22_131342_4);
	LV_IMG_DECLARE(face_simple_360_dial_img_22_131342_5);
	LV_IMG_DECLARE(face_simple_360_dial_img_22_131342_6);
	LV_IMG_DECLARE(face_simple_360_dial_img_22_131342_7);
	LV_IMG_DECLARE(face_simple_360_dial_img_22_131342_8);
	LV_IMG_DECLARE(face_simple_360_dial_img_22_131342_9);
	LV_IMG_DECLARE(face_simple_360_dial_img_23_147294_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_23_147294_1);
	LV_IMG_DECLARE(face_simple_360_dial_img_23_147294_2);
	LV_IMG_DECLARE(face_simple_360_dial_img_23_147294_3);
	LV_IMG_DECLARE(face_simple_360_dial_img_23_147294_4);
	LV_IMG_DECLARE(face_simple_360_dial_img_23_147294_5);
	LV_IMG_DECLARE(face_simple_360_dial_img_23_147294_6);
	LV_IMG_DECLARE(face_simple_360_dial_img_23_147294_7);
	LV_IMG_DECLARE(face_simple_360_dial_img_23_147294_8);
	LV_IMG_DECLARE(face_simple_360_dial_img_23_147294_9);
	LV_IMG_DECLARE(face_simple_360_dial_img_26_984_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_27_136996_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_27_136996_1);
	LV_IMG_DECLARE(face_simple_360_dial_img_27_136996_2);
	LV_IMG_DECLARE(face_simple_360_dial_img_27_136996_3);
	LV_IMG_DECLARE(face_simple_360_dial_img_27_136996_4);
	LV_IMG_DECLARE(face_simple_360_dial_img_27_136996_5);
	LV_IMG_DECLARE(face_simple_360_dial_img_27_136996_6);
	LV_IMG_DECLARE(face_simple_360_dial_img_28_141970_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_28_141970_1);
	LV_IMG_DECLARE(face_simple_360_dial_img_28_141970_2);
	LV_IMG_DECLARE(face_simple_360_dial_img_28_141970_3);
	LV_IMG_DECLARE(face_simple_360_dial_img_28_141970_4);
	LV_IMG_DECLARE(face_simple_360_dial_img_28_141970_5);
	LV_IMG_DECLARE(face_simple_360_dial_img_28_141970_6);
	LV_IMG_DECLARE(face_simple_360_dial_img_29_151518_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_29_151518_1);
	LV_IMG_DECLARE(face_simple_360_dial_img_29_151518_2);
	LV_IMG_DECLARE(face_simple_360_dial_img_29_151518_3);
	LV_IMG_DECLARE(face_simple_360_dial_img_29_151518_4);
	LV_IMG_DECLARE(face_simple_360_dial_img_29_151518_5);
	LV_IMG_DECLARE(face_simple_360_dial_img_29_151518_6);
	LV_IMG_DECLARE(face_simple_360_dial_img_29_151518_7);
	LV_IMG_DECLARE(face_simple_360_dial_img_29_151518_8);
	LV_IMG_DECLARE(face_simple_360_dial_img_29_151518_9);
	LV_IMG_DECLARE(face_simple_360_dial_img_33_140742_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_33_140742_1);
	LV_IMG_DECLARE(face_simple_360_dial_img_33_140742_2);
	LV_IMG_DECLARE(face_simple_360_dial_img_33_140742_3);
	LV_IMG_DECLARE(face_simple_360_dial_img_33_140742_4);
	LV_IMG_DECLARE(face_simple_360_dial_img_33_140742_5);
	LV_IMG_DECLARE(face_simple_360_dial_img_33_140742_6);
	LV_IMG_DECLARE(face_simple_360_dial_img_33_140742_7);
	LV_IMG_DECLARE(face_simple_360_dial_img_33_140742_8);
	LV_IMG_DECLARE(face_simple_360_dial_img_33_140742_9);
	LV_IMG_DECLARE(face_simple_360_dial_img_40_141938_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_preview_0);
	LV_IMG_DECLARE(face_simple_360_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_simple_360(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **));
    void update_time_simple_360(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_simple_360(int temp, int icon);
    void update_status_simple_360(int battery, bool connection);
    void update_activity_simple_360(int steps, int distance, int kcal);
    void update_health_simple_360(int bpm, int oxygen);
    void update_all_simple_360(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_simple_360(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
