
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: SIMPLE_360

#include "simple_360.h"

#ifdef ENABLE_FACE_SIMPLE_360

lv_obj_t *face_simple_360;
lv_obj_t *face_simple_360_0_1276;
lv_obj_t *face_simple_360_2_140074;
lv_obj_t *face_simple_360_11_65535;
lv_obj_t *face_simple_360_12_65535;
lv_obj_t *face_simple_360_13_191064;
lv_obj_t *face_simple_360_14_191064;
lv_obj_t *face_simple_360_15_191064;
lv_obj_t *face_simple_360_16_151204;
lv_obj_t *face_simple_360_17_145716;
lv_obj_t *face_simple_360_18_65535;
lv_obj_t *face_simple_360_19_135620;
lv_obj_t *face_simple_360_20_134154;
lv_obj_t *face_simple_360_21_132698;
lv_obj_t *face_simple_360_22_131342;
lv_obj_t *face_simple_360_23_147294;
lv_obj_t *face_simple_360_24_147294;
lv_obj_t *face_simple_360_25_147294;
lv_obj_t *face_simple_360_26_984;
lv_obj_t *face_simple_360_28_141970;
lv_obj_t *face_simple_360_29_151518;
lv_obj_t *face_simple_360_30_151518;
lv_obj_t *face_simple_360_31_151518;
lv_obj_t *face_simple_360_32_151518;
lv_obj_t *face_simple_360_33_140742;
lv_obj_t *face_simple_360_34_140742;
lv_obj_t *face_simple_360_35_140742;
lv_obj_t *face_simple_360_36_140742;
lv_obj_t *face_simple_360_37_147294;
lv_obj_t *face_simple_360_38_147294;
lv_obj_t *face_simple_360_39_147294;
lv_obj_t *face_simple_360_40_141938;
lv_obj_t *face_simple_360_41_191064;
lv_obj_t *face_simple_360_42_191064;
lv_obj_t *face_simple_360_43_191064;
lv_obj_t *face_simple_360_44_147294;
lv_obj_t *face_simple_360_45_147294;
lv_obj_t *face_simple_360_46_147294;
lv_obj_t *face_simple_360_47_147294;
lv_obj_t *face_simple_360_48_147294;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif

const lv_img_dsc_t *face_simple_360_dial_img_weather[] = {
	&face_simple_360_dial_img_2_140074_0,
	&face_simple_360_dial_img_3_150530_0,
	&face_simple_360_dial_img_4_149856_0,
	&face_simple_360_dial_img_5_148496_0,
	&face_simple_360_dial_img_6_146652_0,
	&face_simple_360_dial_img_7_149166_0,
	&face_simple_360_dial_img_8_192574_0,
	&face_simple_360_dial_img_9_145048_0,
	&face_simple_360_dial_img_10_146002_0,
};
const lv_img_dsc_t *face_simple_360_dial_img_13_191064_group[] = {
	&face_simple_360_dial_img_13_191064_0,
	&face_simple_360_dial_img_13_191064_1,
	&face_simple_360_dial_img_13_191064_2,
	&face_simple_360_dial_img_13_191064_3,
	&face_simple_360_dial_img_13_191064_4,
	&face_simple_360_dial_img_13_191064_5,
	&face_simple_360_dial_img_13_191064_6,
	&face_simple_360_dial_img_13_191064_7,
	&face_simple_360_dial_img_13_191064_8,
	&face_simple_360_dial_img_13_191064_9,
};
const lv_img_dsc_t *face_simple_360_dial_img_19_135620_group[] = {
	&face_simple_360_dial_img_19_135620_0,
	&face_simple_360_dial_img_19_135620_1,
	&face_simple_360_dial_img_19_135620_2,
	&face_simple_360_dial_img_19_135620_3,
	&face_simple_360_dial_img_19_135620_4,
	&face_simple_360_dial_img_19_135620_5,
	&face_simple_360_dial_img_19_135620_6,
	&face_simple_360_dial_img_19_135620_7,
	&face_simple_360_dial_img_19_135620_8,
	&face_simple_360_dial_img_19_135620_9,
};
const lv_img_dsc_t *face_simple_360_dial_img_20_134154_group[] = {
	&face_simple_360_dial_img_20_134154_0,
	&face_simple_360_dial_img_20_134154_1,
	&face_simple_360_dial_img_20_134154_2,
	&face_simple_360_dial_img_20_134154_3,
	&face_simple_360_dial_img_20_134154_4,
	&face_simple_360_dial_img_20_134154_5,
	&face_simple_360_dial_img_20_134154_6,
	&face_simple_360_dial_img_20_134154_7,
	&face_simple_360_dial_img_20_134154_8,
	&face_simple_360_dial_img_20_134154_9,
};
const lv_img_dsc_t *face_simple_360_dial_img_21_132698_group[] = {
	&face_simple_360_dial_img_21_132698_0,
	&face_simple_360_dial_img_21_132698_1,
	&face_simple_360_dial_img_21_132698_2,
	&face_simple_360_dial_img_21_132698_3,
	&face_simple_360_dial_img_21_132698_4,
	&face_simple_360_dial_img_21_132698_5,
	&face_simple_360_dial_img_21_132698_6,
	&face_simple_360_dial_img_21_132698_7,
	&face_simple_360_dial_img_21_132698_8,
	&face_simple_360_dial_img_21_132698_9,
};
const lv_img_dsc_t *face_simple_360_dial_img_22_131342_group[] = {
	&face_simple_360_dial_img_22_131342_0,
	&face_simple_360_dial_img_22_131342_1,
	&face_simple_360_dial_img_22_131342_2,
	&face_simple_360_dial_img_22_131342_3,
	&face_simple_360_dial_img_22_131342_4,
	&face_simple_360_dial_img_22_131342_5,
	&face_simple_360_dial_img_22_131342_6,
	&face_simple_360_dial_img_22_131342_7,
	&face_simple_360_dial_img_22_131342_8,
	&face_simple_360_dial_img_22_131342_9,
};
const lv_img_dsc_t *face_simple_360_dial_img_23_147294_group[] = {
	&face_simple_360_dial_img_23_147294_0,
	&face_simple_360_dial_img_23_147294_1,
	&face_simple_360_dial_img_23_147294_2,
	&face_simple_360_dial_img_23_147294_3,
	&face_simple_360_dial_img_23_147294_4,
	&face_simple_360_dial_img_23_147294_5,
	&face_simple_360_dial_img_23_147294_6,
	&face_simple_360_dial_img_23_147294_7,
	&face_simple_360_dial_img_23_147294_8,
	&face_simple_360_dial_img_23_147294_9,
};
const lv_img_dsc_t *face_simple_360_dial_img_27_136996_group[] = {
	&face_simple_360_dial_img_27_136996_0,
	&face_simple_360_dial_img_27_136996_1,
	&face_simple_360_dial_img_27_136996_2,
	&face_simple_360_dial_img_27_136996_3,
	&face_simple_360_dial_img_27_136996_4,
	&face_simple_360_dial_img_27_136996_5,
	&face_simple_360_dial_img_27_136996_6,
};
const lv_img_dsc_t *face_simple_360_dial_img_28_141970_group[] = {
	&face_simple_360_dial_img_28_141970_0,
	&face_simple_360_dial_img_28_141970_1,
	&face_simple_360_dial_img_28_141970_2,
	&face_simple_360_dial_img_28_141970_3,
	&face_simple_360_dial_img_28_141970_4,
	&face_simple_360_dial_img_28_141970_5,
	&face_simple_360_dial_img_28_141970_6,
};
const lv_img_dsc_t *face_simple_360_dial_img_29_151518_group[] = {
	&face_simple_360_dial_img_29_151518_0,
	&face_simple_360_dial_img_29_151518_1,
	&face_simple_360_dial_img_29_151518_2,
	&face_simple_360_dial_img_29_151518_3,
	&face_simple_360_dial_img_29_151518_4,
	&face_simple_360_dial_img_29_151518_5,
	&face_simple_360_dial_img_29_151518_6,
	&face_simple_360_dial_img_29_151518_7,
	&face_simple_360_dial_img_29_151518_8,
	&face_simple_360_dial_img_29_151518_9,
};
const lv_img_dsc_t *face_simple_360_dial_img_33_140742_group[] = {
	&face_simple_360_dial_img_33_140742_0,
	&face_simple_360_dial_img_33_140742_1,
	&face_simple_360_dial_img_33_140742_2,
	&face_simple_360_dial_img_33_140742_3,
	&face_simple_360_dial_img_33_140742_4,
	&face_simple_360_dial_img_33_140742_5,
	&face_simple_360_dial_img_33_140742_6,
	&face_simple_360_dial_img_33_140742_7,
	&face_simple_360_dial_img_33_140742_8,
	&face_simple_360_dial_img_33_140742_9,
};




#endif

void init_face_simple_360(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **)){
#ifdef ENABLE_FACE_SIMPLE_360
    face_simple_360 = lv_obj_create(NULL);
    lv_obj_clear_flag(face_simple_360, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_simple_360, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_simple_360, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_simple_360, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_simple_360, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_simple_360, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_simple_360, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_simple_360, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_simple_360, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_simple_360_0_1276 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_0_1276, &face_simple_360_dial_img_0_1276_0);
    lv_obj_set_width(face_simple_360_0_1276, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_0_1276, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_0_1276, 0);
    lv_obj_set_y(face_simple_360_0_1276, 0);
    lv_obj_add_flag(face_simple_360_0_1276, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_0_1276, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_2_140074 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_2_140074, &face_simple_360_dial_img_2_140074_0);
    lv_obj_set_width(face_simple_360_2_140074, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_2_140074, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_2_140074, 145);
    lv_obj_set_y(face_simple_360_2_140074, 62);
    lv_obj_add_flag(face_simple_360_2_140074, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_2_140074, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_11_65535 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_11_65535, &face_simple_360_dial_img_11_65535_0);
    lv_obj_set_width(face_simple_360_11_65535, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_11_65535, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_11_65535, 188);
    lv_obj_set_y(face_simple_360_11_65535, 73);
    lv_obj_add_flag(face_simple_360_11_65535, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_11_65535, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_12_65535 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_12_65535, &face_simple_360_dial_img_11_65535_0);
    lv_obj_set_width(face_simple_360_12_65535, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_12_65535, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_12_65535, 177);
    lv_obj_set_y(face_simple_360_12_65535, 73);
    lv_obj_add_flag(face_simple_360_12_65535, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_12_65535, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_13_191064 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_13_191064, &face_simple_360_dial_img_13_191064_0);
    lv_obj_set_width(face_simple_360_13_191064, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_13_191064, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_13_191064, 191);
    lv_obj_set_y(face_simple_360_13_191064, 67);
    lv_obj_add_flag(face_simple_360_13_191064, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_13_191064, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_14_191064 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_14_191064, &face_simple_360_dial_img_13_191064_0);
    lv_obj_set_width(face_simple_360_14_191064, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_14_191064, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_14_191064, 181);
    lv_obj_set_y(face_simple_360_14_191064, 67);
    lv_obj_add_flag(face_simple_360_14_191064, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_14_191064, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_15_191064 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_15_191064, &face_simple_360_dial_img_13_191064_0);
    lv_obj_set_width(face_simple_360_15_191064, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_15_191064, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_15_191064, 171);
    lv_obj_set_y(face_simple_360_15_191064, 67);
    lv_obj_add_flag(face_simple_360_15_191064, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_15_191064, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_16_151204 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_16_151204, &face_simple_360_dial_img_16_151204_0);
    lv_obj_set_width(face_simple_360_16_151204, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_16_151204, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_16_151204, 203);
    lv_obj_set_y(face_simple_360_16_151204, 67);
    lv_obj_add_flag(face_simple_360_16_151204, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_16_151204, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_17_145716 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_17_145716, &face_simple_360_dial_img_17_145716_0);
    lv_obj_set_width(face_simple_360_17_145716, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_17_145716, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_17_145716, 203);
    lv_obj_set_y(face_simple_360_17_145716, 67);
    lv_obj_add_flag(face_simple_360_17_145716, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_17_145716, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_18_65535 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_18_65535, &face_simple_360_dial_img_11_65535_0);
    lv_obj_set_width(face_simple_360_18_65535, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_18_65535, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_18_65535, 172);
    lv_obj_set_y(face_simple_360_18_65535, 73);
    lv_obj_add_flag(face_simple_360_18_65535, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_18_65535, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_19_135620 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_19_135620, &face_simple_360_dial_img_19_135620_0);
    lv_obj_set_width(face_simple_360_19_135620, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_19_135620, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_19_135620, 117);
    lv_obj_set_y(face_simple_360_19_135620, 69);
    lv_obj_add_flag(face_simple_360_19_135620, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_19_135620, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_20_134154 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_20_134154, &face_simple_360_dial_img_20_134154_0);
    lv_obj_set_width(face_simple_360_20_134154, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_20_134154, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_20_134154, 108);
    lv_obj_set_y(face_simple_360_20_134154, 69);
    lv_obj_add_flag(face_simple_360_20_134154, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_20_134154, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_21_132698 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_21_132698, &face_simple_360_dial_img_21_132698_0);
    lv_obj_set_width(face_simple_360_21_132698, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_21_132698, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_21_132698, 99);
    lv_obj_set_y(face_simple_360_21_132698, 69);
    lv_obj_add_flag(face_simple_360_21_132698, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_21_132698, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_22_131342 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_22_131342, &face_simple_360_dial_img_22_131342_0);
    lv_obj_set_width(face_simple_360_22_131342, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_22_131342, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_22_131342, 90);
    lv_obj_set_y(face_simple_360_22_131342, 69);
    lv_obj_add_flag(face_simple_360_22_131342, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_22_131342, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_23_147294 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_23_147294, &face_simple_360_dial_img_23_147294_0);
    lv_obj_set_width(face_simple_360_23_147294, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_23_147294, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_23_147294, 267);
    lv_obj_set_y(face_simple_360_23_147294, 68);
    lv_obj_add_flag(face_simple_360_23_147294, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_23_147294, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_24_147294 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_24_147294, &face_simple_360_dial_img_23_147294_0);
    lv_obj_set_width(face_simple_360_24_147294, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_24_147294, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_24_147294, 258);
    lv_obj_set_y(face_simple_360_24_147294, 68);
    lv_obj_add_flag(face_simple_360_24_147294, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_24_147294, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_25_147294 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_25_147294, &face_simple_360_dial_img_23_147294_0);
    lv_obj_set_width(face_simple_360_25_147294, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_25_147294, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_25_147294, 249);
    lv_obj_set_y(face_simple_360_25_147294, 68);
    lv_obj_add_flag(face_simple_360_25_147294, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_25_147294, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_26_984 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_26_984, &face_simple_360_dial_img_26_984_0);
    lv_obj_set_width(face_simple_360_26_984, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_26_984, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_26_984, 280);
    lv_obj_set_y(face_simple_360_26_984, 68);
    lv_obj_add_flag(face_simple_360_26_984, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_26_984, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_28_141970 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_28_141970, &face_simple_360_dial_img_28_141970_0);
    lv_obj_set_width(face_simple_360_28_141970, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_28_141970, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_28_141970, 217);
    lv_obj_set_y(face_simple_360_28_141970, 119);
    lv_obj_add_flag(face_simple_360_28_141970, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_28_141970, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_29_151518 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_29_151518, &face_simple_360_dial_img_29_151518_0);
    lv_obj_set_width(face_simple_360_29_151518, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_29_151518, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_29_151518, 257);
    lv_obj_set_y(face_simple_360_29_151518, 143);
    lv_obj_add_flag(face_simple_360_29_151518, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_29_151518, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_30_151518 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_30_151518, &face_simple_360_dial_img_29_151518_0);
    lv_obj_set_width(face_simple_360_30_151518, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_30_151518, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_30_151518, 202);
    lv_obj_set_y(face_simple_360_30_151518, 143);
    lv_obj_add_flag(face_simple_360_30_151518, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_30_151518, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_31_151518 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_31_151518, &face_simple_360_dial_img_29_151518_0);
    lv_obj_set_width(face_simple_360_31_151518, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_31_151518, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_31_151518, 103);
    lv_obj_set_y(face_simple_360_31_151518, 143);
    lv_obj_add_flag(face_simple_360_31_151518, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_31_151518, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_32_151518 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_32_151518, &face_simple_360_dial_img_29_151518_0);
    lv_obj_set_width(face_simple_360_32_151518, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_32_151518, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_32_151518, 48);
    lv_obj_set_y(face_simple_360_32_151518, 143);
    lv_obj_add_flag(face_simple_360_32_151518, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_32_151518, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_33_140742 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_33_140742, &face_simple_360_dial_img_33_140742_0);
    lv_obj_set_width(face_simple_360_33_140742, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_33_140742, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_33_140742, 276);
    lv_obj_set_y(face_simple_360_33_140742, 119);
    lv_obj_add_flag(face_simple_360_33_140742, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_33_140742, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_34_140742 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_34_140742, &face_simple_360_dial_img_33_140742_0);
    lv_obj_set_width(face_simple_360_34_140742, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_34_140742, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_34_140742, 266);
    lv_obj_set_y(face_simple_360_34_140742, 119);
    lv_obj_add_flag(face_simple_360_34_140742, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_34_140742, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_35_140742 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_35_140742, &face_simple_360_dial_img_33_140742_0);
    lv_obj_set_width(face_simple_360_35_140742, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_35_140742, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_35_140742, 308);
    lv_obj_set_y(face_simple_360_35_140742, 119);
    lv_obj_add_flag(face_simple_360_35_140742, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_35_140742, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_36_140742 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_36_140742, &face_simple_360_dial_img_33_140742_0);
    lv_obj_set_width(face_simple_360_36_140742, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_36_140742, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_36_140742, 298);
    lv_obj_set_y(face_simple_360_36_140742, 119);
    lv_obj_add_flag(face_simple_360_36_140742, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_36_140742, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_37_147294 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_37_147294, &face_simple_360_dial_img_23_147294_0);
    lv_obj_set_width(face_simple_360_37_147294, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_37_147294, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_37_147294, 113);
    lv_obj_set_y(face_simple_360_37_147294, 281);
    lv_obj_add_flag(face_simple_360_37_147294, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_37_147294, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_38_147294 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_38_147294, &face_simple_360_dial_img_23_147294_0);
    lv_obj_set_width(face_simple_360_38_147294, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_38_147294, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_38_147294, 104);
    lv_obj_set_y(face_simple_360_38_147294, 281);
    lv_obj_add_flag(face_simple_360_38_147294, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_38_147294, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_39_147294 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_39_147294, &face_simple_360_dial_img_23_147294_0);
    lv_obj_set_width(face_simple_360_39_147294, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_39_147294, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_39_147294, 92);
    lv_obj_set_y(face_simple_360_39_147294, 281);
    lv_obj_add_flag(face_simple_360_39_147294, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_39_147294, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_40_141938 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_40_141938, &face_simple_360_dial_img_40_141938_0);
    lv_obj_set_width(face_simple_360_40_141938, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_40_141938, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_40_141938, 101);
    lv_obj_set_y(face_simple_360_40_141938, 281);
    lv_obj_add_flag(face_simple_360_40_141938, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_40_141938, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_41_191064 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_41_191064, &face_simple_360_dial_img_13_191064_0);
    lv_obj_set_width(face_simple_360_41_191064, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_41_191064, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_41_191064, 201);
    lv_obj_set_y(face_simple_360_41_191064, 279);
    lv_obj_add_flag(face_simple_360_41_191064, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_41_191064, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_42_191064 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_42_191064, &face_simple_360_dial_img_13_191064_0);
    lv_obj_set_width(face_simple_360_42_191064, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_42_191064, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_42_191064, 191);
    lv_obj_set_y(face_simple_360_42_191064, 279);
    lv_obj_add_flag(face_simple_360_42_191064, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_42_191064, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_43_191064 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_43_191064, &face_simple_360_dial_img_13_191064_0);
    lv_obj_set_width(face_simple_360_43_191064, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_43_191064, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_43_191064, 181);
    lv_obj_set_y(face_simple_360_43_191064, 279);
    lv_obj_add_flag(face_simple_360_43_191064, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_43_191064, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_44_147294 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_44_147294, &face_simple_360_dial_img_23_147294_0);
    lv_obj_set_width(face_simple_360_44_147294, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_44_147294, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_44_147294, 286);
    lv_obj_set_y(face_simple_360_44_147294, 281);
    lv_obj_add_flag(face_simple_360_44_147294, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_44_147294, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_45_147294 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_45_147294, &face_simple_360_dial_img_23_147294_0);
    lv_obj_set_width(face_simple_360_45_147294, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_45_147294, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_45_147294, 277);
    lv_obj_set_y(face_simple_360_45_147294, 281);
    lv_obj_add_flag(face_simple_360_45_147294, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_45_147294, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_46_147294 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_46_147294, &face_simple_360_dial_img_23_147294_0);
    lv_obj_set_width(face_simple_360_46_147294, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_46_147294, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_46_147294, 268);
    lv_obj_set_y(face_simple_360_46_147294, 281);
    lv_obj_add_flag(face_simple_360_46_147294, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_46_147294, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_47_147294 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_47_147294, &face_simple_360_dial_img_23_147294_0);
    lv_obj_set_width(face_simple_360_47_147294, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_47_147294, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_47_147294, 259);
    lv_obj_set_y(face_simple_360_47_147294, 281);
    lv_obj_add_flag(face_simple_360_47_147294, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_47_147294, LV_OBJ_FLAG_SCROLLABLE );

    face_simple_360_48_147294 = lv_img_create(face_simple_360);
    lv_img_set_src(face_simple_360_48_147294, &face_simple_360_dial_img_23_147294_0);
    lv_obj_set_width(face_simple_360_48_147294, LV_SIZE_CONTENT);
    lv_obj_set_height(face_simple_360_48_147294, LV_SIZE_CONTENT);
    lv_obj_set_x(face_simple_360_48_147294, 250);
    lv_obj_set_y(face_simple_360_48_147294, 281);
    lv_obj_add_flag(face_simple_360_48_147294, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_simple_360_48_147294, LV_OBJ_FLAG_SCROLLABLE );


    callback("Simple", &face_simple_360_dial_img_preview_0, &face_simple_360, NULL);

#endif
}

void update_time_simple_360(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_SIMPLE_360
    if (!face_simple_360)
    {
        return;
    }
	lv_img_set_src(face_simple_360_28_141970, face_simple_360_dial_img_28_141970_group[((weekday + 6) / 1) % 7]);
	lv_img_set_src(face_simple_360_29_151518, face_simple_360_dial_img_29_151518_group[(minute / 1) % 10]);
	lv_img_set_src(face_simple_360_30_151518, face_simple_360_dial_img_29_151518_group[(minute / 10) % 10]);
	lv_img_set_src(face_simple_360_31_151518, face_simple_360_dial_img_29_151518_group[(hour / 1) % 10]);
	lv_img_set_src(face_simple_360_32_151518, face_simple_360_dial_img_29_151518_group[(hour / 10) % 10]);
	lv_img_set_src(face_simple_360_33_140742, face_simple_360_dial_img_33_140742_group[(day / 1) % 10]);
	lv_img_set_src(face_simple_360_34_140742, face_simple_360_dial_img_33_140742_group[(day / 10) % 10]);
	lv_img_set_src(face_simple_360_35_140742, face_simple_360_dial_img_33_140742_group[(month / 1) % 10]);
	lv_img_set_src(face_simple_360_36_140742, face_simple_360_dial_img_33_140742_group[(month / 10) % 10]);

#endif
}

void update_weather_simple_360(int temp, int icon)
{
#ifdef ENABLE_FACE_SIMPLE_360
    if (!face_simple_360)
    {
        return;
    }
	lv_img_set_src(face_simple_360_2_140074, face_simple_360_dial_img_weather[icon % 8]);

#endif
}

void update_status_simple_360(int battery, bool connection){
#ifdef ENABLE_FACE_SIMPLE_360
    if (!face_simple_360)
    {
        return;
    }
	lv_img_set_src(face_simple_360_23_147294, face_simple_360_dial_img_23_147294_group[(battery / 1) % 10]);
	lv_img_set_src(face_simple_360_24_147294, face_simple_360_dial_img_23_147294_group[(battery / 10) % 10]);
	lv_img_set_src(face_simple_360_25_147294, face_simple_360_dial_img_23_147294_group[(battery / 100) % 10]);
	if (battery < 100)
	{
		lv_obj_add_flag(face_simple_360_25_147294, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_simple_360_25_147294, LV_OBJ_FLAG_HIDDEN);
	}

#endif
}

void update_activity_simple_360(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_SIMPLE_360
    if (!face_simple_360)
    {
        return;
    }
	lv_img_set_src(face_simple_360_19_135620, face_simple_360_dial_img_19_135620_group[(kcal / 1) % 10]);
	lv_img_set_src(face_simple_360_20_134154, face_simple_360_dial_img_20_134154_group[(kcal / 10) % 10]);
	lv_img_set_src(face_simple_360_21_132698, face_simple_360_dial_img_21_132698_group[(kcal / 100) % 10]);
	lv_img_set_src(face_simple_360_22_131342, face_simple_360_dial_img_22_131342_group[(kcal / 1000) % 10]);
	lv_img_set_src(face_simple_360_37_147294, face_simple_360_dial_img_23_147294_group[(distance / 1) % 10]);
	lv_img_set_src(face_simple_360_38_147294, face_simple_360_dial_img_23_147294_group[(distance / 10) % 10]);
	lv_img_set_src(face_simple_360_39_147294, face_simple_360_dial_img_23_147294_group[(distance / 100) % 10]);
	lv_img_set_src(face_simple_360_44_147294, face_simple_360_dial_img_23_147294_group[(steps / 1) % 10]);
	lv_img_set_src(face_simple_360_45_147294, face_simple_360_dial_img_23_147294_group[(steps / 10) % 10]);
	lv_img_set_src(face_simple_360_46_147294, face_simple_360_dial_img_23_147294_group[(steps / 100) % 10]);
	lv_img_set_src(face_simple_360_47_147294, face_simple_360_dial_img_23_147294_group[(steps / 1000) % 10]);
	lv_img_set_src(face_simple_360_48_147294, face_simple_360_dial_img_23_147294_group[(steps / 10000) % 10]);

#endif
}

void update_health_simple_360(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_SIMPLE_360
    if (!face_simple_360)
    {
        return;
    }
	lv_img_set_src(face_simple_360_41_191064, face_simple_360_dial_img_13_191064_group[(bpm / 1) % 10]);
	lv_img_set_src(face_simple_360_42_191064, face_simple_360_dial_img_13_191064_group[(bpm / 10) % 10]);
	lv_img_set_src(face_simple_360_43_191064, face_simple_360_dial_img_13_191064_group[(bpm / 100) % 10]);

#endif
}

void update_all_simple_360(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_SIMPLE_360
    update_time_simple_360(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_simple_360(temp, icon);
    update_status_simple_360(battery, connection);
    update_activity_simple_360(steps, distance, kcal);
    update_health_simple_360(bpm, oxygen);
#endif
}

void update_check_simple_360(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_SIMPLE_360
    if (root != face_simple_360)
    {
        return;
    }
    update_time_simple_360(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_simple_360(temp, icon);
    update_status_simple_360(battery, connection);
    update_activity_simple_360(steps, distance, kcal);
    update_health_simple_360(bpm, oxygen);
#endif
}


