
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: WFB_RESIZED

#ifndef _FACE_WFB_RESIZED_H
#define _FACE_WFB_RESIZED_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"
#include "app_hal.h"

//#define ENABLE_FACE_WFB_RESIZED // (WFB) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_WFB_RESIZED
    extern lv_obj_t *face_wfb_resized;
	extern lv_obj_t *face_wfb_resized_0_1324;
	extern lv_obj_t *face_wfb_resized_3_61216;
	extern lv_obj_t *face_wfb_resized_4_62823;
	extern lv_obj_t *face_wfb_resized_5_62823;
	extern lv_obj_t *face_wfb_resized_6_62823;
	extern lv_obj_t *face_wfb_resized_7_62823;
	extern lv_obj_t *face_wfb_resized_8_63485;
	extern lv_obj_t *face_wfb_resized_9_63485;
	extern lv_obj_t *face_wfb_resized_10_63485;
	extern lv_obj_t *face_wfb_resized_11_63485;
	extern lv_obj_t *face_wfb_resized_12_63485;
	extern lv_obj_t *face_wfb_resized_13_63485;
	extern lv_obj_t *face_wfb_resized_14_66037;
	extern lv_obj_t *face_wfb_resized_15_66150;
	extern lv_obj_t *face_wfb_resized_16_66150;
	extern lv_obj_t *face_wfb_resized_17_66150;
	extern lv_obj_t *face_wfb_resized_22_62823;
	extern lv_obj_t *face_wfb_resized_23_62823;
	extern lv_obj_t *face_wfb_resized_24_62823;
	extern lv_obj_t *face_wfb_resized_25_62823;
	extern lv_obj_t *face_wfb_resized_26_66902;
	extern lv_obj_t *face_wfb_resized_27_62823;
	extern lv_obj_t *face_wfb_resized_28_62823;
	extern lv_obj_t *face_wfb_resized_29_62823;
	extern lv_obj_t *face_wfb_resized_30_62823;
	extern lv_obj_t *face_wfb_resized_31_66906;
	extern lv_obj_t *face_wfb_resized_32_66973;
	extern lv_obj_t *face_wfb_resized_35_62823;
	extern lv_obj_t *face_wfb_resized_36_62823;
	extern lv_obj_t *face_wfb_resized_37_62823;
	extern lv_obj_t *face_wfb_resized_38_62823;
	extern lv_obj_t *face_wfb_resized_39_62823;
	extern lv_obj_t *face_wfb_resized_40_62823;
	extern lv_obj_t *face_wfb_resized_41_62823;
	extern lv_obj_t *face_wfb_resized_42_62823;
	extern lv_obj_t *face_wfb_resized_43_62823;
	extern lv_obj_t *face_wfb_resized_44_62823;
	extern lv_obj_t *face_wfb_resized_45_62823;
	extern lv_obj_t *face_wfb_resized_46_62823;
	extern lv_obj_t *face_wfb_resized_48_67215;


	LV_IMG_DECLARE(face_wfb_resized_dial_img_0_1324_0);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_2_59434_0);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_2_59434_1);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_2_59434_2);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_2_59434_3);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_2_59434_4);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_2_59434_5);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_2_59434_6);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_3_61216_0);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_3_61216_1);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_3_61216_2);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_3_61216_3);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_3_61216_4);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_3_61216_5);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_3_61216_6);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_4_62823_0);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_4_62823_1);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_4_62823_2);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_4_62823_3);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_4_62823_4);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_4_62823_5);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_4_62823_6);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_4_62823_7);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_4_62823_8);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_4_62823_9);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_8_63485_0);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_8_63485_1);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_8_63485_2);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_8_63485_3);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_8_63485_4);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_8_63485_5);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_8_63485_6);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_8_63485_7);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_8_63485_8);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_8_63485_9);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_14_66037_0);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_15_66150_0);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_15_66150_1);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_15_66150_2);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_15_66150_3);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_15_66150_4);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_15_66150_5);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_15_66150_6);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_15_66150_7);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_15_66150_8);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_15_66150_9);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_26_66902_0);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_31_66906_0);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_32_66973_0);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_33_67051_0);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_48_67215_0);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_49_67959_0);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_50_68691_0);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_51_69407_0);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_52_70069_0);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_53_70725_0);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_54_71509_0);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_55_72135_0);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_56_72739_0);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_preview_0);
	LV_IMG_DECLARE(face_wfb_resized_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_wfb_resized(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **));
    void update_time_wfb_resized(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_wfb_resized(int temp, int icon);
    void update_status_wfb_resized(int battery, bool connection);
    void update_activity_wfb_resized(int steps, int distance, int kcal);
    void update_health_wfb_resized(int bpm, int oxygen);
    void update_all_wfb_resized(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_wfb_resized(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
