
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 79_2_DIAL

#include "79_2_dial.h"

#ifdef ENABLE_FACE_79_2_DIAL

lv_obj_t *face_79_2_dial;
lv_obj_t *face_79_2_dial_0_404;
lv_obj_t *face_79_2_dial_1_59582;
lv_obj_t *face_79_2_dial_2_59582;
lv_obj_t *face_79_2_dial_3_123330;
lv_obj_t *face_79_2_dial_4_123330;
lv_obj_t *face_79_2_dial_5_58512;
lv_obj_t *face_79_2_dial_6_58512;
lv_obj_t *face_79_2_dial_7_58512;
lv_obj_t *face_79_2_dial_8_58512;
lv_obj_t *face_79_2_dial_9_59456;
lv_obj_t *face_79_2_dial_10_58512;
lv_obj_t *face_79_2_dial_11_58512;
lv_obj_t *face_79_2_dial_12_58512;
lv_obj_t *face_79_2_dial_13_58512;
lv_obj_t *face_79_2_dial_14_58512;
lv_obj_t *face_79_2_dial_15_58512;
lv_obj_t *face_79_2_dial_16_58512;
lv_obj_t *face_79_2_dial_17_58512;
lv_obj_t *face_79_2_dial_19_144206;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif


const lv_img_dsc_t *face_79_2_dial_dial_img_1_59582_group[] = {
	&face_79_2_dial_dial_img_1_59582_0,
	&face_79_2_dial_dial_img_1_59582_1,
	&face_79_2_dial_dial_img_1_59582_2,
	&face_79_2_dial_dial_img_1_59582_3,
	&face_79_2_dial_dial_img_1_59582_4,
	&face_79_2_dial_dial_img_1_59582_5,
	&face_79_2_dial_dial_img_1_59582_6,
	&face_79_2_dial_dial_img_1_59582_7,
	&face_79_2_dial_dial_img_1_59582_8,
	&face_79_2_dial_dial_img_1_59582_9,
};
const lv_img_dsc_t *face_79_2_dial_dial_img_3_123330_group[] = {
	&face_79_2_dial_dial_img_3_123330_0,
	&face_79_2_dial_dial_img_3_123330_1,
	&face_79_2_dial_dial_img_3_123330_2,
	&face_79_2_dial_dial_img_3_123330_3,
	&face_79_2_dial_dial_img_3_123330_4,
	&face_79_2_dial_dial_img_3_123330_5,
	&face_79_2_dial_dial_img_3_123330_6,
	&face_79_2_dial_dial_img_3_123330_7,
	&face_79_2_dial_dial_img_3_123330_8,
	&face_79_2_dial_dial_img_3_123330_9,
};
const lv_img_dsc_t *face_79_2_dial_dial_img_5_58512_group[] = {
	&face_79_2_dial_dial_img_5_58512_0,
	&face_79_2_dial_dial_img_5_58512_1,
	&face_79_2_dial_dial_img_5_58512_2,
	&face_79_2_dial_dial_img_5_58512_3,
	&face_79_2_dial_dial_img_5_58512_4,
	&face_79_2_dial_dial_img_5_58512_5,
	&face_79_2_dial_dial_img_5_58512_6,
	&face_79_2_dial_dial_img_5_58512_7,
	&face_79_2_dial_dial_img_5_58512_8,
	&face_79_2_dial_dial_img_5_58512_9,
};
const lv_img_dsc_t *face_79_2_dial_dial_img_18_138796_group[] = {
	&face_79_2_dial_dial_img_18_138796_0,
	&face_79_2_dial_dial_img_18_138796_1,
	&face_79_2_dial_dial_img_18_138796_2,
	&face_79_2_dial_dial_img_18_138796_3,
	&face_79_2_dial_dial_img_18_138796_4,
	&face_79_2_dial_dial_img_18_138796_5,
	&face_79_2_dial_dial_img_18_138796_6,
};
const lv_img_dsc_t *face_79_2_dial_dial_img_19_144206_group[] = {
	&face_79_2_dial_dial_img_19_144206_0,
	&face_79_2_dial_dial_img_19_144206_1,
	&face_79_2_dial_dial_img_19_144206_2,
	&face_79_2_dial_dial_img_19_144206_3,
	&face_79_2_dial_dial_img_19_144206_4,
	&face_79_2_dial_dial_img_19_144206_5,
	&face_79_2_dial_dial_img_19_144206_6,
};


#endif

void init_face_79_2_dial(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **)){
#ifdef ENABLE_FACE_79_2_DIAL
    face_79_2_dial = lv_obj_create(NULL);
    lv_obj_clear_flag(face_79_2_dial, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_79_2_dial, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_79_2_dial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_79_2_dial, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_79_2_dial, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_79_2_dial, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_79_2_dial, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_79_2_dial, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_79_2_dial, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_79_2_dial_0_404 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_0_404, &face_79_2_dial_dial_img_0_404_0);
    lv_obj_set_width(face_79_2_dial_0_404, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_0_404, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_0_404, 0);
    lv_obj_set_y(face_79_2_dial_0_404, 0);
    lv_obj_add_flag(face_79_2_dial_0_404, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_dial_0_404, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_dial_1_59582 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_1_59582, &face_79_2_dial_dial_img_1_59582_0);
    lv_obj_set_width(face_79_2_dial_1_59582, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_1_59582, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_1_59582, 82);
    lv_obj_set_y(face_79_2_dial_1_59582, 69);
    lv_obj_add_flag(face_79_2_dial_1_59582, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_dial_1_59582, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_dial_2_59582 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_2_59582, &face_79_2_dial_dial_img_1_59582_0);
    lv_obj_set_width(face_79_2_dial_2_59582, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_2_59582, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_2_59582, 14);
    lv_obj_set_y(face_79_2_dial_2_59582, 69);
    lv_obj_add_flag(face_79_2_dial_2_59582, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_dial_2_59582, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_dial_3_123330 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_3_123330, &face_79_2_dial_dial_img_3_123330_0);
    lv_obj_set_width(face_79_2_dial_3_123330, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_3_123330, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_3_123330, 188);
    lv_obj_set_y(face_79_2_dial_3_123330, 93);
    lv_obj_add_flag(face_79_2_dial_3_123330, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_dial_3_123330, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_dial_4_123330 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_4_123330, &face_79_2_dial_dial_img_3_123330_0);
    lv_obj_set_width(face_79_2_dial_4_123330, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_4_123330, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_4_123330, 154);
    lv_obj_set_y(face_79_2_dial_4_123330, 93);
    lv_obj_add_flag(face_79_2_dial_4_123330, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_dial_4_123330, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_dial_5_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_5_58512, &face_79_2_dial_dial_img_5_58512_0);
    lv_obj_set_width(face_79_2_dial_5_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_5_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_5_58512, 108);
    lv_obj_set_y(face_79_2_dial_5_58512, 211);
    lv_obj_add_flag(face_79_2_dial_5_58512, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_dial_5_58512, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_dial_6_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_6_58512, &face_79_2_dial_dial_img_5_58512_0);
    lv_obj_set_width(face_79_2_dial_6_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_6_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_6_58512, 99);
    lv_obj_set_y(face_79_2_dial_6_58512, 211);
    lv_obj_add_flag(face_79_2_dial_6_58512, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_dial_6_58512, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_dial_7_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_7_58512, &face_79_2_dial_dial_img_5_58512_0);
    lv_obj_set_width(face_79_2_dial_7_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_7_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_7_58512, 133);
    lv_obj_set_y(face_79_2_dial_7_58512, 211);
    lv_obj_add_flag(face_79_2_dial_7_58512, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_dial_7_58512, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_dial_8_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_8_58512, &face_79_2_dial_dial_img_5_58512_0);
    lv_obj_set_width(face_79_2_dial_8_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_8_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_8_58512, 124);
    lv_obj_set_y(face_79_2_dial_8_58512, 211);
    lv_obj_add_flag(face_79_2_dial_8_58512, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_dial_8_58512, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_dial_9_59456 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_9_59456, &face_79_2_dial_dial_img_9_59456_0);
    lv_obj_set_width(face_79_2_dial_9_59456, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_9_59456, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_9_59456, 116);
    lv_obj_set_y(face_79_2_dial_9_59456, 212);
    lv_obj_add_flag(face_79_2_dial_9_59456, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_dial_9_59456, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_dial_10_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_10_58512, &face_79_2_dial_dial_img_5_58512_0);
    lv_obj_set_width(face_79_2_dial_10_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_10_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_10_58512, 67);
    lv_obj_set_y(face_79_2_dial_10_58512, 189);
    lv_obj_add_flag(face_79_2_dial_10_58512, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_dial_10_58512, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_dial_11_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_11_58512, &face_79_2_dial_dial_img_5_58512_0);
    lv_obj_set_width(face_79_2_dial_11_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_11_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_11_58512, 58);
    lv_obj_set_y(face_79_2_dial_11_58512, 189);
    lv_obj_add_flag(face_79_2_dial_11_58512, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_dial_11_58512, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_dial_12_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_12_58512, &face_79_2_dial_dial_img_5_58512_0);
    lv_obj_set_width(face_79_2_dial_12_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_12_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_12_58512, 49);
    lv_obj_set_y(face_79_2_dial_12_58512, 189);
    lv_obj_add_flag(face_79_2_dial_12_58512, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_dial_12_58512, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_dial_13_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_13_58512, &face_79_2_dial_dial_img_5_58512_0);
    lv_obj_set_width(face_79_2_dial_13_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_13_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_13_58512, 195);
    lv_obj_set_y(face_79_2_dial_13_58512, 189);
    lv_obj_add_flag(face_79_2_dial_13_58512, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_dial_13_58512, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_dial_14_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_14_58512, &face_79_2_dial_dial_img_5_58512_0);
    lv_obj_set_width(face_79_2_dial_14_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_14_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_14_58512, 186);
    lv_obj_set_y(face_79_2_dial_14_58512, 189);
    lv_obj_add_flag(face_79_2_dial_14_58512, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_dial_14_58512, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_dial_15_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_15_58512, &face_79_2_dial_dial_img_5_58512_0);
    lv_obj_set_width(face_79_2_dial_15_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_15_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_15_58512, 177);
    lv_obj_set_y(face_79_2_dial_15_58512, 189);
    lv_obj_add_flag(face_79_2_dial_15_58512, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_dial_15_58512, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_dial_16_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_16_58512, &face_79_2_dial_dial_img_5_58512_0);
    lv_obj_set_width(face_79_2_dial_16_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_16_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_16_58512, 168);
    lv_obj_set_y(face_79_2_dial_16_58512, 189);
    lv_obj_add_flag(face_79_2_dial_16_58512, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_dial_16_58512, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_dial_17_58512 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_17_58512, &face_79_2_dial_dial_img_5_58512_0);
    lv_obj_set_width(face_79_2_dial_17_58512, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_17_58512, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_17_58512, 159);
    lv_obj_set_y(face_79_2_dial_17_58512, 189);
    lv_obj_add_flag(face_79_2_dial_17_58512, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_dial_17_58512, LV_OBJ_FLAG_SCROLLABLE );

    face_79_2_dial_19_144206 = lv_img_create(face_79_2_dial);
    lv_img_set_src(face_79_2_dial_19_144206, &face_79_2_dial_dial_img_19_144206_0);
    lv_obj_set_width(face_79_2_dial_19_144206, LV_SIZE_CONTENT);
    lv_obj_set_height(face_79_2_dial_19_144206, LV_SIZE_CONTENT);
    lv_obj_set_x(face_79_2_dial_19_144206, 74);
    lv_obj_set_y(face_79_2_dial_19_144206, 23);
    lv_obj_add_flag(face_79_2_dial_19_144206, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_79_2_dial_19_144206, LV_OBJ_FLAG_SCROLLABLE );


    callback("Blue", &face_79_2_dial_dial_img_preview_0, &face_79_2_dial);

#endif
}

void update_time_79_2_dial(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_79_2_DIAL
    if (!face_79_2_dial)
    {
        return;
    }
	lv_img_set_src(face_79_2_dial_1_59582, face_79_2_dial_dial_img_1_59582_group[(hour / 1) % 10]);
	lv_img_set_src(face_79_2_dial_2_59582, face_79_2_dial_dial_img_1_59582_group[(hour / 10) % 10]);
	lv_img_set_src(face_79_2_dial_3_123330, face_79_2_dial_dial_img_3_123330_group[(minute / 1) % 10]);
	lv_img_set_src(face_79_2_dial_4_123330, face_79_2_dial_dial_img_3_123330_group[(minute / 10) % 10]);
	lv_img_set_src(face_79_2_dial_5_58512, face_79_2_dial_dial_img_5_58512_group[(month / 1) % 10]);
	lv_img_set_src(face_79_2_dial_6_58512, face_79_2_dial_dial_img_5_58512_group[(month / 10) % 10]);
	lv_img_set_src(face_79_2_dial_7_58512, face_79_2_dial_dial_img_5_58512_group[(day / 1) % 10]);
	lv_img_set_src(face_79_2_dial_8_58512, face_79_2_dial_dial_img_5_58512_group[(day / 10) % 10]);
	lv_img_set_src(face_79_2_dial_19_144206, face_79_2_dial_dial_img_19_144206_group[((weekday + 6) / 1) % 7]);

#endif
}

void update_weather_79_2_dial(int temp, int icon)
{
#ifdef ENABLE_FACE_79_2_DIAL
    if (!face_79_2_dial)
    {
        return;
    }

#endif
}

void update_status_79_2_dial(int battery, bool connection){
#ifdef ENABLE_FACE_79_2_DIAL
    if (!face_79_2_dial)
    {
        return;
    }
	lv_img_set_src(face_79_2_dial_10_58512, face_79_2_dial_dial_img_5_58512_group[(battery / 1) % 10]);
	lv_img_set_src(face_79_2_dial_11_58512, face_79_2_dial_dial_img_5_58512_group[(battery / 10) % 10]);
	lv_img_set_src(face_79_2_dial_12_58512, face_79_2_dial_dial_img_5_58512_group[(battery / 100) % 10]);
	if (battery < 100)
	{
		lv_obj_add_flag(face_79_2_dial_12_58512, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_79_2_dial_12_58512, LV_OBJ_FLAG_HIDDEN);
	}

#endif
}

void update_activity_79_2_dial(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_79_2_DIAL
    if (!face_79_2_dial)
    {
        return;
    }
	lv_img_set_src(face_79_2_dial_13_58512, face_79_2_dial_dial_img_5_58512_group[(steps / 1) % 10]);
	lv_img_set_src(face_79_2_dial_14_58512, face_79_2_dial_dial_img_5_58512_group[(steps / 10) % 10]);
	lv_img_set_src(face_79_2_dial_15_58512, face_79_2_dial_dial_img_5_58512_group[(steps / 100) % 10]);
	lv_img_set_src(face_79_2_dial_16_58512, face_79_2_dial_dial_img_5_58512_group[(steps / 1000) % 10]);
	lv_img_set_src(face_79_2_dial_17_58512, face_79_2_dial_dial_img_5_58512_group[(steps / 10000) % 10]);

#endif
}

void update_health_79_2_dial(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_79_2_DIAL
    if (!face_79_2_dial)
    {
        return;
    }

#endif
}

void update_all_79_2_dial(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_79_2_DIAL
    update_time_79_2_dial(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_79_2_dial(temp, icon);
    update_status_79_2_dial(battery, connection);
    update_activity_79_2_dial(steps, distance, kcal);
    update_health_79_2_dial(bpm, oxygen);
#endif
}

void update_check_79_2_dial(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_79_2_DIAL
    if (root != face_79_2_dial)
    {
        return;
    }
    update_time_79_2_dial(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_79_2_dial(temp, icon);
    update_status_79_2_dial(battery, connection);
    update_activity_79_2_dial(steps, distance, kcal);
    update_health_79_2_dial(bpm, oxygen);
#endif
}


