
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 2151_410

#include "2151_410.h"

#ifdef ENABLE_FACE_2151_410

lv_obj_t *face_2151_410;
lv_obj_t *face_2151_410_0_1184;
lv_obj_t *face_2151_410_2_204502;
lv_obj_t *face_2151_410_4_206548;
lv_obj_t *face_2151_410_5_65535;
lv_obj_t *face_2151_410_6_65535;
lv_obj_t *face_2151_410_7_207436;
lv_obj_t *face_2151_410_8_207436;
lv_obj_t *face_2151_410_9_207436;
lv_obj_t *face_2151_410_10_212058;
lv_obj_t *face_2151_410_11_213871;
lv_obj_t *face_2151_410_12_65535;
lv_obj_t *face_2151_410_13_215670;
lv_obj_t *face_2151_410_14_215670;
lv_obj_t *face_2151_410_15_215670;
lv_obj_t *face_2151_410_16_215670;
lv_obj_t *face_2151_410_18_219347;
lv_obj_t *face_2151_410_20_220394;
lv_obj_t *face_2151_410_22_233288;
lv_obj_t *face_2151_410_23_246741;
lv_obj_t *face_2151_410_24_246741;
lv_obj_t *face_2151_410_25_246741;
lv_obj_t *face_2151_410_26_246741;
lv_obj_t *face_2151_410_27_254873;
lv_obj_t *face_2151_410_28_215670;
lv_obj_t *face_2151_410_29_215670;
lv_obj_t *face_2151_410_30_215670;
lv_obj_t *face_2151_410_31_215670;
lv_obj_t *face_2151_410_32_215670;
lv_obj_t *face_2151_410_33_215670;
lv_obj_t *face_2151_410_34_215670;
lv_obj_t *face_2151_410_35_215670;
lv_obj_t *face_2151_410_36_215670;
lv_obj_t *face_2151_410_37_215670;
lv_obj_t *face_2151_410_38_215670;
lv_obj_t *face_2151_410_39_254919;
lv_obj_t *face_2151_410_40_215670;
lv_obj_t *face_2151_410_41_215670;
lv_obj_t *face_2151_410_42_215670;
lv_obj_t *face_2151_410_43_255480;
lv_obj_t *face_2151_410_44_255511;
lv_obj_t *face_2151_410_45_255511;
lv_obj_t *face_2151_410_46_255511;
lv_obj_t *face_2151_410_47_255511;
lv_obj_t *face_2151_410_48_276965;
lv_obj_t *face_2151_410_50_277299;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif

const lv_img_dsc_t *face_2151_410_dial_img_1_203414_group[] = {
	&face_2151_410_dial_img_1_203414_0,
	&face_2151_410_dial_img_1_203414_1,
};
const lv_img_dsc_t *face_2151_410_dial_img_2_204502_group[] = {
	&face_2151_410_dial_img_2_204502_0,
	&face_2151_410_dial_img_2_204502_1,
};
const lv_img_dsc_t *face_2151_410_dial_img_3_205590_group[] = {
	&face_2151_410_dial_img_3_205590_0,
	&face_2151_410_dial_img_3_205590_1,
};
const lv_img_dsc_t *face_2151_410_dial_img_4_206548_group[] = {
	&face_2151_410_dial_img_4_206548_0,
	&face_2151_410_dial_img_4_206548_1,
};
const lv_img_dsc_t *face_2151_410_dial_img_7_207436_group[] = {
	&face_2151_410_dial_img_7_207436_0,
	&face_2151_410_dial_img_7_207436_1,
	&face_2151_410_dial_img_7_207436_2,
	&face_2151_410_dial_img_7_207436_3,
	&face_2151_410_dial_img_7_207436_4,
	&face_2151_410_dial_img_7_207436_5,
	&face_2151_410_dial_img_7_207436_6,
	&face_2151_410_dial_img_7_207436_7,
	&face_2151_410_dial_img_7_207436_8,
	&face_2151_410_dial_img_7_207436_9,
};
const lv_img_dsc_t *face_2151_410_dial_img_13_215670_group[] = {
	&face_2151_410_dial_img_13_215670_0,
	&face_2151_410_dial_img_13_215670_1,
	&face_2151_410_dial_img_13_215670_2,
	&face_2151_410_dial_img_13_215670_3,
	&face_2151_410_dial_img_13_215670_4,
	&face_2151_410_dial_img_13_215670_5,
	&face_2151_410_dial_img_13_215670_6,
	&face_2151_410_dial_img_13_215670_7,
	&face_2151_410_dial_img_13_215670_8,
	&face_2151_410_dial_img_13_215670_9,
};
const lv_img_dsc_t *face_2151_410_dial_img_21_220864_group[] = {
	&face_2151_410_dial_img_21_220864_0,
	&face_2151_410_dial_img_21_220864_1,
	&face_2151_410_dial_img_21_220864_2,
	&face_2151_410_dial_img_21_220864_3,
	&face_2151_410_dial_img_21_220864_4,
	&face_2151_410_dial_img_21_220864_5,
	&face_2151_410_dial_img_21_220864_6,
};
const lv_img_dsc_t *face_2151_410_dial_img_22_233288_group[] = {
	&face_2151_410_dial_img_22_233288_0,
	&face_2151_410_dial_img_22_233288_1,
	&face_2151_410_dial_img_22_233288_2,
	&face_2151_410_dial_img_22_233288_3,
	&face_2151_410_dial_img_22_233288_4,
	&face_2151_410_dial_img_22_233288_5,
	&face_2151_410_dial_img_22_233288_6,
};
const lv_img_dsc_t *face_2151_410_dial_img_23_246741_group[] = {
	&face_2151_410_dial_img_23_246741_0,
	&face_2151_410_dial_img_23_246741_1,
	&face_2151_410_dial_img_23_246741_2,
	&face_2151_410_dial_img_23_246741_3,
	&face_2151_410_dial_img_23_246741_4,
	&face_2151_410_dial_img_23_246741_5,
	&face_2151_410_dial_img_23_246741_6,
	&face_2151_410_dial_img_23_246741_7,
	&face_2151_410_dial_img_23_246741_8,
	&face_2151_410_dial_img_23_246741_9,
};
const lv_img_dsc_t *face_2151_410_dial_img_44_255511_group[] = {
	&face_2151_410_dial_img_44_255511_0,
	&face_2151_410_dial_img_44_255511_1,
	&face_2151_410_dial_img_44_255511_2,
	&face_2151_410_dial_img_44_255511_3,
	&face_2151_410_dial_img_44_255511_4,
	&face_2151_410_dial_img_44_255511_5,
	&face_2151_410_dial_img_44_255511_6,
	&face_2151_410_dial_img_44_255511_7,
	&face_2151_410_dial_img_44_255511_8,
	&face_2151_410_dial_img_44_255511_9,
};
const lv_img_dsc_t *face_2151_410_dial_img_weather[] = {
	&face_2151_410_dial_img_50_277299_0,
	&face_2151_410_dial_img_51_279564_0,
	&face_2151_410_dial_img_52_281885_0,
	&face_2151_410_dial_img_53_284210_0,
	&face_2151_410_dial_img_54_286525_0,
	&face_2151_410_dial_img_55_288778_0,
	&face_2151_410_dial_img_56_291179_0,
	&face_2151_410_dial_img_57_293474_0,
	&face_2151_410_dial_img_58_295837_0,
};




#endif

void init_face_2151_410(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **)){
#ifdef ENABLE_FACE_2151_410
    face_2151_410 = lv_obj_create(NULL);
    lv_obj_clear_flag(face_2151_410, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_2151_410, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_2151_410, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_2151_410, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_2151_410, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_2151_410, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_2151_410, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_2151_410, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_2151_410, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_2151_410_0_1184 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_0_1184, &face_2151_410_dial_img_0_1184_0);
    lv_obj_set_width(face_2151_410_0_1184, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_0_1184, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_0_1184, 0);
    lv_obj_set_y(face_2151_410_0_1184, 0);
    lv_obj_add_flag(face_2151_410_0_1184, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_0_1184, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_2_204502 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_2_204502, &face_2151_410_dial_img_2_204502_0);
    lv_obj_set_width(face_2151_410_2_204502, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_2_204502, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_2_204502, 203);
    lv_obj_set_y(face_2151_410_2_204502, 285);
    lv_obj_add_flag(face_2151_410_2_204502, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_2_204502, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_4_206548 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_4_206548, &face_2151_410_dial_img_4_206548_0);
    lv_obj_set_width(face_2151_410_4_206548, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_4_206548, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_4_206548, 205);
    lv_obj_set_y(face_2151_410_4_206548, 287);
    lv_obj_add_flag(face_2151_410_4_206548, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_4_206548, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_5_65535 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_5_65535, &face_2151_410_dial_img_5_65535_0);
    lv_obj_set_width(face_2151_410_5_65535, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_5_65535, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_5_65535, 225);
    lv_obj_set_y(face_2151_410_5_65535, 25);
    lv_obj_add_flag(face_2151_410_5_65535, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_5_65535, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_6_65535 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_6_65535, &face_2151_410_dial_img_5_65535_0);
    lv_obj_set_width(face_2151_410_6_65535, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_6_65535, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_6_65535, 206);
    lv_obj_set_y(face_2151_410_6_65535, 25);
    lv_obj_add_flag(face_2151_410_6_65535, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_6_65535, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_7_207436 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_7_207436, &face_2151_410_dial_img_7_207436_0);
    lv_obj_set_width(face_2151_410_7_207436, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_7_207436, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_7_207436, 225);
    lv_obj_set_y(face_2151_410_7_207436, 15);
    lv_obj_add_flag(face_2151_410_7_207436, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_7_207436, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_8_207436 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_8_207436, &face_2151_410_dial_img_7_207436_0);
    lv_obj_set_width(face_2151_410_8_207436, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_8_207436, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_8_207436, 206);
    lv_obj_set_y(face_2151_410_8_207436, 15);
    lv_obj_add_flag(face_2151_410_8_207436, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_8_207436, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_9_207436 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_9_207436, &face_2151_410_dial_img_7_207436_0);
    lv_obj_set_width(face_2151_410_9_207436, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_9_207436, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_9_207436, 187);
    lv_obj_set_y(face_2151_410_9_207436, 15);
    lv_obj_add_flag(face_2151_410_9_207436, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_9_207436, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_10_212058 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_10_212058, &face_2151_410_dial_img_10_212058_0);
    lv_obj_set_width(face_2151_410_10_212058, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_10_212058, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_10_212058, 242);
    lv_obj_set_y(face_2151_410_10_212058, 8);
    lv_obj_add_flag(face_2151_410_10_212058, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_10_212058, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_11_213871 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_11_213871, &face_2151_410_dial_img_11_213871_0);
    lv_obj_set_width(face_2151_410_11_213871, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_11_213871, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_11_213871, 242);
    lv_obj_set_y(face_2151_410_11_213871, 8);
    lv_obj_add_flag(face_2151_410_11_213871, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_11_213871, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_12_65535 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_12_65535, &face_2151_410_dial_img_5_65535_0);
    lv_obj_set_width(face_2151_410_12_65535, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_12_65535, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_12_65535, 193);
    lv_obj_set_y(face_2151_410_12_65535, 25);
    lv_obj_add_flag(face_2151_410_12_65535, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_12_65535, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_13_215670 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_13_215670, &face_2151_410_dial_img_13_215670_0);
    lv_obj_set_width(face_2151_410_13_215670, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_13_215670, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_13_215670, 83);
    lv_obj_set_y(face_2151_410_13_215670, 338);
    lv_obj_add_flag(face_2151_410_13_215670, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_13_215670, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_14_215670 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_14_215670, &face_2151_410_dial_img_13_215670_0);
    lv_obj_set_width(face_2151_410_14_215670, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_14_215670, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_14_215670, 66);
    lv_obj_set_y(face_2151_410_14_215670, 338);
    lv_obj_add_flag(face_2151_410_14_215670, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_14_215670, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_15_215670 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_15_215670, &face_2151_410_dial_img_13_215670_0);
    lv_obj_set_width(face_2151_410_15_215670, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_15_215670, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_15_215670, 152);
    lv_obj_set_y(face_2151_410_15_215670, 338);
    lv_obj_add_flag(face_2151_410_15_215670, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_15_215670, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_16_215670 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_16_215670, &face_2151_410_dial_img_13_215670_0);
    lv_obj_set_width(face_2151_410_16_215670, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_16_215670, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_16_215670, 134);
    lv_obj_set_y(face_2151_410_16_215670, 338);
    lv_obj_add_flag(face_2151_410_16_215670, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_16_215670, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_18_219347 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_18_219347, &face_2151_410_dial_img_18_219347_0);
    lv_obj_set_width(face_2151_410_18_219347, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_18_219347, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_18_219347, 107);
    lv_obj_set_y(face_2151_410_18_219347, 339);
    lv_obj_add_flag(face_2151_410_18_219347, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_18_219347, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_20_220394 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_20_220394, &face_2151_410_dial_img_20_220394_0);
    lv_obj_set_width(face_2151_410_20_220394, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_20_220394, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_20_220394, 172);
    lv_obj_set_y(face_2151_410_20_220394, 339);
    lv_obj_add_flag(face_2151_410_20_220394, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_20_220394, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_22_233288 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_22_233288, &face_2151_410_dial_img_22_233288_0);
    lv_obj_set_width(face_2151_410_22_233288, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_22_233288, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_22_233288, 302);
    lv_obj_set_y(face_2151_410_22_233288, 283);
    lv_obj_add_flag(face_2151_410_22_233288, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_22_233288, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_23_246741 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_23_246741, &face_2151_410_dial_img_23_246741_0);
    lv_obj_set_width(face_2151_410_23_246741, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_23_246741, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_23_246741, 307);
    lv_obj_set_y(face_2151_410_23_246741, 329);
    lv_obj_add_flag(face_2151_410_23_246741, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_23_246741, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_24_246741 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_24_246741, &face_2151_410_dial_img_23_246741_0);
    lv_obj_set_width(face_2151_410_24_246741, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_24_246741, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_24_246741, 278);
    lv_obj_set_y(face_2151_410_24_246741, 329);
    lv_obj_add_flag(face_2151_410_24_246741, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_24_246741, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_25_246741 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_25_246741, &face_2151_410_dial_img_23_246741_0);
    lv_obj_set_width(face_2151_410_25_246741, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_25_246741, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_25_246741, 377);
    lv_obj_set_y(face_2151_410_25_246741, 329);
    lv_obj_add_flag(face_2151_410_25_246741, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_25_246741, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_26_246741 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_26_246741, &face_2151_410_dial_img_23_246741_0);
    lv_obj_set_width(face_2151_410_26_246741, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_26_246741, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_26_246741, 348);
    lv_obj_set_y(face_2151_410_26_246741, 329);
    lv_obj_add_flag(face_2151_410_26_246741, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_26_246741, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_27_254873 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_27_254873, &face_2151_410_dial_img_27_254873_0);
    lv_obj_set_width(face_2151_410_27_254873, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_27_254873, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_27_254873, 338);
    lv_obj_set_y(face_2151_410_27_254873, 351);
    lv_obj_add_flag(face_2151_410_27_254873, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_27_254873, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_28_215670 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_28_215670, &face_2151_410_dial_img_13_215670_0);
    lv_obj_set_width(face_2151_410_28_215670, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_28_215670, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_28_215670, 152);
    lv_obj_set_y(face_2151_410_28_215670, 396);
    lv_obj_add_flag(face_2151_410_28_215670, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_28_215670, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_29_215670 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_29_215670, &face_2151_410_dial_img_13_215670_0);
    lv_obj_set_width(face_2151_410_29_215670, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_29_215670, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_29_215670, 133);
    lv_obj_set_y(face_2151_410_29_215670, 396);
    lv_obj_add_flag(face_2151_410_29_215670, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_29_215670, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_30_215670 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_30_215670, &face_2151_410_dial_img_13_215670_0);
    lv_obj_set_width(face_2151_410_30_215670, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_30_215670, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_30_215670, 114);
    lv_obj_set_y(face_2151_410_30_215670, 396);
    lv_obj_add_flag(face_2151_410_30_215670, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_30_215670, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_31_215670 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_31_215670, &face_2151_410_dial_img_13_215670_0);
    lv_obj_set_width(face_2151_410_31_215670, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_31_215670, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_31_215670, 95);
    lv_obj_set_y(face_2151_410_31_215670, 396);
    lv_obj_add_flag(face_2151_410_31_215670, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_31_215670, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_32_215670 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_32_215670, &face_2151_410_dial_img_13_215670_0);
    lv_obj_set_width(face_2151_410_32_215670, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_32_215670, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_32_215670, 76);
    lv_obj_set_y(face_2151_410_32_215670, 396);
    lv_obj_add_flag(face_2151_410_32_215670, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_32_215670, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_33_215670 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_33_215670, &face_2151_410_dial_img_13_215670_0);
    lv_obj_set_width(face_2151_410_33_215670, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_33_215670, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_33_215670, 338);
    lv_obj_set_y(face_2151_410_33_215670, 392);
    lv_obj_add_flag(face_2151_410_33_215670, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_33_215670, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_34_215670 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_34_215670, &face_2151_410_dial_img_13_215670_0);
    lv_obj_set_width(face_2151_410_34_215670, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_34_215670, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_34_215670, 319);
    lv_obj_set_y(face_2151_410_34_215670, 392);
    lv_obj_add_flag(face_2151_410_34_215670, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_34_215670, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_35_215670 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_35_215670, &face_2151_410_dial_img_13_215670_0);
    lv_obj_set_width(face_2151_410_35_215670, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_35_215670, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_35_215670, 300);
    lv_obj_set_y(face_2151_410_35_215670, 392);
    lv_obj_add_flag(face_2151_410_35_215670, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_35_215670, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_36_215670 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_36_215670, &face_2151_410_dial_img_13_215670_0);
    lv_obj_set_width(face_2151_410_36_215670, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_36_215670, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_36_215670, 123);
    lv_obj_set_y(face_2151_410_36_215670, 454);
    lv_obj_add_flag(face_2151_410_36_215670, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_36_215670, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_37_215670 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_37_215670, &face_2151_410_dial_img_13_215670_0);
    lv_obj_set_width(face_2151_410_37_215670, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_37_215670, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_37_215670, 105);
    lv_obj_set_y(face_2151_410_37_215670, 454);
    lv_obj_add_flag(face_2151_410_37_215670, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_37_215670, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_38_215670 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_38_215670, &face_2151_410_dial_img_13_215670_0);
    lv_obj_set_width(face_2151_410_38_215670, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_38_215670, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_38_215670, 88);
    lv_obj_set_y(face_2151_410_38_215670, 454);
    lv_obj_add_flag(face_2151_410_38_215670, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_38_215670, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_39_254919 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_39_254919, &face_2151_410_dial_img_39_254919_0);
    lv_obj_set_width(face_2151_410_39_254919, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_39_254919, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_39_254919, 141);
    lv_obj_set_y(face_2151_410_39_254919, 454);
    lv_obj_add_flag(face_2151_410_39_254919, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_39_254919, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_40_215670 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_40_215670, &face_2151_410_dial_img_13_215670_0);
    lv_obj_set_width(face_2151_410_40_215670, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_40_215670, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_40_215670, 339);
    lv_obj_set_y(face_2151_410_40_215670, 454);
    lv_obj_add_flag(face_2151_410_40_215670, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_40_215670, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_41_215670 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_41_215670, &face_2151_410_dial_img_13_215670_0);
    lv_obj_set_width(face_2151_410_41_215670, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_41_215670, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_41_215670, 312);
    lv_obj_set_y(face_2151_410_41_215670, 454);
    lv_obj_add_flag(face_2151_410_41_215670, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_41_215670, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_42_215670 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_42_215670, &face_2151_410_dial_img_13_215670_0);
    lv_obj_set_width(face_2151_410_42_215670, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_42_215670, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_42_215670, 293);
    lv_obj_set_y(face_2151_410_42_215670, 454);
    lv_obj_add_flag(face_2151_410_42_215670, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_42_215670, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_43_255480 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_43_255480, &face_2151_410_dial_img_43_255480_0);
    lv_obj_set_width(face_2151_410_43_255480, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_43_255480, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_43_255480, 329);
    lv_obj_set_y(face_2151_410_43_255480, 471);
    lv_obj_add_flag(face_2151_410_43_255480, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_43_255480, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_44_255511 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_44_255511, &face_2151_410_dial_img_44_255511_0);
    lv_obj_set_width(face_2151_410_44_255511, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_44_255511, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_44_255511, 42);
    lv_obj_set_y(face_2151_410_44_255511, 237);
    lv_obj_add_flag(face_2151_410_44_255511, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_44_255511, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_45_255511 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_45_255511, &face_2151_410_dial_img_44_255511_0);
    lv_obj_set_width(face_2151_410_45_255511, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_45_255511, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_45_255511, 0);
    lv_obj_set_y(face_2151_410_45_255511, 237);
    lv_obj_add_flag(face_2151_410_45_255511, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_45_255511, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_46_255511 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_46_255511, &face_2151_410_dial_img_44_255511_0);
    lv_obj_set_width(face_2151_410_46_255511, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_46_255511, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_46_255511, 152);
    lv_obj_set_y(face_2151_410_46_255511, 237);
    lv_obj_add_flag(face_2151_410_46_255511, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_46_255511, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_47_255511 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_47_255511, &face_2151_410_dial_img_44_255511_0);
    lv_obj_set_width(face_2151_410_47_255511, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_47_255511, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_47_255511, 107);
    lv_obj_set_y(face_2151_410_47_255511, 237);
    lv_obj_add_flag(face_2151_410_47_255511, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_47_255511, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_48_276965 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_48_276965, &face_2151_410_dial_img_48_276965_0);
    lv_obj_set_width(face_2151_410_48_276965, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_48_276965, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_48_276965, 90);
    lv_obj_set_y(face_2151_410_48_276965, 254);
    lv_obj_add_flag(face_2151_410_48_276965, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_48_276965, LV_OBJ_FLAG_SCROLLABLE );

    face_2151_410_50_277299 = lv_img_create(face_2151_410);
    lv_img_set_src(face_2151_410_50_277299, &face_2151_410_dial_img_50_277299_0);
    lv_obj_set_width(face_2151_410_50_277299, LV_SIZE_CONTENT);
    lv_obj_set_height(face_2151_410_50_277299, LV_SIZE_CONTENT);
    lv_obj_set_x(face_2151_410_50_277299, 134);
    lv_obj_set_y(face_2151_410_50_277299, 8);
    lv_obj_add_flag(face_2151_410_50_277299, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_2151_410_50_277299, LV_OBJ_FLAG_SCROLLABLE );


    callback("2151", &face_2151_410_dial_img_preview_0, &face_2151_410, NULL);

#endif
}

void update_time_2151_410(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_2151_410
    if (!face_2151_410)
    {
        return;
    }
	if (mode)
	{
		lv_obj_add_flag(face_2151_410_2_204502, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_2151_410_2_204502, LV_OBJ_FLAG_HIDDEN);
	}
	lv_img_set_src(face_2151_410_2_204502, face_2151_410_dial_img_2_204502_group[(am ? 0 : 1) % 2]);
	if (mode)
	{
		lv_obj_add_flag(face_2151_410_4_206548, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_2151_410_4_206548, LV_OBJ_FLAG_HIDDEN);
	}
	lv_img_set_src(face_2151_410_4_206548, face_2151_410_dial_img_4_206548_group[(am ? 0 : 1) % 2]);
	lv_img_set_src(face_2151_410_22_233288, face_2151_410_dial_img_22_233288_group[((weekday + 6) / 1) % 7]);
	lv_img_set_src(face_2151_410_23_246741, face_2151_410_dial_img_23_246741_group[(month / 1) % 10]);
	lv_img_set_src(face_2151_410_24_246741, face_2151_410_dial_img_23_246741_group[(month / 10) % 10]);
	lv_img_set_src(face_2151_410_25_246741, face_2151_410_dial_img_23_246741_group[(day / 1) % 10]);
	lv_img_set_src(face_2151_410_26_246741, face_2151_410_dial_img_23_246741_group[(day / 10) % 10]);
	lv_img_set_src(face_2151_410_44_255511, face_2151_410_dial_img_44_255511_group[(hour / 1) % 10]);
	lv_img_set_src(face_2151_410_45_255511, face_2151_410_dial_img_44_255511_group[(hour / 10) % 10]);
	lv_img_set_src(face_2151_410_46_255511, face_2151_410_dial_img_44_255511_group[(minute / 1) % 10]);
	lv_img_set_src(face_2151_410_47_255511, face_2151_410_dial_img_44_255511_group[(minute / 10) % 10]);

#endif
}

void update_weather_2151_410(int temp, int icon)
{
#ifdef ENABLE_FACE_2151_410
    if (!face_2151_410)
    {
        return;
    }
	lv_img_set_src(face_2151_410_50_277299, face_2151_410_dial_img_weather[icon % 8]);

#endif
}

void update_status_2151_410(int battery, bool connection){
#ifdef ENABLE_FACE_2151_410
    if (!face_2151_410)
    {
        return;
    }
	lv_img_set_src(face_2151_410_36_215670, face_2151_410_dial_img_13_215670_group[(battery / 1) % 10]);
	lv_img_set_src(face_2151_410_37_215670, face_2151_410_dial_img_13_215670_group[(battery / 10) % 10]);
	lv_img_set_src(face_2151_410_38_215670, face_2151_410_dial_img_13_215670_group[(battery / 100) % 10]);
	if (battery < 100)
	{
		lv_obj_add_flag(face_2151_410_38_215670, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_2151_410_38_215670, LV_OBJ_FLAG_HIDDEN);
	}

#endif
}

void update_activity_2151_410(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_2151_410
    if (!face_2151_410)
    {
        return;
    }
	lv_img_set_src(face_2151_410_28_215670, face_2151_410_dial_img_13_215670_group[(steps / 1) % 10]);
	lv_img_set_src(face_2151_410_29_215670, face_2151_410_dial_img_13_215670_group[(steps / 10) % 10]);
	lv_img_set_src(face_2151_410_30_215670, face_2151_410_dial_img_13_215670_group[(steps / 100) % 10]);
	lv_img_set_src(face_2151_410_31_215670, face_2151_410_dial_img_13_215670_group[(steps / 1000) % 10]);
	lv_img_set_src(face_2151_410_32_215670, face_2151_410_dial_img_13_215670_group[(steps / 10000) % 10]);
	lv_img_set_src(face_2151_410_40_215670, face_2151_410_dial_img_13_215670_group[(distance / 1) % 10]);
	lv_img_set_src(face_2151_410_41_215670, face_2151_410_dial_img_13_215670_group[(distance / 10) % 10]);
	lv_img_set_src(face_2151_410_42_215670, face_2151_410_dial_img_13_215670_group[(distance / 100) % 10]);

#endif
}

void update_health_2151_410(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_2151_410
    if (!face_2151_410)
    {
        return;
    }
	lv_img_set_src(face_2151_410_33_215670, face_2151_410_dial_img_13_215670_group[(bpm / 1) % 10]);
	lv_img_set_src(face_2151_410_34_215670, face_2151_410_dial_img_13_215670_group[(bpm / 10) % 10]);
	lv_img_set_src(face_2151_410_35_215670, face_2151_410_dial_img_13_215670_group[(bpm / 100) % 10]);

#endif
}

void update_all_2151_410(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_2151_410
    update_time_2151_410(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_2151_410(temp, icon);
    update_status_2151_410(battery, connection);
    update_activity_2151_410(steps, distance, kcal);
    update_health_2151_410(bpm, oxygen);
#endif
}

void update_check_2151_410(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_2151_410
    if (root != face_2151_410)
    {
        return;
    }
    update_time_2151_410(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_2151_410(temp, icon);
    update_status_2151_410(battery, connection);
    update_activity_2151_410(steps, distance, kcal);
    update_health_2151_410(bpm, oxygen);
#endif
}


