
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 2151_410

#ifndef _FACE_2151_410_H
#define _FACE_2151_410_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"
#include "app_hal.h"

//#define ENABLE_FACE_2151_410 // (2151) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_2151_410
    extern lv_obj_t *face_2151_410;
	extern lv_obj_t *face_2151_410_0_1184;
	extern lv_obj_t *face_2151_410_2_204502;
	extern lv_obj_t *face_2151_410_4_206548;
	extern lv_obj_t *face_2151_410_5_65535;
	extern lv_obj_t *face_2151_410_6_65535;
	extern lv_obj_t *face_2151_410_7_207436;
	extern lv_obj_t *face_2151_410_8_207436;
	extern lv_obj_t *face_2151_410_9_207436;
	extern lv_obj_t *face_2151_410_10_212058;
	extern lv_obj_t *face_2151_410_11_213871;
	extern lv_obj_t *face_2151_410_12_65535;
	extern lv_obj_t *face_2151_410_13_215670;
	extern lv_obj_t *face_2151_410_14_215670;
	extern lv_obj_t *face_2151_410_15_215670;
	extern lv_obj_t *face_2151_410_16_215670;
	extern lv_obj_t *face_2151_410_18_219347;
	extern lv_obj_t *face_2151_410_20_220394;
	extern lv_obj_t *face_2151_410_22_233288;
	extern lv_obj_t *face_2151_410_23_246741;
	extern lv_obj_t *face_2151_410_24_246741;
	extern lv_obj_t *face_2151_410_25_246741;
	extern lv_obj_t *face_2151_410_26_246741;
	extern lv_obj_t *face_2151_410_27_254873;
	extern lv_obj_t *face_2151_410_28_215670;
	extern lv_obj_t *face_2151_410_29_215670;
	extern lv_obj_t *face_2151_410_30_215670;
	extern lv_obj_t *face_2151_410_31_215670;
	extern lv_obj_t *face_2151_410_32_215670;
	extern lv_obj_t *face_2151_410_33_215670;
	extern lv_obj_t *face_2151_410_34_215670;
	extern lv_obj_t *face_2151_410_35_215670;
	extern lv_obj_t *face_2151_410_36_215670;
	extern lv_obj_t *face_2151_410_37_215670;
	extern lv_obj_t *face_2151_410_38_215670;
	extern lv_obj_t *face_2151_410_39_254919;
	extern lv_obj_t *face_2151_410_40_215670;
	extern lv_obj_t *face_2151_410_41_215670;
	extern lv_obj_t *face_2151_410_42_215670;
	extern lv_obj_t *face_2151_410_43_255480;
	extern lv_obj_t *face_2151_410_44_255511;
	extern lv_obj_t *face_2151_410_45_255511;
	extern lv_obj_t *face_2151_410_46_255511;
	extern lv_obj_t *face_2151_410_47_255511;
	extern lv_obj_t *face_2151_410_48_276965;
	extern lv_obj_t *face_2151_410_50_277299;


	LV_IMG_DECLARE(face_2151_410_dial_img_0_1184_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_1_203414_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_1_203414_1);
	LV_IMG_DECLARE(face_2151_410_dial_img_2_204502_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_2_204502_1);
	LV_IMG_DECLARE(face_2151_410_dial_img_3_205590_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_3_205590_1);
	LV_IMG_DECLARE(face_2151_410_dial_img_4_206548_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_4_206548_1);
	LV_IMG_DECLARE(face_2151_410_dial_img_5_65535_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_7_207436_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_7_207436_1);
	LV_IMG_DECLARE(face_2151_410_dial_img_7_207436_2);
	LV_IMG_DECLARE(face_2151_410_dial_img_7_207436_3);
	LV_IMG_DECLARE(face_2151_410_dial_img_7_207436_4);
	LV_IMG_DECLARE(face_2151_410_dial_img_7_207436_5);
	LV_IMG_DECLARE(face_2151_410_dial_img_7_207436_6);
	LV_IMG_DECLARE(face_2151_410_dial_img_7_207436_7);
	LV_IMG_DECLARE(face_2151_410_dial_img_7_207436_8);
	LV_IMG_DECLARE(face_2151_410_dial_img_7_207436_9);
	LV_IMG_DECLARE(face_2151_410_dial_img_10_212058_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_11_213871_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_13_215670_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_13_215670_1);
	LV_IMG_DECLARE(face_2151_410_dial_img_13_215670_2);
	LV_IMG_DECLARE(face_2151_410_dial_img_13_215670_3);
	LV_IMG_DECLARE(face_2151_410_dial_img_13_215670_4);
	LV_IMG_DECLARE(face_2151_410_dial_img_13_215670_5);
	LV_IMG_DECLARE(face_2151_410_dial_img_13_215670_6);
	LV_IMG_DECLARE(face_2151_410_dial_img_13_215670_7);
	LV_IMG_DECLARE(face_2151_410_dial_img_13_215670_8);
	LV_IMG_DECLARE(face_2151_410_dial_img_13_215670_9);
	LV_IMG_DECLARE(face_2151_410_dial_img_17_218692_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_18_219347_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_19_219739_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_20_220394_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_21_220864_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_21_220864_1);
	LV_IMG_DECLARE(face_2151_410_dial_img_21_220864_2);
	LV_IMG_DECLARE(face_2151_410_dial_img_21_220864_3);
	LV_IMG_DECLARE(face_2151_410_dial_img_21_220864_4);
	LV_IMG_DECLARE(face_2151_410_dial_img_21_220864_5);
	LV_IMG_DECLARE(face_2151_410_dial_img_21_220864_6);
	LV_IMG_DECLARE(face_2151_410_dial_img_22_233288_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_22_233288_1);
	LV_IMG_DECLARE(face_2151_410_dial_img_22_233288_2);
	LV_IMG_DECLARE(face_2151_410_dial_img_22_233288_3);
	LV_IMG_DECLARE(face_2151_410_dial_img_22_233288_4);
	LV_IMG_DECLARE(face_2151_410_dial_img_22_233288_5);
	LV_IMG_DECLARE(face_2151_410_dial_img_22_233288_6);
	LV_IMG_DECLARE(face_2151_410_dial_img_23_246741_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_23_246741_1);
	LV_IMG_DECLARE(face_2151_410_dial_img_23_246741_2);
	LV_IMG_DECLARE(face_2151_410_dial_img_23_246741_3);
	LV_IMG_DECLARE(face_2151_410_dial_img_23_246741_4);
	LV_IMG_DECLARE(face_2151_410_dial_img_23_246741_5);
	LV_IMG_DECLARE(face_2151_410_dial_img_23_246741_6);
	LV_IMG_DECLARE(face_2151_410_dial_img_23_246741_7);
	LV_IMG_DECLARE(face_2151_410_dial_img_23_246741_8);
	LV_IMG_DECLARE(face_2151_410_dial_img_23_246741_9);
	LV_IMG_DECLARE(face_2151_410_dial_img_27_254873_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_39_254919_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_43_255480_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_44_255511_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_44_255511_1);
	LV_IMG_DECLARE(face_2151_410_dial_img_44_255511_2);
	LV_IMG_DECLARE(face_2151_410_dial_img_44_255511_3);
	LV_IMG_DECLARE(face_2151_410_dial_img_44_255511_4);
	LV_IMG_DECLARE(face_2151_410_dial_img_44_255511_5);
	LV_IMG_DECLARE(face_2151_410_dial_img_44_255511_6);
	LV_IMG_DECLARE(face_2151_410_dial_img_44_255511_7);
	LV_IMG_DECLARE(face_2151_410_dial_img_44_255511_8);
	LV_IMG_DECLARE(face_2151_410_dial_img_44_255511_9);
	LV_IMG_DECLARE(face_2151_410_dial_img_48_276965_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_50_277299_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_51_279564_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_52_281885_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_53_284210_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_54_286525_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_55_288778_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_56_291179_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_57_293474_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_58_295837_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_preview_0);
	LV_IMG_DECLARE(face_2151_410_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_2151_410(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **));
    void update_time_2151_410(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_2151_410(int temp, int icon);
    void update_status_2151_410(int battery, bool connection);
    void update_activity_2151_410(int steps, int distance, int kcal);
    void update_health_2151_410(int bpm, int oxygen);
    void update_all_2151_410(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_2151_410(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
