
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: TERMINAL_360

#include "terminal_360.h"

#ifdef ENABLE_FACE_TERMINAL_360

lv_obj_t *face_terminal_360;
lv_obj_t *face_terminal_360_0_464;
lv_obj_t *face_terminal_360_1_130092;
lv_obj_t *face_terminal_360_2_130092;
lv_obj_t *face_terminal_360_3_130092;
lv_obj_t *face_terminal_360_4_130092;
lv_obj_t *face_terminal_360_5_130092;
lv_obj_t *face_terminal_360_6_130092;
lv_obj_t *face_terminal_360_7_130092;
lv_obj_t *face_terminal_360_8_130092;
lv_obj_t *face_terminal_360_9_130092;
lv_obj_t *face_terminal_360_10_130092;
lv_obj_t *face_terminal_360_11_130092;
lv_obj_t *face_terminal_360_12_130092;
lv_obj_t *face_terminal_360_13_130092;
lv_obj_t *face_terminal_360_14_130092;
lv_obj_t *face_terminal_360_15_130092;
lv_obj_t *face_terminal_360_16_130092;
lv_obj_t *face_terminal_360_17_130092;
lv_obj_t *face_terminal_360_18_139128;
lv_obj_t *face_terminal_360_19_130092;
lv_obj_t *face_terminal_360_20_130092;
lv_obj_t *face_terminal_360_21_130092;
lv_obj_t *face_terminal_360_22_130092;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif

const lv_img_dsc_t *face_terminal_360_dial_img_1_130092_group[] = {
	&face_terminal_360_dial_img_1_130092_0,
	&face_terminal_360_dial_img_1_130092_1,
	&face_terminal_360_dial_img_1_130092_2,
	&face_terminal_360_dial_img_1_130092_3,
	&face_terminal_360_dial_img_1_130092_4,
	&face_terminal_360_dial_img_1_130092_5,
	&face_terminal_360_dial_img_1_130092_6,
	&face_terminal_360_dial_img_1_130092_7,
	&face_terminal_360_dial_img_1_130092_8,
	&face_terminal_360_dial_img_1_130092_9,
};
const lv_img_dsc_t *face_terminal_360_dial_img_18_139128_group[] = {
	&face_terminal_360_dial_img_18_139128_0,
	&face_terminal_360_dial_img_18_139128_1,
	&face_terminal_360_dial_img_18_139128_2,
	&face_terminal_360_dial_img_18_139128_3,
	&face_terminal_360_dial_img_18_139128_4,
	&face_terminal_360_dial_img_18_139128_5,
	&face_terminal_360_dial_img_18_139128_6,
};




#endif

void init_face_terminal_360(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **)){
#ifdef ENABLE_FACE_TERMINAL_360
    face_terminal_360 = lv_obj_create(NULL);
    lv_obj_clear_flag(face_terminal_360, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_terminal_360, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_terminal_360, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_terminal_360, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_terminal_360, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_terminal_360, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_terminal_360, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_terminal_360, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_terminal_360, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_terminal_360_0_464 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_0_464, &face_terminal_360_dial_img_0_464_0);
    lv_obj_set_width(face_terminal_360_0_464, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_0_464, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_0_464, 0);
    lv_obj_set_y(face_terminal_360_0_464, 0);
    lv_obj_add_flag(face_terminal_360_0_464, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_0_464, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_1_130092 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_1_130092, &face_terminal_360_dial_img_1_130092_0);
    lv_obj_set_width(face_terminal_360_1_130092, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_1_130092, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_1_130092, 258);
    lv_obj_set_y(face_terminal_360_1_130092, 238);
    lv_obj_add_flag(face_terminal_360_1_130092, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_1_130092, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_2_130092 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_2_130092, &face_terminal_360_dial_img_1_130092_0);
    lv_obj_set_width(face_terminal_360_2_130092, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_2_130092, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_2_130092, 233);
    lv_obj_set_y(face_terminal_360_2_130092, 238);
    lv_obj_add_flag(face_terminal_360_2_130092, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_2_130092, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_3_130092 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_3_130092, &face_terminal_360_dial_img_1_130092_0);
    lv_obj_set_width(face_terminal_360_3_130092, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_3_130092, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_3_130092, 208);
    lv_obj_set_y(face_terminal_360_3_130092, 238);
    lv_obj_add_flag(face_terminal_360_3_130092, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_3_130092, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_4_130092 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_4_130092, &face_terminal_360_dial_img_1_130092_0);
    lv_obj_set_width(face_terminal_360_4_130092, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_4_130092, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_4_130092, 183);
    lv_obj_set_y(face_terminal_360_4_130092, 238);
    lv_obj_add_flag(face_terminal_360_4_130092, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_4_130092, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_5_130092 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_5_130092, &face_terminal_360_dial_img_1_130092_0);
    lv_obj_set_width(face_terminal_360_5_130092, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_5_130092, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_5_130092, 158);
    lv_obj_set_y(face_terminal_360_5_130092, 238);
    lv_obj_add_flag(face_terminal_360_5_130092, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_5_130092, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_6_130092 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_6_130092, &face_terminal_360_dial_img_1_130092_0);
    lv_obj_set_width(face_terminal_360_6_130092, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_6_130092, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_6_130092, 208);
    lv_obj_set_y(face_terminal_360_6_130092, 284);
    lv_obj_add_flag(face_terminal_360_6_130092, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_6_130092, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_7_130092 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_7_130092, &face_terminal_360_dial_img_1_130092_0);
    lv_obj_set_width(face_terminal_360_7_130092, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_7_130092, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_7_130092, 183);
    lv_obj_set_y(face_terminal_360_7_130092, 284);
    lv_obj_add_flag(face_terminal_360_7_130092, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_7_130092, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_8_130092 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_8_130092, &face_terminal_360_dial_img_1_130092_0);
    lv_obj_set_width(face_terminal_360_8_130092, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_8_130092, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_8_130092, 158);
    lv_obj_set_y(face_terminal_360_8_130092, 284);
    lv_obj_add_flag(face_terminal_360_8_130092, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_8_130092, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_9_130092 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_9_130092, &face_terminal_360_dial_img_1_130092_0);
    lv_obj_set_width(face_terminal_360_9_130092, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_9_130092, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_9_130092, 304);
    lv_obj_set_y(face_terminal_360_9_130092, 144);
    lv_obj_add_flag(face_terminal_360_9_130092, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_9_130092, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_10_130092 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_10_130092, &face_terminal_360_dial_img_1_130092_0);
    lv_obj_set_width(face_terminal_360_10_130092, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_10_130092, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_10_130092, 279);
    lv_obj_set_y(face_terminal_360_10_130092, 144);
    lv_obj_add_flag(face_terminal_360_10_130092, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_10_130092, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_11_130092 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_11_130092, &face_terminal_360_dial_img_1_130092_0);
    lv_obj_set_width(face_terminal_360_11_130092, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_11_130092, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_11_130092, 243);
    lv_obj_set_y(face_terminal_360_11_130092, 144);
    lv_obj_add_flag(face_terminal_360_11_130092, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_11_130092, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_12_130092 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_12_130092, &face_terminal_360_dial_img_1_130092_0);
    lv_obj_set_width(face_terminal_360_12_130092, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_12_130092, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_12_130092, 218);
    lv_obj_set_y(face_terminal_360_12_130092, 144);
    lv_obj_add_flag(face_terminal_360_12_130092, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_12_130092, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_13_130092 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_13_130092, &face_terminal_360_dial_img_1_130092_0);
    lv_obj_set_width(face_terminal_360_13_130092, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_13_130092, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_13_130092, 183);
    lv_obj_set_y(face_terminal_360_13_130092, 144);
    lv_obj_add_flag(face_terminal_360_13_130092, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_13_130092, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_14_130092 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_14_130092, &face_terminal_360_dial_img_1_130092_0);
    lv_obj_set_width(face_terminal_360_14_130092, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_14_130092, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_14_130092, 158);
    lv_obj_set_y(face_terminal_360_14_130092, 144);
    lv_obj_add_flag(face_terminal_360_14_130092, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_14_130092, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_15_130092 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_15_130092, &face_terminal_360_dial_img_1_130092_0);
    lv_obj_set_width(face_terminal_360_15_130092, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_15_130092, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_15_130092, 208);
    lv_obj_set_y(face_terminal_360_15_130092, 192);
    lv_obj_add_flag(face_terminal_360_15_130092, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_15_130092, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_16_130092 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_16_130092, &face_terminal_360_dial_img_1_130092_0);
    lv_obj_set_width(face_terminal_360_16_130092, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_16_130092, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_16_130092, 183);
    lv_obj_set_y(face_terminal_360_16_130092, 192);
    lv_obj_add_flag(face_terminal_360_16_130092, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_16_130092, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_17_130092 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_17_130092, &face_terminal_360_dial_img_1_130092_0);
    lv_obj_set_width(face_terminal_360_17_130092, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_17_130092, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_17_130092, 158);
    lv_obj_set_y(face_terminal_360_17_130092, 192);
    lv_obj_add_flag(face_terminal_360_17_130092, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_17_130092, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_18_139128 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_18_139128, &face_terminal_360_dial_img_18_139128_0);
    lv_obj_set_width(face_terminal_360_18_139128, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_18_139128, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_18_139128, 158);
    lv_obj_set_y(face_terminal_360_18_139128, 98);
    lv_obj_add_flag(face_terminal_360_18_139128, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_18_139128, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_19_130092 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_19_130092, &face_terminal_360_dial_img_1_130092_0);
    lv_obj_set_width(face_terminal_360_19_130092, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_19_130092, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_19_130092, 183);
    lv_obj_set_y(face_terminal_360_19_130092, 50);
    lv_obj_add_flag(face_terminal_360_19_130092, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_19_130092, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_20_130092 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_20_130092, &face_terminal_360_dial_img_1_130092_0);
    lv_obj_set_width(face_terminal_360_20_130092, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_20_130092, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_20_130092, 158);
    lv_obj_set_y(face_terminal_360_20_130092, 50);
    lv_obj_add_flag(face_terminal_360_20_130092, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_20_130092, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_21_130092 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_21_130092, &face_terminal_360_dial_img_1_130092_0);
    lv_obj_set_width(face_terminal_360_21_130092, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_21_130092, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_21_130092, 243);
    lv_obj_set_y(face_terminal_360_21_130092, 50);
    lv_obj_add_flag(face_terminal_360_21_130092, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_21_130092, LV_OBJ_FLAG_SCROLLABLE );

    face_terminal_360_22_130092 = lv_img_create(face_terminal_360);
    lv_img_set_src(face_terminal_360_22_130092, &face_terminal_360_dial_img_1_130092_0);
    lv_obj_set_width(face_terminal_360_22_130092, LV_SIZE_CONTENT);
    lv_obj_set_height(face_terminal_360_22_130092, LV_SIZE_CONTENT);
    lv_obj_set_x(face_terminal_360_22_130092, 218);
    lv_obj_set_y(face_terminal_360_22_130092, 50);
    lv_obj_add_flag(face_terminal_360_22_130092, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_terminal_360_22_130092, LV_OBJ_FLAG_SCROLLABLE );


    callback("Terminal", &face_terminal_360_dial_img_preview_0, &face_terminal_360, NULL);

#endif
}

void update_time_terminal_360(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_TERMINAL_360
    if (!face_terminal_360)
    {
        return;
    }
	lv_img_set_src(face_terminal_360_9_130092, face_terminal_360_dial_img_1_130092_group[(year / 1) % 10]);
	lv_img_set_src(face_terminal_360_10_130092, face_terminal_360_dial_img_1_130092_group[(year / 10) % 10]);
	lv_img_set_src(face_terminal_360_11_130092, face_terminal_360_dial_img_1_130092_group[(month / 1) % 10]);
	lv_img_set_src(face_terminal_360_12_130092, face_terminal_360_dial_img_1_130092_group[(month / 10) % 10]);
	lv_img_set_src(face_terminal_360_13_130092, face_terminal_360_dial_img_1_130092_group[(day / 1) % 10]);
	lv_img_set_src(face_terminal_360_14_130092, face_terminal_360_dial_img_1_130092_group[(day / 10) % 10]);
	lv_img_set_src(face_terminal_360_18_139128, face_terminal_360_dial_img_18_139128_group[((weekday + 6) / 1) % 7]);
	lv_img_set_src(face_terminal_360_19_130092, face_terminal_360_dial_img_1_130092_group[(hour / 1) % 10]);
	lv_img_set_src(face_terminal_360_20_130092, face_terminal_360_dial_img_1_130092_group[(hour / 10) % 10]);
	lv_img_set_src(face_terminal_360_21_130092, face_terminal_360_dial_img_1_130092_group[(minute / 1) % 10]);
	lv_img_set_src(face_terminal_360_22_130092, face_terminal_360_dial_img_1_130092_group[(minute / 10) % 10]);

#endif
}

void update_weather_terminal_360(int temp, int icon)
{
#ifdef ENABLE_FACE_TERMINAL_360
    if (!face_terminal_360)
    {
        return;
    }

#endif
}

void update_status_terminal_360(int battery, bool connection){
#ifdef ENABLE_FACE_TERMINAL_360
    if (!face_terminal_360)
    {
        return;
    }
	lv_img_set_src(face_terminal_360_15_130092, face_terminal_360_dial_img_1_130092_group[(battery / 1) % 10]);
	lv_img_set_src(face_terminal_360_16_130092, face_terminal_360_dial_img_1_130092_group[(battery / 10) % 10]);
	lv_img_set_src(face_terminal_360_17_130092, face_terminal_360_dial_img_1_130092_group[(battery / 100) % 10]);
	if (battery < 100)
	{
		lv_obj_add_flag(face_terminal_360_17_130092, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_terminal_360_17_130092, LV_OBJ_FLAG_HIDDEN);
	}

#endif
}

void update_activity_terminal_360(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_TERMINAL_360
    if (!face_terminal_360)
    {
        return;
    }
	lv_img_set_src(face_terminal_360_1_130092, face_terminal_360_dial_img_1_130092_group[(steps / 1) % 10]);
	lv_img_set_src(face_terminal_360_2_130092, face_terminal_360_dial_img_1_130092_group[(steps / 10) % 10]);
	lv_img_set_src(face_terminal_360_3_130092, face_terminal_360_dial_img_1_130092_group[(steps / 100) % 10]);
	lv_img_set_src(face_terminal_360_4_130092, face_terminal_360_dial_img_1_130092_group[(steps / 1000) % 10]);
	lv_img_set_src(face_terminal_360_5_130092, face_terminal_360_dial_img_1_130092_group[(steps / 10000) % 10]);

#endif
}

void update_health_terminal_360(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_TERMINAL_360
    if (!face_terminal_360)
    {
        return;
    }
	lv_img_set_src(face_terminal_360_6_130092, face_terminal_360_dial_img_1_130092_group[(bpm / 1) % 10]);
	lv_img_set_src(face_terminal_360_7_130092, face_terminal_360_dial_img_1_130092_group[(bpm / 10) % 10]);
	lv_img_set_src(face_terminal_360_8_130092, face_terminal_360_dial_img_1_130092_group[(bpm / 100) % 10]);

#endif
}

void update_all_terminal_360(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_TERMINAL_360
    update_time_terminal_360(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_terminal_360(temp, icon);
    update_status_terminal_360(battery, connection);
    update_activity_terminal_360(steps, distance, kcal);
    update_health_terminal_360(bpm, oxygen);
#endif
}

void update_check_terminal_360(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_TERMINAL_360
    if (root != face_terminal_360)
    {
        return;
    }
    update_time_terminal_360(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_terminal_360(temp, icon);
    update_status_terminal_360(battery, connection);
    update_activity_terminal_360(steps, distance, kcal);
    update_health_terminal_360(bpm, oxygen);
#endif
}


