
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: TERMINAL_360

#ifndef _FACE_TERMINAL_360_H
#define _FACE_TERMINAL_360_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"
#include "app_hal.h"

//#define ENABLE_FACE_TERMINAL_360 // (Terminal) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_TERMINAL_360
    extern lv_obj_t *face_terminal_360;
	extern lv_obj_t *face_terminal_360_0_464;
	extern lv_obj_t *face_terminal_360_1_130092;
	extern lv_obj_t *face_terminal_360_2_130092;
	extern lv_obj_t *face_terminal_360_3_130092;
	extern lv_obj_t *face_terminal_360_4_130092;
	extern lv_obj_t *face_terminal_360_5_130092;
	extern lv_obj_t *face_terminal_360_6_130092;
	extern lv_obj_t *face_terminal_360_7_130092;
	extern lv_obj_t *face_terminal_360_8_130092;
	extern lv_obj_t *face_terminal_360_9_130092;
	extern lv_obj_t *face_terminal_360_10_130092;
	extern lv_obj_t *face_terminal_360_11_130092;
	extern lv_obj_t *face_terminal_360_12_130092;
	extern lv_obj_t *face_terminal_360_13_130092;
	extern lv_obj_t *face_terminal_360_14_130092;
	extern lv_obj_t *face_terminal_360_15_130092;
	extern lv_obj_t *face_terminal_360_16_130092;
	extern lv_obj_t *face_terminal_360_17_130092;
	extern lv_obj_t *face_terminal_360_18_139128;
	extern lv_obj_t *face_terminal_360_19_130092;
	extern lv_obj_t *face_terminal_360_20_130092;
	extern lv_obj_t *face_terminal_360_21_130092;
	extern lv_obj_t *face_terminal_360_22_130092;


	LV_IMG_DECLARE(face_terminal_360_dial_img_0_464_0);
	LV_IMG_DECLARE(face_terminal_360_dial_img_1_130092_0);
	LV_IMG_DECLARE(face_terminal_360_dial_img_1_130092_1);
	LV_IMG_DECLARE(face_terminal_360_dial_img_1_130092_2);
	LV_IMG_DECLARE(face_terminal_360_dial_img_1_130092_3);
	LV_IMG_DECLARE(face_terminal_360_dial_img_1_130092_4);
	LV_IMG_DECLARE(face_terminal_360_dial_img_1_130092_5);
	LV_IMG_DECLARE(face_terminal_360_dial_img_1_130092_6);
	LV_IMG_DECLARE(face_terminal_360_dial_img_1_130092_7);
	LV_IMG_DECLARE(face_terminal_360_dial_img_1_130092_8);
	LV_IMG_DECLARE(face_terminal_360_dial_img_1_130092_9);
	LV_IMG_DECLARE(face_terminal_360_dial_img_18_139128_0);
	LV_IMG_DECLARE(face_terminal_360_dial_img_18_139128_1);
	LV_IMG_DECLARE(face_terminal_360_dial_img_18_139128_2);
	LV_IMG_DECLARE(face_terminal_360_dial_img_18_139128_3);
	LV_IMG_DECLARE(face_terminal_360_dial_img_18_139128_4);
	LV_IMG_DECLARE(face_terminal_360_dial_img_18_139128_5);
	LV_IMG_DECLARE(face_terminal_360_dial_img_18_139128_6);
	LV_IMG_DECLARE(face_terminal_360_dial_img_preview_0);
	LV_IMG_DECLARE(face_terminal_360_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_terminal_360(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **));
    void update_time_terminal_360(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_terminal_360(int temp, int icon);
    void update_status_terminal_360(int battery, bool connection);
    void update_activity_terminal_360(int steps, int distance, int kcal);
    void update_health_terminal_360(int bpm, int oxygen);
    void update_all_terminal_360(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_terminal_360(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
