
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: WFB_RESIZED

#include "../wfb_resized.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif


const LV_ATTRIBUTE_MEM_ALIGN uint8_t face_wfb_resized_dial_img_26_66902_data_0[] = {
	0xF7,0xBE,0xFF,0xF7,0xBE,0xFF,
    };
        


const lv_img_dsc_t face_wfb_resized_dial_img_26_66902_0 = {
    .header.always_zero = 0,
    .header.w = 1,
    .header.h = 2,
    .data_size = sizeof(face_wfb_resized_dial_img_26_66902_data_0),
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .data = face_wfb_resized_dial_img_26_66902_data_0};

    