
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 228_410

#ifndef _FACE_228_410_H
#define _FACE_228_410_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"
#include "app_hal.h"

//#define ENABLE_FACE_228_410 // (174) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_228_410
    extern lv_obj_t *face_228_410;
	extern lv_obj_t *face_228_410_0_184;
	extern lv_obj_t *face_228_410_1_202412;
	extern lv_obj_t *face_228_410_2_202412;
	extern lv_obj_t *face_228_410_3_205896;
	extern lv_obj_t *face_228_410_4_205896;
	extern lv_obj_t *face_228_410_5_205896;
	extern lv_obj_t *face_228_410_6_205896;
	extern lv_obj_t *face_228_410_8_259931;


	LV_IMG_DECLARE(face_228_410_dial_img_0_184_0);
	LV_IMG_DECLARE(face_228_410_dial_img_1_202412_0);
	LV_IMG_DECLARE(face_228_410_dial_img_1_202412_1);
	LV_IMG_DECLARE(face_228_410_dial_img_1_202412_2);
	LV_IMG_DECLARE(face_228_410_dial_img_1_202412_3);
	LV_IMG_DECLARE(face_228_410_dial_img_1_202412_4);
	LV_IMG_DECLARE(face_228_410_dial_img_1_202412_5);
	LV_IMG_DECLARE(face_228_410_dial_img_1_202412_6);
	LV_IMG_DECLARE(face_228_410_dial_img_1_202412_7);
	LV_IMG_DECLARE(face_228_410_dial_img_1_202412_8);
	LV_IMG_DECLARE(face_228_410_dial_img_1_202412_9);
	LV_IMG_DECLARE(face_228_410_dial_img_3_205896_0);
	LV_IMG_DECLARE(face_228_410_dial_img_3_205896_1);
	LV_IMG_DECLARE(face_228_410_dial_img_3_205896_2);
	LV_IMG_DECLARE(face_228_410_dial_img_3_205896_3);
	LV_IMG_DECLARE(face_228_410_dial_img_3_205896_4);
	LV_IMG_DECLARE(face_228_410_dial_img_3_205896_5);
	LV_IMG_DECLARE(face_228_410_dial_img_3_205896_6);
	LV_IMG_DECLARE(face_228_410_dial_img_3_205896_7);
	LV_IMG_DECLARE(face_228_410_dial_img_3_205896_8);
	LV_IMG_DECLARE(face_228_410_dial_img_3_205896_9);
	LV_IMG_DECLARE(face_228_410_dial_img_7_252330_0);
	LV_IMG_DECLARE(face_228_410_dial_img_7_252330_1);
	LV_IMG_DECLARE(face_228_410_dial_img_7_252330_2);
	LV_IMG_DECLARE(face_228_410_dial_img_7_252330_3);
	LV_IMG_DECLARE(face_228_410_dial_img_7_252330_4);
	LV_IMG_DECLARE(face_228_410_dial_img_7_252330_5);
	LV_IMG_DECLARE(face_228_410_dial_img_7_252330_6);
	LV_IMG_DECLARE(face_228_410_dial_img_8_259931_0);
	LV_IMG_DECLARE(face_228_410_dial_img_8_259931_1);
	LV_IMG_DECLARE(face_228_410_dial_img_8_259931_2);
	LV_IMG_DECLARE(face_228_410_dial_img_8_259931_3);
	LV_IMG_DECLARE(face_228_410_dial_img_8_259931_4);
	LV_IMG_DECLARE(face_228_410_dial_img_8_259931_5);
	LV_IMG_DECLARE(face_228_410_dial_img_8_259931_6);
	LV_IMG_DECLARE(face_228_410_dial_img_preview_0);
	LV_IMG_DECLARE(face_228_410_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_228_410(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **));
    void update_time_228_410(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_228_410(int temp, int icon);
    void update_status_228_410(int battery, bool connection);
    void update_activity_228_410(int steps, int distance, int kcal);
    void update_health_228_410(int bpm, int oxygen);
    void update_all_228_410(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_228_410(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
