
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 34_2_466

#ifndef _FACE_34_2_466_H
#define _FACE_34_2_466_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"
#include "app_hal.h"

//#define ENABLE_FACE_34_2_466 // (Shadow) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_34_2_466
    extern lv_obj_t *face_34_2_466;
	extern lv_obj_t *face_34_2_466_0_304;
	extern lv_obj_t *face_34_2_466_1_217952;
	extern lv_obj_t *face_34_2_466_2_218013;
	extern lv_obj_t *face_34_2_466_3_218013;
	extern lv_obj_t *face_34_2_466_4_217952;
	extern lv_obj_t *face_34_2_466_5_218013;
	extern lv_obj_t *face_34_2_466_6_218013;
	extern lv_obj_t *face_34_2_466_7_218013;
	extern lv_obj_t *face_34_2_466_8_218013;
	extern lv_obj_t *face_34_2_466_9_221495;
	extern lv_obj_t *face_34_2_466_10_221495;
	extern lv_obj_t *face_34_2_466_11_321827;
	extern lv_obj_t *face_34_2_466_12_321827;
	extern lv_obj_t *face_34_2_466_14_439096;


	LV_IMG_DECLARE(face_34_2_466_dial_img_0_304_0);
	LV_IMG_DECLARE(face_34_2_466_dial_img_1_217952_0);
	LV_IMG_DECLARE(face_34_2_466_dial_img_2_218013_0);
	LV_IMG_DECLARE(face_34_2_466_dial_img_2_218013_1);
	LV_IMG_DECLARE(face_34_2_466_dial_img_2_218013_2);
	LV_IMG_DECLARE(face_34_2_466_dial_img_2_218013_3);
	LV_IMG_DECLARE(face_34_2_466_dial_img_2_218013_4);
	LV_IMG_DECLARE(face_34_2_466_dial_img_2_218013_5);
	LV_IMG_DECLARE(face_34_2_466_dial_img_2_218013_6);
	LV_IMG_DECLARE(face_34_2_466_dial_img_2_218013_7);
	LV_IMG_DECLARE(face_34_2_466_dial_img_2_218013_8);
	LV_IMG_DECLARE(face_34_2_466_dial_img_2_218013_9);
	LV_IMG_DECLARE(face_34_2_466_dial_img_9_221495_0);
	LV_IMG_DECLARE(face_34_2_466_dial_img_9_221495_1);
	LV_IMG_DECLARE(face_34_2_466_dial_img_9_221495_2);
	LV_IMG_DECLARE(face_34_2_466_dial_img_9_221495_3);
	LV_IMG_DECLARE(face_34_2_466_dial_img_9_221495_4);
	LV_IMG_DECLARE(face_34_2_466_dial_img_9_221495_5);
	LV_IMG_DECLARE(face_34_2_466_dial_img_9_221495_6);
	LV_IMG_DECLARE(face_34_2_466_dial_img_9_221495_7);
	LV_IMG_DECLARE(face_34_2_466_dial_img_9_221495_8);
	LV_IMG_DECLARE(face_34_2_466_dial_img_9_221495_9);
	LV_IMG_DECLARE(face_34_2_466_dial_img_11_321827_0);
	LV_IMG_DECLARE(face_34_2_466_dial_img_11_321827_1);
	LV_IMG_DECLARE(face_34_2_466_dial_img_11_321827_2);
	LV_IMG_DECLARE(face_34_2_466_dial_img_11_321827_3);
	LV_IMG_DECLARE(face_34_2_466_dial_img_11_321827_4);
	LV_IMG_DECLARE(face_34_2_466_dial_img_11_321827_5);
	LV_IMG_DECLARE(face_34_2_466_dial_img_11_321827_6);
	LV_IMG_DECLARE(face_34_2_466_dial_img_11_321827_7);
	LV_IMG_DECLARE(face_34_2_466_dial_img_11_321827_8);
	LV_IMG_DECLARE(face_34_2_466_dial_img_11_321827_9);
	LV_IMG_DECLARE(face_34_2_466_dial_img_13_422621_0);
	LV_IMG_DECLARE(face_34_2_466_dial_img_13_422621_1);
	LV_IMG_DECLARE(face_34_2_466_dial_img_13_422621_2);
	LV_IMG_DECLARE(face_34_2_466_dial_img_13_422621_3);
	LV_IMG_DECLARE(face_34_2_466_dial_img_13_422621_4);
	LV_IMG_DECLARE(face_34_2_466_dial_img_13_422621_5);
	LV_IMG_DECLARE(face_34_2_466_dial_img_13_422621_6);
	LV_IMG_DECLARE(face_34_2_466_dial_img_14_439096_0);
	LV_IMG_DECLARE(face_34_2_466_dial_img_14_439096_1);
	LV_IMG_DECLARE(face_34_2_466_dial_img_14_439096_2);
	LV_IMG_DECLARE(face_34_2_466_dial_img_14_439096_3);
	LV_IMG_DECLARE(face_34_2_466_dial_img_14_439096_4);
	LV_IMG_DECLARE(face_34_2_466_dial_img_14_439096_5);
	LV_IMG_DECLARE(face_34_2_466_dial_img_14_439096_6);
	LV_IMG_DECLARE(face_34_2_466_dial_img_preview_0);
	LV_IMG_DECLARE(face_34_2_466_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_34_2_466(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **));
    void update_time_34_2_466(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_34_2_466(int temp, int icon);
    void update_status_34_2_466(int battery, bool connection);
    void update_activity_34_2_466(int steps, int distance, int kcal);
    void update_health_34_2_466(int bpm, int oxygen);
    void update_all_34_2_466(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_34_2_466(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
