
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 34_2_466

#include "34_2_466.h"

#ifdef ENABLE_FACE_34_2_466

lv_obj_t *face_34_2_466;
lv_obj_t *face_34_2_466_0_304;
lv_obj_t *face_34_2_466_1_217952;
lv_obj_t *face_34_2_466_2_218013;
lv_obj_t *face_34_2_466_3_218013;
lv_obj_t *face_34_2_466_4_217952;
lv_obj_t *face_34_2_466_5_218013;
lv_obj_t *face_34_2_466_6_218013;
lv_obj_t *face_34_2_466_7_218013;
lv_obj_t *face_34_2_466_8_218013;
lv_obj_t *face_34_2_466_9_221495;
lv_obj_t *face_34_2_466_10_221495;
lv_obj_t *face_34_2_466_11_321827;
lv_obj_t *face_34_2_466_12_321827;
lv_obj_t *face_34_2_466_14_439096;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif

const lv_img_dsc_t *face_34_2_466_dial_img_2_218013_group[] = {
	&face_34_2_466_dial_img_2_218013_0,
	&face_34_2_466_dial_img_2_218013_1,
	&face_34_2_466_dial_img_2_218013_2,
	&face_34_2_466_dial_img_2_218013_3,
	&face_34_2_466_dial_img_2_218013_4,
	&face_34_2_466_dial_img_2_218013_5,
	&face_34_2_466_dial_img_2_218013_6,
	&face_34_2_466_dial_img_2_218013_7,
	&face_34_2_466_dial_img_2_218013_8,
	&face_34_2_466_dial_img_2_218013_9,
};
const lv_img_dsc_t *face_34_2_466_dial_img_9_221495_group[] = {
	&face_34_2_466_dial_img_9_221495_0,
	&face_34_2_466_dial_img_9_221495_1,
	&face_34_2_466_dial_img_9_221495_2,
	&face_34_2_466_dial_img_9_221495_3,
	&face_34_2_466_dial_img_9_221495_4,
	&face_34_2_466_dial_img_9_221495_5,
	&face_34_2_466_dial_img_9_221495_6,
	&face_34_2_466_dial_img_9_221495_7,
	&face_34_2_466_dial_img_9_221495_8,
	&face_34_2_466_dial_img_9_221495_9,
};
const lv_img_dsc_t *face_34_2_466_dial_img_11_321827_group[] = {
	&face_34_2_466_dial_img_11_321827_0,
	&face_34_2_466_dial_img_11_321827_1,
	&face_34_2_466_dial_img_11_321827_2,
	&face_34_2_466_dial_img_11_321827_3,
	&face_34_2_466_dial_img_11_321827_4,
	&face_34_2_466_dial_img_11_321827_5,
	&face_34_2_466_dial_img_11_321827_6,
	&face_34_2_466_dial_img_11_321827_7,
	&face_34_2_466_dial_img_11_321827_8,
	&face_34_2_466_dial_img_11_321827_9,
};
const lv_img_dsc_t *face_34_2_466_dial_img_13_422621_group[] = {
	&face_34_2_466_dial_img_13_422621_0,
	&face_34_2_466_dial_img_13_422621_1,
	&face_34_2_466_dial_img_13_422621_2,
	&face_34_2_466_dial_img_13_422621_3,
	&face_34_2_466_dial_img_13_422621_4,
	&face_34_2_466_dial_img_13_422621_5,
	&face_34_2_466_dial_img_13_422621_6,
};
const lv_img_dsc_t *face_34_2_466_dial_img_14_439096_group[] = {
	&face_34_2_466_dial_img_14_439096_0,
	&face_34_2_466_dial_img_14_439096_1,
	&face_34_2_466_dial_img_14_439096_2,
	&face_34_2_466_dial_img_14_439096_3,
	&face_34_2_466_dial_img_14_439096_4,
	&face_34_2_466_dial_img_14_439096_5,
	&face_34_2_466_dial_img_14_439096_6,
};




#endif

void init_face_34_2_466(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **)){
#ifdef ENABLE_FACE_34_2_466
    face_34_2_466 = lv_obj_create(NULL);
    lv_obj_clear_flag(face_34_2_466, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_34_2_466, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_34_2_466, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_34_2_466, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_34_2_466, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_34_2_466, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_34_2_466, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_34_2_466, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_34_2_466, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_34_2_466_0_304 = lv_img_create(face_34_2_466);
    lv_img_set_src(face_34_2_466_0_304, &face_34_2_466_dial_img_0_304_0);
    lv_obj_set_width(face_34_2_466_0_304, LV_SIZE_CONTENT);
    lv_obj_set_height(face_34_2_466_0_304, LV_SIZE_CONTENT);
    lv_obj_set_x(face_34_2_466_0_304, 0);
    lv_obj_set_y(face_34_2_466_0_304, 0);
    lv_obj_add_flag(face_34_2_466_0_304, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_34_2_466_0_304, LV_OBJ_FLAG_SCROLLABLE );

    face_34_2_466_1_217952 = lv_img_create(face_34_2_466);
    lv_img_set_src(face_34_2_466_1_217952, &face_34_2_466_dial_img_1_217952_0);
    lv_obj_set_width(face_34_2_466_1_217952, LV_SIZE_CONTENT);
    lv_obj_set_height(face_34_2_466_1_217952, LV_SIZE_CONTENT);
    lv_obj_set_x(face_34_2_466_1_217952, 209);
    lv_obj_set_y(face_34_2_466_1_217952, 81);
    lv_obj_add_flag(face_34_2_466_1_217952, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_34_2_466_1_217952, LV_OBJ_FLAG_SCROLLABLE );

    face_34_2_466_2_218013 = lv_img_create(face_34_2_466);
    lv_img_set_src(face_34_2_466_2_218013, &face_34_2_466_dial_img_2_218013_0);
    lv_obj_set_width(face_34_2_466_2_218013, LV_SIZE_CONTENT);
    lv_obj_set_height(face_34_2_466_2_218013, LV_SIZE_CONTENT);
    lv_obj_set_x(face_34_2_466_2_218013, 194);
    lv_obj_set_y(face_34_2_466_2_218013, 71);
    lv_obj_add_flag(face_34_2_466_2_218013, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_34_2_466_2_218013, LV_OBJ_FLAG_SCROLLABLE );

    face_34_2_466_3_218013 = lv_img_create(face_34_2_466);
    lv_img_set_src(face_34_2_466_3_218013, &face_34_2_466_dial_img_2_218013_0);
    lv_obj_set_width(face_34_2_466_3_218013, LV_SIZE_CONTENT);
    lv_obj_set_height(face_34_2_466_3_218013, LV_SIZE_CONTENT);
    lv_obj_set_x(face_34_2_466_3_218013, 178);
    lv_obj_set_y(face_34_2_466_3_218013, 71);
    lv_obj_add_flag(face_34_2_466_3_218013, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_34_2_466_3_218013, LV_OBJ_FLAG_SCROLLABLE );

    face_34_2_466_4_217952 = lv_img_create(face_34_2_466);
    lv_img_set_src(face_34_2_466_4_217952, &face_34_2_466_dial_img_1_217952_0);
    lv_obj_set_width(face_34_2_466_4_217952, LV_SIZE_CONTENT);
    lv_obj_set_height(face_34_2_466_4_217952, LV_SIZE_CONTENT);
    lv_obj_set_x(face_34_2_466_4_217952, 250);
    lv_obj_set_y(face_34_2_466_4_217952, 81);
    lv_obj_add_flag(face_34_2_466_4_217952, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_34_2_466_4_217952, LV_OBJ_FLAG_SCROLLABLE );

    face_34_2_466_5_218013 = lv_img_create(face_34_2_466);
    lv_img_set_src(face_34_2_466_5_218013, &face_34_2_466_dial_img_2_218013_0);
    lv_obj_set_width(face_34_2_466_5_218013, LV_SIZE_CONTENT);
    lv_obj_set_height(face_34_2_466_5_218013, LV_SIZE_CONTENT);
    lv_obj_set_x(face_34_2_466_5_218013, 234);
    lv_obj_set_y(face_34_2_466_5_218013, 71);
    lv_obj_add_flag(face_34_2_466_5_218013, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_34_2_466_5_218013, LV_OBJ_FLAG_SCROLLABLE );

    face_34_2_466_6_218013 = lv_img_create(face_34_2_466);
    lv_img_set_src(face_34_2_466_6_218013, &face_34_2_466_dial_img_2_218013_0);
    lv_obj_set_width(face_34_2_466_6_218013, LV_SIZE_CONTENT);
    lv_obj_set_height(face_34_2_466_6_218013, LV_SIZE_CONTENT);
    lv_obj_set_x(face_34_2_466_6_218013, 219);
    lv_obj_set_y(face_34_2_466_6_218013, 71);
    lv_obj_add_flag(face_34_2_466_6_218013, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_34_2_466_6_218013, LV_OBJ_FLAG_SCROLLABLE );

    face_34_2_466_7_218013 = lv_img_create(face_34_2_466);
    lv_img_set_src(face_34_2_466_7_218013, &face_34_2_466_dial_img_2_218013_0);
    lv_obj_set_width(face_34_2_466_7_218013, LV_SIZE_CONTENT);
    lv_obj_set_height(face_34_2_466_7_218013, LV_SIZE_CONTENT);
    lv_obj_set_x(face_34_2_466_7_218013, 275);
    lv_obj_set_y(face_34_2_466_7_218013, 71);
    lv_obj_add_flag(face_34_2_466_7_218013, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_34_2_466_7_218013, LV_OBJ_FLAG_SCROLLABLE );

    face_34_2_466_8_218013 = lv_img_create(face_34_2_466);
    lv_img_set_src(face_34_2_466_8_218013, &face_34_2_466_dial_img_2_218013_0);
    lv_obj_set_width(face_34_2_466_8_218013, LV_SIZE_CONTENT);
    lv_obj_set_height(face_34_2_466_8_218013, LV_SIZE_CONTENT);
    lv_obj_set_x(face_34_2_466_8_218013, 260);
    lv_obj_set_y(face_34_2_466_8_218013, 71);
    lv_obj_add_flag(face_34_2_466_8_218013, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_34_2_466_8_218013, LV_OBJ_FLAG_SCROLLABLE );

    face_34_2_466_9_221495 = lv_img_create(face_34_2_466);
    lv_img_set_src(face_34_2_466_9_221495, &face_34_2_466_dial_img_9_221495_0);
    lv_obj_set_width(face_34_2_466_9_221495, LV_SIZE_CONTENT);
    lv_obj_set_height(face_34_2_466_9_221495, LV_SIZE_CONTENT);
    lv_obj_set_x(face_34_2_466_9_221495, 234);
    lv_obj_set_y(face_34_2_466_9_221495, 114);
    lv_obj_add_flag(face_34_2_466_9_221495, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_34_2_466_9_221495, LV_OBJ_FLAG_SCROLLABLE );

    face_34_2_466_10_221495 = lv_img_create(face_34_2_466);
    lv_img_set_src(face_34_2_466_10_221495, &face_34_2_466_dial_img_9_221495_0);
    lv_obj_set_width(face_34_2_466_10_221495, LV_SIZE_CONTENT);
    lv_obj_set_height(face_34_2_466_10_221495, LV_SIZE_CONTENT);
    lv_obj_set_x(face_34_2_466_10_221495, 139);
    lv_obj_set_y(face_34_2_466_10_221495, 114);
    lv_obj_add_flag(face_34_2_466_10_221495, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_34_2_466_10_221495, LV_OBJ_FLAG_SCROLLABLE );

    face_34_2_466_11_321827 = lv_img_create(face_34_2_466);
    lv_img_set_src(face_34_2_466_11_321827, &face_34_2_466_dial_img_11_321827_0);
    lv_obj_set_width(face_34_2_466_11_321827, LV_SIZE_CONTENT);
    lv_obj_set_height(face_34_2_466_11_321827, LV_SIZE_CONTENT);
    lv_obj_set_x(face_34_2_466_11_321827, 234);
    lv_obj_set_y(face_34_2_466_11_321827, 238);
    lv_obj_add_flag(face_34_2_466_11_321827, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_34_2_466_11_321827, LV_OBJ_FLAG_SCROLLABLE );

    face_34_2_466_12_321827 = lv_img_create(face_34_2_466);
    lv_img_set_src(face_34_2_466_12_321827, &face_34_2_466_dial_img_11_321827_0);
    lv_obj_set_width(face_34_2_466_12_321827, LV_SIZE_CONTENT);
    lv_obj_set_height(face_34_2_466_12_321827, LV_SIZE_CONTENT);
    lv_obj_set_x(face_34_2_466_12_321827, 139);
    lv_obj_set_y(face_34_2_466_12_321827, 238);
    lv_obj_add_flag(face_34_2_466_12_321827, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_34_2_466_12_321827, LV_OBJ_FLAG_SCROLLABLE );

    face_34_2_466_14_439096 = lv_img_create(face_34_2_466);
    lv_img_set_src(face_34_2_466_14_439096, &face_34_2_466_dial_img_14_439096_0);
    lv_obj_set_width(face_34_2_466_14_439096, LV_SIZE_CONTENT);
    lv_obj_set_height(face_34_2_466_14_439096, LV_SIZE_CONTENT);
    lv_obj_set_x(face_34_2_466_14_439096, 203);
    lv_obj_set_y(face_34_2_466_14_439096, 372);
    lv_obj_add_flag(face_34_2_466_14_439096, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_34_2_466_14_439096, LV_OBJ_FLAG_SCROLLABLE );


    callback("Shadow", &face_34_2_466_dial_img_preview_0, &face_34_2_466, NULL);

#endif
}

void update_time_34_2_466(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_34_2_466
    if (!face_34_2_466)
    {
        return;
    }
	lv_img_set_src(face_34_2_466_2_218013, face_34_2_466_dial_img_2_218013_group[(year / 1) % 10]);
	lv_img_set_src(face_34_2_466_3_218013, face_34_2_466_dial_img_2_218013_group[(year / 10) % 10]);
	lv_img_set_src(face_34_2_466_5_218013, face_34_2_466_dial_img_2_218013_group[(month / 1) % 10]);
	lv_img_set_src(face_34_2_466_6_218013, face_34_2_466_dial_img_2_218013_group[(month / 10) % 10]);
	lv_img_set_src(face_34_2_466_7_218013, face_34_2_466_dial_img_2_218013_group[(day / 1) % 10]);
	lv_img_set_src(face_34_2_466_8_218013, face_34_2_466_dial_img_2_218013_group[(day / 10) % 10]);
	lv_img_set_src(face_34_2_466_9_221495, face_34_2_466_dial_img_9_221495_group[(hour / 1) % 10]);
	lv_img_set_src(face_34_2_466_10_221495, face_34_2_466_dial_img_9_221495_group[(hour / 10) % 10]);
	lv_img_set_src(face_34_2_466_11_321827, face_34_2_466_dial_img_11_321827_group[(minute / 1) % 10]);
	lv_img_set_src(face_34_2_466_12_321827, face_34_2_466_dial_img_11_321827_group[(minute / 10) % 10]);
	lv_img_set_src(face_34_2_466_14_439096, face_34_2_466_dial_img_14_439096_group[((weekday + 6) / 1) % 7]);

#endif
}

void update_weather_34_2_466(int temp, int icon)
{
#ifdef ENABLE_FACE_34_2_466
    if (!face_34_2_466)
    {
        return;
    }

#endif
}

void update_status_34_2_466(int battery, bool connection){
#ifdef ENABLE_FACE_34_2_466
    if (!face_34_2_466)
    {
        return;
    }

#endif
}

void update_activity_34_2_466(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_34_2_466
    if (!face_34_2_466)
    {
        return;
    }

#endif
}

void update_health_34_2_466(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_34_2_466
    if (!face_34_2_466)
    {
        return;
    }

#endif
}

void update_all_34_2_466(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_34_2_466
    update_time_34_2_466(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_34_2_466(temp, icon);
    update_status_34_2_466(battery, connection);
    update_activity_34_2_466(steps, distance, kcal);
    update_health_34_2_466(bpm, oxygen);
#endif
}

void update_check_34_2_466(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_34_2_466
    if (root != face_34_2_466)
    {
        return;
    }
    update_time_34_2_466(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_34_2_466(temp, icon);
    update_status_34_2_466(battery, connection);
    update_activity_34_2_466(steps, distance, kcal);
    update_health_34_2_466(bpm, oxygen);
#endif
}


